### ISSUE TITLE
Drag and drop doesn't work with Qt5.4

### ISSUE THREAD

**Issue by madsl** [lxde/pcmanfm-qt#100]
I'm at commit 1426aeb618. PCManFM-qt doesn't support drag and drop when compiled with Qt5. Tested dragging stuff into KWrite, audacious, chromium, firefox, nothing works anymore. Worked when compiled with Qt4.

**Comment by PCMan** [comment]
Confirmed. Opening files using Dnd is broken.

**Comment by PCMan** [comment]
Just confirmed that it is a known bug of Qt 5.4. It will be fixed in Qt 5.4.1.
So it's not our issue.
