### ISSUE TITLE
rearrange tabs by drag&drop

### ISSUE THREAD

**Issue by pmattern** [lxde/pcmanfm-qt#107]
It would be good if the order of tabs could be changed, either by some keyboard shortcut or drag&drop.

The latter is, if this should be of interest, possible in PCManFM's GTK version. The issue doesn't seem to be related to #100 as tabs can't be arranged in a context where drag&drop works either.

Seen on Arch Linux x86_64 running latest git version compiled against Qt5.

**Comment by PCMan** [comment]
done.
