### ISSUE TITLE
Can't change bookmarks

### ISSUE THREAD

**Issue by V10lator** [lxde/pcmanfm-qt#111]
A few days ago I changed my username and with it moved my home folder. So far I managed to change the settings of all applications except the bookmarks of pcmanfm-qt. I tried:
- Changing the existing enties.
- Removing the existing entries and creating new ones.
- Adding new entries
But when I click on OK all my changes are reverted. As I added new entries in the past I guess the problem is that the old folder don't exist anymore.

**Comment by PCMan** [comment]
fixed.
