### ISSUE TITLE
FTBFS: error: 'class PCManFM::TabBar' has no member named 'setChangeCurrentOnDrag'

### ISSUE THREAD

**Issue by agaida** [lxde/pcmanfm-qt#121]
* @PCMan latest commit, build with pbuilder
<pre>
/tmp/buildd/pcmanfm-qt-0.8.1/pcmanfm/mainwindow.cpp: In constructor 'PCManFM::MainWindow::MainWindow(FmPath*)':
/tmp/buildd/pcmanfm-qt-0.8.1/pcmanfm/mainwindow.cpp:84:14: error: 'class PCManFM::TabBar' has no member named 'setChangeCurrentOnDrag'
   ui.tabBar->setChangeCurrentOnDrag(true);
</pre>

**Comment by PCMan** [comment]
Sorry, that's a Qt 5.4 feature.
I should have #ifdef that.
