### ISSUE TITLE
"Move to trash " on mounted devices

### ISSUE THREAD

**Issue by rcmn** [lxde/pcmanfm-qt#125]
Is someone can reproduce a bug I have that any mounted device / share (NTFS,FAT32,SMB) .Right click "Move to trash " does not work . However "Shift + Del" will remove the file. Also can I launch pcmanfm-qt with an argument to see an output ? So that I can report better .
ubuntu repo

**Comment by jleclanche** [comment]
@PCMan can you look at this one for 0.9 since we delayed?
