### ISSUE TITLE
Open With... menu for directories

### ISSUE THREAD

**Issue by tlhpray** [lxde/pcmanfm-qt#129]
As it is directories don't have option to be opened with application of choice. There are many cases where I want to open/parse folder (inode/directory mime type) with/to other program but I can't do it in simple way with pcmanfm-qt. I propose to add same menu (open with...) like we have for files.

**Comment by pmattern** [comment]
As of 60568c9 the feature is basically provided. It cannot be invoked from all locations where it makes sense which is addressed in #273.
