### ISSUE TITLE
Desktop not refreshing

### ISSUE THREAD

**Issue by ghost** [lxde/pcmanfm-qt#135]
Desktop not refreshing when deleting or moving files from within a program.
Now I got all these useless thumbnails laying on my wallpaper.

**Comment by tsujan** [comment]
Not reproducible for a long time. Closing.

**Comment by Neonunux** [comment]
1. set a picture.png as wallpaper
2. deconnect from windows manager
3. login

app crash because there's no fallback here:
https://github.com/lxqt/pcmanfm-qt/blob/957720b3b3a63b1ab363422cf21a991a0340c4c6/pcmanfm/desktoppreferencesdialog.cpp#L160

**Comment by Neonunux** [comment]
@tsujan Sorry, i didn't mention versions I use :

i'm working on Lubuntu 18.10 and 

Package: pcmanfm-qt
Version: 0.13.0-2ubuntu2

Package: pcmanfm
Version: 1.3.0-1

Package: liblxqt0
Version: 0.13.0-0ubuntu1

Package: lxqt
Version: 27

**Comment by tsujan** [comment]
@Neonunux With the git pcmanfm-qt, no crash happens after deleting the wallpaper image (although I didn't understand "deconnect from windows manager" -- window manager has nothing to do with pcmanfm-qt).

**Comment by Neonunux** [comment]
error, i had to write: disconnect from the desktop manager
