### ISSUE TITLE
Desktop Settings appear under "Other"

### ISSUE THREAD

**Issue by stefonarch** [lxde/pcmanfm-qt#136]
pcmanfm-qt-desktop-pref.desktop ends up in menu among "other", non in preferences.
Introducing "Settings" solves. Tested on 2 different PC with git-packages from AUR.
Categories=Settings;Qt;DesktopSettings;

**Comment by stefonarch** [comment]
PS: same issue with lxqt-about.desktop

**Comment by pmattern** [comment]
**pcmanfm-qt-desktop-pref.desktop**
Recent version of lxqt-applications.menu is including pcmanfm-qt-desktop-pref.desktop by its filename and independent of line "Categories"
> \<!-- Include some optional components here --\>
> [...]
> \<Filename\>pcmanfm-qt-desktop-pref.desktop\</Filename\>

So latest Git version of lxqt-common which is providing lxqt-applications.menu should fix the issue provided that Applications menu is using lxqt-applications.menu. The latter can be seen from its configuration window which in turn can be invoked from the icon's context menu.

**lxqt-about.desktop**
Your findings are right. Note that including LXQt about in "Settings" was deemed undesirable in https://github.com/lxde/lxqt-about/pull/5 and that it doesn't seem to be clear where it should go after all, though.

**Comment by stefonarch** [comment]
Shows up now in submenu lxqt-settings.
