### ISSUE TITLE
Icons missing after each reboot

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/pcmanfm-qt#140]
When I start my Linux distro and open pcmanfm-qt, no items are shown.

![icons-missing](https://cloud.githubusercontent.com/assets/6639859/6204423/e5c0551e-b54a-11e4-80b5-76ff4a707f64.png)

After I go to the preferences, select another theme and press OK. The icons of this theme are shown. Once I do this again for the theme which was initially selected. Most icons show (except the bookmarks).

![icons-returned](https://cloud.githubusercontent.com/assets/6639859/6204427/05989892-b54b-11e4-9500-c94b0099923e.png)

When I reboot the desktop, I am back at square one. :)
This issue started after upgrading today from lxqt 0.8 to 0.9.

Do you have any suggestions how to solve this?

**Comment by ArthurBorsboom** [comment]
Issue hasn't occurred anymore.
I am not sure why it disappeared.

**Comment by pmattern** [comment]
Feel free to reopen if the problem should come up again.

Also, if you should happen to figure out the culprit it would be nice if you dropped a note.
