### ISSUE TITLE
translation updates should be done out of the sources

### ISSUE THREAD

**Issue by agaida** [lxde/pcmanfm-qt#143]
don't know if it's possible to do this in the build dir
<pre>
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building pcmanfm-qt using existing ./pcmanfm-qt_0.9.0.orig.tar.gz
dpkg-source: info: local changes detected, the modified files are:
 pcmanfm-qt-0.9.0/pcmanfm/translations/pcmanfm-qt_ar.ts
 pcmanfm-qt-0.9.0/pcmanfm/translations/pcmanfm-qt_cs_CZ.ts
</pre>

**Comment by luis-pereira** [comment]
@agaida If it worked the same way the lxqt packages, it would be Ok ?

**Comment by luis-pereira** [comment]
@agaida ping

**Comment by agaida** [comment]
@luis-pereira pong - i think yes

**Comment by luis-pereira** [comment]
@agaida Check https://github.com/lxde/pcmanfm-qt/pull/192

**Comment by PCMan** [comment]
This should already be improved by the new translation infrastructure built by luis-pereira.
