### ISSUE TITLE
Don't confirm when moving files to the trash

### ISSUE THREAD

**Issue by goetzc** [lxde/pcmanfm-qt#151]
As a file deleted to the trash can be undeleted, it is not so important to ask confirmation, and it can even be annoying to the user. But a confirmation before deleting a file (bypassing trash) is convenient to have. 

I propose to change in Preferences the behavior of `Confirm before deleting files` so that it only asks confirmation when deleting files bypassing the trash.

**Comment by PCMan** [comment]
it's already implemented.
