### ISSUE TITLE
tree view: hidden objects only displayed in right pane

### ISSUE THREAD

**Issue by pmattern** [lxde/pcmanfm-qt#154]
In Directory Tree view hidden objects are only displayed in the right pane but not within the actual tree in the left one
![pcmanfm hidden objects](https://cloud.githubusercontent.com/assets/9860801/6738271/492d8bdc-ce71-11e4-9cff-8b03bcabe792.png)

FWIW both PCManFM GTK and qtFM do display them in left pane as well.

**Comment by PCMan** [comment]
Fixed.
https://github.com/lxde/pcmanfm-qt/commit/79e2e5e66f0586e78d3625974b61f76da2e96cd8
