### ISSUE TITLE
Uneven icons margin

### ISSUE THREAD

**Issue by goetzc** [lxde/pcmanfm-qt#160]
As seen in the screenshot, the top margin is uneven for some icons.  
PCManFM-qt:
![pcmanfm-qt files margins](https://cloud.githubusercontent.com/assets/2220440/6487952/58da0ce2-c262-11e4-9ec9-fba3f30928e1.png)

Dolphin:
![files margins dolphin](https://cloud.githubusercontent.com/assets/2220440/6488080/fb0559d6-c262-11e4-8add-8458715717e5.png)

**Comment by jleclanche** [comment]
You're comparing two different icons though.

However, this also highlights that pcmanfm-qt does not set application/x-zerosize icons. cc @PCMan

**Comment by goetzc** [comment]
You are right, those are not the same icons, although the behavior is the same:
![files margins dolphin](https://cloud.githubusercontent.com/assets/2220440/6494193/f5d14526-c28d-11e4-8096-fd2ab089bb59.png)

Dolphin uses that empty paper icon when the file is empty, and the other icon for non-empty text files.

**Comment by tsujan** [comment]
Fixed by https://github.com/lxde/libfm-qt/pull/11 and an older commit. Reopen it if you still see it with the latest git versions.
