### ISSUE TITLE
usual build procedure omits translation of desktop entry files

### ISSUE THREAD

**Issue by pmattern** [lxde/pcmanfm-qt#186]
The usual `cmake && make` doesn't consider the translations of pcmanfm-qt[-desktop-pref].desktop in ./pcmanfm/translations/ (source tree).

**Comment by luis-pereira** [comment]
pcmanfm-qt doesn't use the LXQt translation stuff.
@PCMan What's your opinion about using LXQt translation stuff here ? Without depending on liblxqt.

**Comment by PCMan** [comment]
I'm OK with that given it does not add new dependencies. :-)

**Comment by pmattern** [comment]
Just curious:
The actual UI itself does get translated. Which method other than "LXQt stuff" is used to achieve this?
What's so bad about depending on liblxqt? PCManFM-Qt is LXQt's file manager after all.

Thanks.

**Comment by PCMan** [comment]
1. CMake itself can handle Qt translations and I used that.
2. The reason not to use liblxqt is simple. We currently do not need any function from it. Linking to more libraries means longer loading time due to dynamic linking and symbol resolution.

**Comment by luis-pereira** [comment]
@PCMan CMake can't handle .desktop files. I can just copy the CMake modules that handle translations on liblxqt to pcmanfm-qt. lximage-qt, for example, already uses LXQtTranslateDesktop.cmake. But linking to liblxqt isn't necessary to use the translation stuff. It's an compile time dependency. An runtime dependency is only needed if one want's to use the automatic runtime translation loader.
We can use `find_package(lxqt)` and still don't link to it.

**Comment by luis-pereira** [comment]
@pmattern @PCMan Check https://github.com/lxde/pcmanfm-qt/pull/192

**Comment by PCMan** [comment]
I'm ok with that as long as no new "runtime" dependency is required.
Sorry for the late and infrequent replies. Fighting with real life issues now. :-(

**Comment by luis-pereira** [comment]
@PCMan That's life. The changes don't introduce __any__ dependency.

**Comment by pmattern** [comment]
Commits proposed in #192 are working as expected here and solve this issue. Arch Linux i686 and x86_64.

Didn't check any eventual new dependencies but just trusted what @luis-pereira said with regards to this.

**Comment by luis-pereira** [comment]
@pmattern I copied the CMake modules from liblxqt to the pcmanfm-qt tree, so no dependencies, not even build time depedencies.

**Comment by pmattern** [comment]
Unfortunately there seems to be a regression: as of e880e33 translations in left pane as those flagged by arrows in following screenshot
![lxqt_pcmanfm-qt_missing-translation-left-pane](https://cloud.githubusercontent.com/assets/9860801/8552717/33e205cc-24df-11e5-9fb8-529e1eabc953.png)
aren't considered any longer.

**Comment by luis-pereira** [comment]
@pmattern I will take a look.... tomorrow. I'm just to exhausted to look at any code.

**Comment by pmattern** [comment]
@luis-pereira
Take your time! We're not in a hurry with regards to this!

**Comment by luis-pereira** [comment]
@pmattern Fixed in the latest master.
Portuguese screenshot
![screen-2015-07-08-08-01-33](https://cloud.githubusercontent.com/assets/62877/8574080/aa835202-2549-11e5-9fbe-3c46d96db1b5.png)

**Comment by pmattern** [comment]
Confirmed.

Just curious: what icon theme is that?

**Comment by luis-pereira** [comment]
The good looking Numix icon theme. https://github.com/numixproject/numix-icon-theme
