### ISSUE TITLE
Column layout is not always updated

### ISSUE THREAD

**Issue by ufleisch** [lxde/pcmanfm-qt#190]
###### Steps to reproduce

Create a test folder with some contents:
```
mkdir -p "layouttest/a bit longer filename 1"
touch "layouttest/a bit longer filename 1/short" "layouttest/a bit longer filename 2"
```
Now start pcmanfm-qt, set left side pane to "Places", right side pane to "Detailed List".

1. Change to directory "layouttest",
2. then to directory "a bit longer filename 1",
3. then back to parent (Alt-Up).

Everything is displayed correctly.

Now set left side pane to "Directory Tree", and repeat the steps 1-3. The folder name is not displayed correctly, only "a bit l..." instead of "a bit longer filename 1" although there would be enough horizontal space. Actually the "Name" column size has not changed and has still the size suitable for "short".

###### Analysis:

Looking at the debug output there is an additional "folder loaded" message after the "finish-loading" messages in steps 1 and 2 in the case of the "Directory Tree". The messages for step 3 are "start-loading, delete CachedFolderModel, delete FolderModel, finish-loading" in the "Places" case and "start-loading, finish-loading, delete CachedFolderModel, delete FolderModel" in the "Directory Tree" case. Looking at the code, this shows that in the "Directory Tree" case, the folders are also loaded by the `DirTreeModelItem` (hence the "folder loaded" message), this (`fm_folder_is_loaded()`) will cause `TabPage::chdir()` to directly call `onFolderFinishLoading() `(hence the different order of "finish-loading" message).

In the "Places" case, the model is loaded, which invokes `FolderViewTreeView::rowsInserted()`, which calls `queueLayoutColumns()`. In the "Directory Tree" case, the folder is already loaded and the layout is therefore not updated.

**Comment by PCMan** [comment]
Thank you for the detailed bug report.
