### ISSUE TITLE
pcmanfm-qt: `cannot open display` under wayland

### ISSUE THREAD

**Issue by Schweber** [lxde/pcmanfm-qt#1939]
##### Expected Behavior

`pcmanfm-qt` launches without problem in a pure wayland environment.
##### Current Behavior

If i run `pcmanfm-qt` in `hyprland` without `xwayland` or in `niri` i'm getting:

```
$ pcmanfm-qt                                                                                                                                     

(pcmanfm-qt:4471): Gtk-WARNING **: 20:09:24.876: cannot open display:
```
I've set the following environment variables but it doesn't help:
```
environment {
    XDG_CURRENT_DESKTOP "niri"
    XDG_SESSION_DESKTOP "niri"
    XDG_SESSION_TYPE "wayland"
    SDL_VIDEODRIVER "wayland"
    CLUTTER_BACKEND "wayland"
    MOZ_ENABLE_WAYLAND "1"
    NIXOS_OZONE_WL "1"
    _JAVA_AWT_WM_NONREPARENTING "1"
    GDK_BACKEND "wayland"
    QT_QPA_PLATFORM "wayland"
    QT_AUTO_SCREEN_SCALE_FACTOR "1"
    QT_WAYLAND_DISABLE_WINDOWDECORATION "1"
}
```

##### Steps to Reproduce (for bugs)

1. launch `pcmanfm-qt` in a wayland compositor without access to `xwayland`

##### Context

Other users of Nixos have [reported](https://github.com/NixOS/nixpkgs/issues/333964) that it works for them so i don't understand the problem on my system. I ran `strace pcmanfm-qt` with these [results](https://bin.disroot.org/?1176e6523c4f73b5#8CwMrt48Z1VGnCMKDheut29X871YEDuCFLJbD3o7dGc8).
##### System Information

* PcManFm-qt version: 2.0.0
* Distribution & Version: Nixos unstable
* Qt Version: 6.7.2
* liblxqt Version: not part of the package in nixpkgs

**Comment by stefonarch** [comment]
I can launch pcmanfm-qt under any wayland compositor including niri without any issues. Suspected ` QT_QPA_PLATFORM "wayland"` but it opens with that too.

For env vars on Hyprland: https://github.com/stefonarch/LXQt-Wayland-files#hyprland-tiling but IMO the problem is elsewhere in your case.

`(pcmanfm-qt:4471): Gtk-WARNING **: 20:09:24.876: cannot open display:`: this is weird, as GTK isn't involved with pcmanfm-qt.  Maybe an issue in terminal you're using?

**Comment by tsujan** [comment]
Definitely not a problem of pcmanfm-qt.

**Comment by tsujan** [comment]
> Is that to be expected?

I wonder why it didn't crash immediately. Qt6 doesn't have a gtk2 style. If you don't have an LXQt session, try qt6ct for the platform plugin and Fusion/Breeze/Oxygen/Kvantum for the style.

**Comment by tsujan** [comment]
> I'm missing my gtk theme though

Kvantum includes two themes very similar to GTK's default themes, namely, KvGnome and KvGnomeDark.

**Comment by tsujan** [comment]
> As the package is called qt6qtk2, isn't it supposed to work with qt6?

Its name says that it is. But I remember that, with Qt5 too, the gtk2 style (and some others) caused crashes in Qt apps after each Qt upgrade.

**Comment by tsujan** [comment]
> It's working in xwayland though

You mean the gtk2 style engine? If so, its code may be too old.

> Anyway, that's off topic for pcmanfm-qt.

Yes, but there's no harm in talking about other things in a closed report.
