### ISSUE TITLE
Crash when rightclick on item in trash

### ISSUE THREAD

**Issue by fguzm** [lxde/pcmanfm-qt#195]
...but only when 'move deleted files to trash bin' in preferences is untagged.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff649fa77 in QAction::setText(QString const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
```
(Some programs move files to trash, even though trash isn't 'enabled' in pcman)

Debian 64 testing, lxqt from siduction

**Comment by pmattern** [comment]
Confirmed as described above.
PCManFM-Qt from latest Git checkout on Arch Linux as well as from PPA ppa:lubuntu-dev/lubuntu-daily on Lubuntu 15.04, both x86_64, both using Qt 5.4.x. (Also tried to test on Debian stable hence Qt 5.3.x but can't get LXQt running in my KVM/QEMU VM right now.)

> (Some programs move files to trash, even though trash isn't 'enabled' in pcman)

This comes to no surprise. The trash is following a [specificaion](http://www.freedesktop.org/wiki/Specifications/trash-spec/) that's implemented by different desktop environments and tools. You can e. g. handle it by tool `gvfs-trash` as well.
