### ISSUE TITLE
Use lxqt-sudo by default

### ISSUE THREAD

**Issue by pmattern** [lxde/pcmanfm-qt#204]
In order to open a new window as root (Tool - Open as root) PCManFM-Qt is looking for gksu as backend ~~only~~ by default.
This should be replaced with `lxqt-sudo` introduced recently in the long run.

Btw. shouldn't this be 'Tool*s*' in the menu bar?

[Edit: correct that backend can be chosen and hence gksu isn't the only one available but just the default]

**Comment by 8fm** [comment]
You can change it in settings: http://i.imgur.com/fRUQUlCh.png
But this does not working for me. But I still can run "lxqt-sudo pcmanfm-qt" from command line and get it working.

**Comment by q4a** [comment]
You can change it in settings: http://i.imgur.com/fRUQUlCh.png
This does not working for me: nothing happens. May be it's lxqt-sudo bug?
PS I still can run "lxqt-sudo pcmanfm-qt" from command line and get it working.

**Comment by pmattern** [comment]
> You can change it in settings [...]

Of course. I had totally forgotten that setting when filing this issue and modified stuff accordingly.

The apparent malfunction of `lxqt-sudo` is probably due to the fact that PCManFM-Qt isn't assuming `sudo` as backend but `su` and support of the latter is [wip](https://github.com/lxde/lxqt-sudo/pull/7) in `lxqt-sudo`.

(So basically this issue has to be postponed until the problems that came up in the said PR are fixed.)

**Comment by agaida** [comment]
@pmattern - makeing lxqt-sudo default would introduce a dependeny (or at least a recommend) to lxqt-sudo, so pcmanfm-qt should look if lxqt-sudo is present and has a reliable fallback - no clue if this is a really clever move (mind using pcmanfm-qt outside of LXQt). But i would second this.

**Comment by pmattern** [comment]
@agaida 
Are you sure regarding dependencies?
Grepping through the code and running `ldd` strongly suggest that it's not a dependency at all but just a configuration setting, see [here](https://github.com/lxde/pcmanfm-qt/blob/184da38cc965fc93f52d09d1d1f6e3822214a23c/pcmanfm/settings.cpp#L152).
So trading `gksu` with `lxqt-sudo` or [what ever it may be renamed to](https://github.com/lxde/lxqt/issues/794) wouldn't change dependencies at all, would it?

**Comment by agaida** [comment]
not a build dependency or so - but i would consider a program broken if it blindly trust in the presence of another package - so this should be handled gracefully - in that case it isn't a dependency, just  recommended.

**Comment by pmattern** [comment]
Don't know whether there's some kind of common approach to deal with "soft dependencies" like this. But isn't it rather downstream's / packager's job to craft their packages accordingly, something like `optdepends` on Arch Linux or `Recommends` / `Suggests` on Debian and derivatives?

Nevertheless I still think trading `gksu` with something different wouldn't change the situation regarding dependencies at all and that hence the latter is beyond this issue's scope.

**Comment by PCMan** [comment]
Done. The default value is changed to lxqt-sudo now in pcmanfm-qt and the default config file shipped with lxqt-common.
