### ISSUE TITLE
Bookmarks for frequently used network shares

### ISSUE THREAD

**Issue by Atalanttore** [lxde/pcmanfm-qt#207]
Hi,

I miss bookmarks for frequently used network shares very much. I would appreciate such a feature.

Regards,
Ettore

**Comment by pmattern** [comment]
This is working on a VCS checkout made some days ago on Arch Linux here. E. g. here
![pcmanfm-qt_bookmarks-vs-network-shares](https://cloud.githubusercontent.com/assets/9860801/9449708/ab85c20e-4aa4-11e5-92c5-72081a7c1c49.png)
an SFTP share on a host `st-test1` was selected under "Devices" and bookmarked as usual. The corresponding topic under "Bookmarks" could then be used to connect to the share once it was unmounted.

Does PCManFM-Qt behave differently on your system (which you may want to state if it does) or is it even something different you have in mind?

**Comment by Atalanttore** [comment]
They are lost after a system restart.

**Comment by pmattern** [comment]
> They are lost after a system restart.

Not in general. Bookmarks referencing network shares as stated above do not get deleted during reboots on Arch Linux (LXQt from AUR VCS packages), Lubuntu 15.04 (PPA ppa:lubuntu-dev/lubuntu-daily) or Fedora 23 alpha (Rawhide).
So either a downstream issue affecting your platform in general or something wrong with your particular system.
