### ISSUE TITLE
Edit filename inline

### ISSUE THREAD

**Issue by jleclanche** [lxde/pcmanfm-qt#21]

**Comment by tsujan** [comment]
Oh, this very old issue is repeated here: https://github.com/lxde/pcmanfm-qt/issues/468, Apparently the reporter couldn't find this.

Since the inline renaming is implemented at https://github.com/lxde/libfm-qt/pull/67, is it OK to close this issue instead of the new one?

**Comment by tsujan** [comment]
I close this. Moved tot https://github.com/lxde/pcmanfm-qt/issues/468; please discuss it there!
