### ISSUE TITLE
Custom Folder Icons in PCManFM-qt (patch)

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#213]
The following patch is for libfm and makes PCManFM-qt read the file ".directory" inside a folder (if it exists) and set the icon of that folder accordingly, as is the case with Dolphin and Konqueror. It works for me.

https://dl.dropboxusercontent.com/u/7793460/libfm-custom_directory_icon.diff.gz

For now, PCManFM-qt doesn't do anything when the folder icon on the Properties dialog is clicked but the ".directory" file can be created manually or by a simple file-manager action.

**Comment by pmattern** [comment]
Any particular reason why don't submit your suggestions as pull request and deposit the patches on a third-party server instead?

**Comment by tsujan** [comment]
I just didn't know that's the right way.

**Comment by pmattern** [comment]
You may want to have a look at https://github.com/lxde/lxqt/blob/master/CONTRIBUTING.md and the links therein.

**Comment by tsujan** [comment]
Thank you very much!
