### ISSUE TITLE
pcmanfm-qt closes abruptly

### ISSUE THREAD

**Issue by ferronrsmith** [lxde/pcmanfm-qt#217]
There are 2 cases where this happens.

- If I create a bookmark for a folder
- Delete the folder
- Try to navigate to the folder (deleted) using the bookmark. pcmanfm crashes

I using maven alot for work

- If I navigate inside the `targets` folder
- Then perform a mvn clean via the terminal (which removes the targets folder)
- pcmanfm-qt crashes.

Are these expected behavior ? 

Expected behavior

1. If a user tries to navigate via a bookmark to a folder that does not exist, A message saying  "Folder does not exist"
2. If a folder is deleted while a user is currently access it, it should always take them to the parent level and so on 

e.g.

`/home/ferron/lxqt/targets` <-- deleting target should take me back to `/home/ferron/lxqt`

linked to lxde/lxqt#801

**Comment by pmattern** [comment]
Running LXQt from VCS checkouts on Arch Linux x86_64 I'm just getting an ordinary message telling me the folder in question is no longer available when trying to reproduce your findings regarding bookmarks.

As for the second finding, namely an apparent crash if the folder that's actually displayed gets deleted by another application, I remember very well I had seem something similar not too long ago as well but cannot reproduce any more either right now. Issue #70 addressing the same problem got closed long ago.

Could you please provide information regarding OS, version of LXQt and way it was installed

**Comment by ferronrsmith** [comment]
Currentl version of pcmanfm-qt - 0.9.0+bzr355+201509012231~ubuntu14.04.1

**Comment by PCMan** [comment]
I'm not able to reproduce the crash here.
