### ISSUE TITLE
"open terminal" work directory is home directory

### ISSUE THREAD

**Issue by nyim** [lxde/pcmanfm-qt#231]
1 open fm, navigate to /tmp, / or something else.
2 press F4 / or Tool => open terminal
3 in my terminal, konsole, the current directory is home (~)

version 0.9
kde plasma 5.4.1, konsole-15.08.0

btw: pcmanfm works perfectly,  and the strange things are:
after I install pcmanfm and open terminal in it
then pcmanfm-qt, works.

after I uninstall pcmanfm, then pcmanfm-qt fail to work again

**Comment by andrei-korshikov** [comment]
Eight years later... Revision [49a73d2](https://github.com/lxqt/pcmanfm-qt/commit/49a73d26f4b507757eee4ac4b1c45ff56323f308) (yes, it is the most current commit in Qt6 branch, but that's not matter - I've tried 1.4.0 for Qt5 too), almost the same behavior with `konsole`.

Work as expected only one time, and if there is no `konsole` previously started:
1. No console is opened.
2. Press F4.
3. Console is opened, the current directory is correct.
4. Change folder in PCManFM, try to "open terminal" again.
5. New console is opened, the current directory as in (3). Seems like something caches it somewhere, and then uses this cached value while at least one console window is opened.
6. Repeat any times, result is the same, still the same (first) directory...
7. Now close all console windows.
8. Aha! Now the very first newly created console is opened with right directory.
9. All the next windows open with the same directory from (8).
10. Close all consoles. Start `konsole` from desktop environment, go to somewhere.
11. Try to open terminal in PCManFM.
12. And now the same behavior as 8 years before: console is opened in `$HOME` directory.

Side note. Also konsole doesn't respect `--new-tab` parameter when I place it in `terminals.list` file. So, new console is always opened as a new window, not as a new tab. Well, manually attach window to existed one is not a big problem, but incorrect directory (always home in case of pre-opened consoles) is.

**Comment by tsujan** [comment]
> Also konsole doesn't respect....

Konsole doesn't have anything to do with LXQt or pcmanfm-qt. Only if it has had a backward incompatible change in its command-line options, they should be updated in the terminals list; whether they work as expected or not is a KDE question.

In case there are changes in Konsole's command-line options, we need to wait for its Qt6 version.

**Comment by andrei-korshikov** [comment]
I think "respect" was a wrong word, I'm sorry. I mean that putting `open_arg=--new-tab -e` in `[konsole]` section of `/usr/share/libfm-qt/terminals.list` (or its user's counterpart `${HOME}/.local/share/libfm-qt/terminals.list`) does nothing. Despite this konsole opens a new window, and because of that I think that konsole doesn't really get `open_arg` parameters from terminals list.

**Comment by tsujan** [comment]
I'm under LabWC (Wayland) and `--new-tab` doesn't work as advertised, even though I've checked "Run all Konsole windows in a single process": always a separate process is started and a new window is opened. So, it should be a problem in Konsole.

If this has happened for 8 years, KDE devs have had no motivation to fix it — perhaps they're satisfied with Konsole working with Dolphin.
