### ISSUE TITLE
Open directory in external program

### ISSUE THREAD

**Issue by hotvic** [lxde/pcmanfm-qt#238]
The Pcmanfm has a submenu in the right click menu that lets me open the directory in a external program, easytag for example.

In Pcmanfm-qt this isn't possible AFAIK.

Would be great have this feature in -qt too.

**Comment by pmattern** [comment]
Seems rather like an inconsistency in terms of context menus of different views and panes respectively:
Feature is available in context menu of "Directory Tree" view's left pane

![pcmanfm-qt_open-directory-in-external-application](https://cloud.githubusercontent.com/assets/9860801/10209310/59b5429e-67da-11e5-84f4-2f67bc220d5b.png)

but lacks both in the context menus of left pane in "Places" view and in right pane altogether.

You may want to use this as a workaround for the time being.

**Comment by hotvic** [comment]
I get no context menu in left panel at all.

**Comment by pmattern** [comment]
So mind posting some information about OS you're running, the way LXQt was installed and version of PCManFM-Qt?
Probably you're still running release 0.9 which doesn't feature some changes in PCManFM-Qt's context menus yet that took place [some months ago](https://github.com/lxde/pcmanfm-qt/issues/163).

**Comment by hotvic** [comment]
Arch, installed from official repositories.

Yes it was the 0.9, now build from git and menu is there.

**Comment by hotvic** [comment]
Any news on the main panel context ?

**Comment by pmattern** [comment]
If I'm not mistaken this issue boiled down to the feature missing *in right pane* which is addressed in #273 now.
Hence closing. Feel free to add another comment if you feel the need to.
