### ISSUE TITLE
PCManFM-Qt crashes when opening certain directories

### ISSUE THREAD

**Issue by whitebyte** [lxde/pcmanfm-qt#241]
Hi,
i have a directory generated with Doxygen for relatively large project. When I try to open it in PCManFM-Qt it silently closes after a second or two. When launched from terminal it doesn't generate any errors on close. Example directory can be downloaded here: http://rghost.ru/77wpf8Xq2
PCmanFM 0.9.0, openSUSE Tumbleweed

**Comment by PCMan** [comment]
@whitebyte The file you example.tar.bz2 you provided is already deleted.
Would you please upload it again? Thank you.

**Comment by whitebyte** [comment]
@PCMan https://yadi.sk/d/uhOxFdbpk96rr

**Comment by PCMan** [comment]
Fixed in https://github.com/lxde/pcmanfm-qt/commit/17971f3d95dcecb4259a3da2b24a210eae37d301 .
Thanks!
