### ISSUE TITLE
remove margin in file browser

### ISSUE THREAD

**Issue by antis81** [lxde/pcmanfm-qt#242]
Since file search got implemented (finally :+1: :smile:) the file browser is shown with an ugly margin. Could you please remove that?

Screenshot from Lubuntu 15.04 (I'm a lazy upgrader…):
![PCManFM-Qt with ugly margin](https://cloud.githubusercontent.com/assets/440517/10712743/eb1a9df8-7aa2-11e5-94b8-062e332da5ce.png)

**Comment by paulolieuthier** [comment]
Test it please.

**Comment by antis81** [comment]
Sorry, I had to re-setup my whole machine after failed upgrade to Lubuntu 15.10 -> currently back on Lubuntu 14.04.

Hm… this issue is still there, at least in `lubuntu-daily` PPA nothing changed yet.

**Comment by paulolieuthier** [comment]
The packager will take some time to upgrade, but the issue is fixed. If you want, you can build pcmanfm-qt from source.

**Comment by palinek** [comment]
@paulolieuthier why didn't you remove gap in the middle?
- before filter patch:

![screenshot](https://cloud.githubusercontent.com/assets/10990929/10840315/616a2d54-7ede-11e5-99d8-f705f6721ccc.png)
- after your patch

![screenshot](https://cloud.githubusercontent.com/assets/10990929/10840359/d1666fc8-7ede-11e5-9c35-de5586119bf5.png)

**Comment by antis81** [comment]
@palinek This is separate issue (space has been there for long time now). Anyway, I also wish for a narrow splitter with 1px width. Maybe open new issue?

**Comment by paulolieuthier** [comment]
@palinek the separator is larger in your screenshot than it is here. It just feels better to me, but feel free to make it thiner.

**Comment by palinek** [comment]
I don't use pcmanfm so don't care if there is a gap or not. I was just pointing the change before/after.

**Comment by pmattern** [comment]
Seeing that gap exactly as in palinek's screenshot here (Arch Linux i686 or x86_64 with all LXQt components from latest VCS checkouts), too, and have to agree it looks rather ugly.
So if feasible I'd also vote for reverting it to the status as shown in screenshot "before filter patch".

**Comment by paulolieuthier** [comment]
Done.
