### ISSUE TITLE
Double selection of files

### ISSUE THREAD

**Issue by baghira** [lxde/pcmanfm-qt#251]
Upon clicking on some files, pcmanfm-qt also selects either the file immediately above or below. I suspect the issue appears only with file with longish names (i.e. 50-60 characters).
Moreover the issue disappears once I resize the window (until, that is, the next time I open the folder).
![Sample screenshot](https://cloud.githubusercontent.com/assets/15658924/10950691/4cf99ef4-8339-11e5-93f6-5a6eddcf82e0.png)

**Comment by tsujan** [comment]
I confirm that -- saw it only recently.

**Comment by pmattern** [comment]
Probably related to lxde/lxqt#768?

**Comment by tsujan** [comment]
Fixed by  #252.
