### ISSUE TITLE
inconsistencies in context menus

### ISSUE THREAD

**Issue by pmattern** [lxde/pcmanfm-qt#273]
There are several inconsistencies / problems in the various context menus the solution of which would improve the UX.

If left pane is set to Directory Tree view context menus of directories comprise an item `Open with ...` that's missing in right pane.
Opening directories in a distinct application may be much less common than with files but use cases where it makes sense exist, see e. g. #238.
So directories' context menus in right pane should get complemented with the said item, too.

If `Open` gets clicked in a context menu of a directory in right pane all the content of the directory gets displayed in right pane. Plus, if left pane is set to Directory Tree view the corresponding subfolders get displayed there, too (tree view gets expanded automatically). Clicking `Open` in a directory's context menu in left pane in Directory Tree view doesn't seem to trigger any action, though.
So button `Open` in left pane in Directory Tree view should trigger the same actions as in right pane.

Files' context menus in right pane are comprising items `Create New {Folder,Blank File}` and `Paste` which cannot be applied to a file. In fact they get applied to the directory comprising the file which is non-intuitive and confusing. All these items are provided by the context menus of directories and blank space in right pane as well where they do make sense and work as expected.
So I suggest to remove `Create New` and `Paste` from files' context menus.

Directory context menus in left pane in Places view are comprising topics `Open in New {Tab,Window}` only.
I'm not sure about the motivation to do so, maybe it was done with intent. On the other hand other items in Places view are featuring additional topics, too, e. g. those summarized under "Devices" state actions `Unmount` and `Eject`.
So I wonder whether the it wouldn't improve the UX if the context menus of directories in left pane's Places view got complemented with additional actions like those discussed above.

**Comment by hotvic** [comment]
> Clicking Open in a directory's context menu in left pane in Directory Tree view doesn't seem to trigger any action, though.

Works here, just like the right panel.

**Comment by pmattern** [comment]
>> Clicking Open in a directory's context menu in left pane in Directory Tree view doesn't seem to trigger any action, though.

>Works here, just like the right panel.

Weird. Still seeing this here, latest VCS checkouts of all LXQt components on Arch Linux x86_64. Choosing `Open` from the context menu of a directory in Directory Tree view in left pane just doesn't seem to have any effect. Btw. double clicking the same directory behaves like `Open` in the context menus in right pane. The tree of subfolders get expanded which is what I'd consider expected behaviour.

**Comment by hotvic** [comment]
The 'Open' behavior of left panel here is: Loads the directory contents in the right panel, but not expand the tree.
The double click behavior: Loads the directory contents in the right panel and expand the tree.

I don't know if this is a issue or the pcmanfm-way to handle 'Open' action.

**Comment by pmattern** [comment]
> The 'Open' behavior of left panel here is: Loads the directory contents in the right panel, but not expand the tree.
The double click behavior: Loads the directory contents in the right panel and expand the tree.

That's exactly the behaviour I'm seeing, too.
But on the one hand this does mean that the very same item `Open` behaves differently in left pane in Directory Tree view and in right pane. Also, I guess in file managers the most common behaviour is to first select an item and then open its context menu by right clicking. But selecting a directory in left pane makes its content already visible in right pane. So choosing `Open` from the context menu has no effect at all in that case.
All in all I still doubt the current behaviour makes for a good UX.

**Comment by pmattern** [comment]
Still item `Open` in Directory Tree view doesn't have any effect most of the time and the context menus of directories in Places view are pretty sparse, see last two paragraphs of initial comment.
Do you think these topics aren't worthwhile (if so a little explanatory note would be nice, IMO)? Any other reason for closing?
