### ISSUE TITLE
(Folder) custom actions are missing in FolderMenu.

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#297]
As the title says. Right clicking inside a folder but outside any file/folder should show custom actions for directories.

The fix I have is simple but requires duplication of some code blocks. I'll PR it if I don't find another way.

**Comment by PCMan** [comment]
Thanks! Waiting for your fix. :)

**Comment by pmattern** [comment]
@tsujan 
Just curious: Could you eventually elaborate a little bit what the actual problem addressed in this issue looks like?
Running lxde/libfm-qt@0691823 I couldn't see any malfunction so far and `inside a folder but outside any file/folder` wasn't clear to me, either.

**Comment by tsujan** [comment]
> wasn't clear to me, *either*.

It seemed to me that PCMan got what I meant.
If you had custom actions for folders, they wouldn't show up when you right clicked on an empty area inside a folder.

**Comment by tsujan** [comment]
@pmattern 
More explicitly: First create a folder custom action. Then restart PCManFM and right click on an empty area of desktop. Do you see any folder custom action?

**Comment by pmattern** [comment]
Got it.
I thought "custom" was referring to the individual context menus of different objects like files and directories and wasn't aware of those "custom action" stuff which I haven't used so far.
Thanks for answering.

**Comment by PCMan** [comment]
Merged.

**Comment by excalibur1234** [comment]
if somebody find this thread in the future and wonders what custom actions in pcmanfm-qt are, please look here for examples: 
https://wiki.manjaro.org/index.php?title=Custom_Actions_for_PCmanFM-Qt
