### ISSUE TITLE
pcmanfm-qt require gksu

### ISSUE THREAD

**Issue by MttCastelli** [lxde/pcmanfm-qt#302]
Hi,
I'm trying to use an as-pure-as-I-can LXQt desktop and so I removed gksu. If I try 'Tools>Open as root' return this error:

Failed to execute child process "gksu" (No such file or directory)

Shouldn't it uses lxqt-sudo instead?

regards.

**Comment by pmattern** [comment]
Usage of `lxqt-sudo` was introduced in cdb4718. So updating to a recent checkout should actually solve this issue.
Don't know whether remnants of former configuration can eventually be in the way, so you may eventually have to remove `~/.confgic/pcmanfm-qt` or so.

**Comment by MttCastelli** [comment]
my packages from here https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily,
Ubuntu xenial. I removed ~/.config/pcmanfm-qt but the error remain, see the next reboot. Thanks for your answer.

I'm now realizing that lubuntu-dev PPA builders had some problems compiling pcmanfm-qt...

**Comment by palinek** [comment]
...and it's configurable in Edit -> Preferences -> Advanced -> Switch user command

**Comment by MttCastelli** [comment]
"lxqt-sudo %s" instead of "gksu %s" works.

Thank you all, @palinek and @pmattern!
