### ISSUE TITLE
Address bar: append "/" after a folder when auto-completing

### ISSUE THREAD

**Issue by goetzc** [lxde/pcmanfm-qt#310]
This behavior is used by Dolphin and I think it is interesting and quiet useful.
In the address bad, when typing a folder name, and using the arrow to select one from the drop-down list, it would be useful if pcmanfm-qt could append a "/" after the folder name, so that writing the next folder name can be made easier.

**Comment by pmattern** [comment]
Already addressed in #201, see https://github.com/lxde/pcmanfm-qt/issues/201#issuecomment-174218958.
