### ISSUE TITLE
Add filter bar shortcut

### ISSUE THREAD

**Issue by samuelgarcia** [lxde/pcmanfm-qt#311]
Thank you for that tools and lxQt.

This file browser could be wonderfull with a filter bar like in dolphin accessible with Ctr+I.

**Comment by palinek** [comment]
What version of pcmanfm-qt are you talking about?

Filter bar was implemented in 5fd3eb96aba40130bcad50f092fb6d6717402bc2, see below
![screenshot](https://cloud.githubusercontent.com/assets/10990929/13009894/3262fca2-d19f-11e5-9441-aebf769b9033.png)

**Comment by samuelgarcia** [comment]
oups.
Infinite sorry for disturbing.
So the query is just : could it be possible to add Ctr+I shortcut ?

Thank a lot for LxQt gain. It is wonderfull.

**Comment by tsujan** [comment]
Ctrl+F seems better.

**Comment by samuelgarcia** [comment]
You choose.
Note that on dolphin when Ctrl+I : this show the filter bar AND set the focus in it
very very convinient.
Thanks a lot.
BTW what is your icon theme ?

**Comment by tsujan** [comment]
> ... show the filter bar AND set the focus in it

Yes, it should be focused too. "F" for "Filter", "I" for what?

> BTW what is your icon theme ?

@palinek could answer that ;)

**Comment by samuelgarcia** [comment]
In dolphin, I guess,  F is for Find : this open the search bar wich is something more complicated.

**Comment by palinek** [comment]
> BTW what is your icon theme ?
Numix Circle

**Comment by npmiller** [comment]
I think it might make more sense to keep Ctrl + F for the full blown search file dialog currently accessible with F3.

In addition to a classic shortcut (such as Ctrl + I), it would be nice to also have "/" focus the filter bar.

**Comment by tsujan** [comment]
Usually F11 is used for (un-)full-screening, so Ctrl + F would have no problem.
Ctrl + F should also focus the filterbar and return the focus to the folder-view when hiding it, IMO.

**Comment by tsujan** [comment]
> it would be nice to also have "/" focus the filter bar

That's not possible because one may want to write "/" inside the location-bar. After "Ctrl + F" is implemented, you could use it twice to give the focus to the filterbar. Or tab can be used for that purpose.

**Comment by npmiller** [comment]
I tried adding a "/" shortcut on the mainwindow that focuses the filter bar and it works fine, you can still type an actual "/" in the filter bar and in the url bar. You can try it here: 
https://github.com/npmiller/pcmanfm-qt/commit/5d91abab12ae51c1a43b75a5d0a5db713027e17f.

And for Ctrl+F I was thinking about showing this dialog instead:
![spectacle tf2227](https://cloud.githubusercontent.com/assets/5684593/13035200/ffe23424-d341-11e5-9d39-cedc7bddd251.png)

I think Ctrl+F should be for searching, not filtering. The current shortcut for this dialog is F3.

**Comment by pmattern** [comment]
> I think Ctrl+F should be for searching, not filtering. 

Definitely agree here. Virtually all applications featuring a more sophisticated search tool have it launched by this shortcut.
So I think we should really be consistent with all those other applications as well as Dolphin and use `Ctrl+F` (or maybe `F3` as used right now) → advanced search tool, `Ctrl+I` → filtering.

**Comment by tsujan** [comment]
@pmattern 
If F3 is kept for the search utility, there will be no reason for using Ctrl+I. IMO, F3 is good alongside F4 for the terminal. The search utility and terminal are temporary windows and it's good to call them quickly by pressing only one key. On the other hand, the filterbar can be left visible.

I welcome importing of good features from Dolphin, Nemo or Nautilus (some of my PR's have been in this direction) but I see no reason to imitate them to such details.

**Comment by pmattern** [comment]
> If F3 is kept for the search utility, there will be no reason for using Ctrl+I.

This issue boiled down to adding a shortcut to en-/disable the filter bar. Assigning `Ctrl+I` seems like a reasonable choice as e. g. Dolphin is using it, too. Shortcut `Ctrl+F` should not be used for the filter bar as it's used for the more complex search tools normally.
All this is basically independent of the preexisting shortcut to open the search tool of PCManFM-Qt. Eventually changing this shortcut as well just happened to get discussed in addition while at it.
That said I cannot understand your conclusion stated above.

**Comment by tsujan** [comment]
> That said I cannot understand your conclusion stated above.

There was no conclusion to understand!

All in all, I don't think this difference in opinions is practically so grave that justifies much discussion. As you said, it boiled down to adding of a shortcut to en-/disable the filter bar. I'll wait until the others decide between Ctrl+F and Ctrl+I. Or perhaps someone else will do it before me.

**Comment by palinek** [comment]
My opinion:
- add Ctrl+F for showing Find/Search dialog (of course the F3 shortcut will remain)
- add Ctrl+I for setting focus to Filter bar

**Comment by pmattern** [comment]
Hm, while I basically absolutely agree with palinek's last comment this made me notice that there are actually two actions involved: bringing up / hiding the filter bar as a whole, so the action handled by menu View - Filter, and bringing the focus into the filter bar.
This in turn made me wonder whether we should eventually introduce shortcuts for both of them. On the other hand the former is already accessible via mnemonics (`Alt+V` - F) so it could indeed be sufficient to just add a shortcut which brings the focus to the filter bar and maybe opens the filter bar if it shouldn't be already visible when that shortcut gets git.

@tsujan 
Well, if your statement I cited isn't a conclusion than I really don't know. Sometimes I'm under the impression you tend to feel offended when there's in fact no reason to.

**Comment by tsujan** [comment]
> there are actually two actions involved

One shortcut is enough. I already implemented it with Ctrl+I and will make a PR.

> Sometimes I'm under the impression you tend to feel offended

I hardly feel so in everyday life, let alone in a computer discussion :) Thanks for your consideration though! Maybe my statements are sometimes too logical but my intention is more efficiency without emotional interference. Sometimes I may even enjoy being contradicted to see what comes out -- but not too much ;)

**Comment by npmiller** [comment]
> bringing up / hiding the filter bar as a whole, so the action handled by menu View - Filter, and bringing the focus into the filter bar.

What about two modes for the filter bar, always visible and auto-hide. In always visible, the shortcut focuses in the filter bar, and in auto-hide it shows the filter bar and focuses in, the filter bar would then automatically hide if it's empty and looses focus.

I think that would provide the best user experience, and I don't think we would need a shortcut for switching between the two modes of the filter bar.

Also the issue of focusing out of the filter bar is kinda solved by the pull request: https://github.com/lxde/pcmanfm-qt/pull/313

**Comment by tsujan** [comment]
> What about two modes for the filter bar, always visible and auto-hide

IMO, auto-hide would feel jumpy. Two shortcuts for two different tasks don't do any harm.

In #314, I supposed #313 would be merged; otherwise I'd add something like it.

**Comment by tsujan** [comment]
Fixed by https://github.com/lxde/pcmanfm-qt/pull/314.
