### ISSUE TITLE
bug: F2 (rename) option not available when menu bar is hidden

### ISSUE THREAD

**Issue by excalibur1234** [lxde/pcmanfm-qt#317]
i have just built the latest pcmanfm-qt-git and found a bug:
after i have hidden the menu bar (with CTRL+M), i cannot rename files anymore by pressing F2.  but i can rename it, when i right click --> rename.
CTRL+B does not work anymore, too.
F3 does not work, too.

it seems that all keyboard shortcuts stop working with a hidden menu bar.
this behavior is clearly a bug.

btw, thanks for this great feature! its just a little buggy at the moment...

**Comment by tsujan** [comment]
Yes, I wanted to say the same thing at https://github.com/lxde/pcmanfm-qt/pull/308 but it was merged.

@npmiller would you please fix this? Or I could fix it if you want.

**Comment by npmiller** [comment]
Oh I didn't realize that, that's annoying, the `QAction` don't work if their parent widget is hidden, that's annoying. If you have a quick way to fix it @tsujan go ahead, otherwise I can look into it.

**Comment by tsujan** [comment]
@npmiller don't worry! It's fixable. I'll do it as soon as I have time.

**Comment by npmiller** [comment]
Oh I know it's fixable, I'm just not sure what's the best way to fix it right now.

**Comment by tsujan** [comment]
I was thinking of something as simple as this:
````
WIDGET->addActions(MENU->actions());
````
Here, WIDGET can be the main window and MENU is each of the menus. I don't have time to test this idea right now but if you do, please test it!

**Comment by npmiller** [comment]
Ah, yes, that works, I'll prepare a pull request, thanks!
