### ISSUE TITLE
Issue with thumbnail and icon views

### ISSUE THREAD

**Issue by AcarBurak** [lxde/pcmanfm-qt#325]
This is on an Arch Fluxbox system (not LXQt) with pcmanfm-qt 0.10 and the system qt theme being managed by qt5ct.

I've got a directory containing 1000 light jpg images (thumbnails of my CD covers) and when I launch pcmanfm-qt some items are placed too close to or rather attached to the next item both vertically and horizontally. When clicking on one of them chooses not only the clicked one but those neighbours as well.

You can see this in the attachment, the second and third items horizantally on the first raw and the second, third and fourth items vertically on the sixth column.

Just opening preferences and clicking OK solves the issue temporarily, but going to a different bookmark and coming back again brings the issue back as well.

Launching from the terminal produces this:

      Corrupt JPEG data: 324 extraneous bytes before marker 0x2d
      Unsupported marker type 0x2d

![pcmanthumbs](https://cloud.githubusercontent.com/assets/1426842/13634332/8f70bbb0-e5fd-11e5-9d6e-c9ea1d8c1ea7.png)

**Comment by tsujan** [comment]
This was an old bug fixed months ago. Please update your pcmanfm-qt installation or compile it from the git source! Then, if you still see the same problem, reopen this issue.

**Comment by AcarBurak** [comment]
All right, sorry for bother; thank you.
