### ISSUE TITLE
Closing property window for folders before indexing finishes causes segfault

### ISSUE THREAD

**Issue by nonamethanks** [lxde/pcmanfm-qt#328]
As said in the title. 

Steps to reproduce:
1) Right click on and open the property window of a folder containing a large number of files (enough for the program to take more than a single instant to show the total size of it)
2) Before the program finishes indexing, close the property window
3) Once the program finishes indexing (which it'll keep doing even if the property window is closed), it'll crash and return: 
`
zsh: segmentation fault (core dumped)  pcmanfm-qt`

As I said, the folder must be big enough that the program takes several seconds to index its entire content. I've found that a very easy way to reproduce this bug is to pick a folder in an external HDD, since indexing is much slower.

gdb:
```
Starting program: /usr/bin/pcmanfm-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffeaf21700 (LWP 10874)]
[New Thread 0x7fffe1a56700 (LWP 10875)]
[New Thread 0x7fffe1255700 (LWP 10876)]

** (pcmanfm-qt:10870): WARNING **: XDG_TEMPLATES_DIR is set to invalid path, ignoring it
isPrimaryInstance
[New Thread 0x7fffdbbec700 (LWP 10878)]
[New Thread 0x7fffdb3eb700 (LWP 10879)]
[New Thread 0x7fffd9b94700 (LWP 10880)]
[Thread 0x7fffd9b94700 (LWP 10880) exited]
[Thread 0x7fffdb3eb700 (LWP 10879) exited]
[Thread 0x7fffdbbec700 (LWP 10878) exited]
[New Thread 0x7fffdbbec700 (LWP 10908)]
[New Thread 0x7fffdb3eb700 (LWP 10909)]
delete FolderModel
[New Thread 0x7fffd9b94700 (LWP 10910)]
[Thread 0x7fffd9b94700 (LWP 10910) exited]
[Thread 0x7fffdb3eb700 (LWP 10909) exited]

Thread 1 "pcmanfm-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff5e83208 in operator==(QString const&, QString const&) () from /usr/lib/libQt5Core.so.5

```

Core dump from ` journalctl`: http://pastebin.com/ckCAfeTb

I'm using [this version](https://www.archlinux.org/packages/community/i686/pcmanfm-qt/).

**Comment by npmiller** [comment]
Can reproduce on the git version, the indexing job should be aborted when the window is closed.

**Comment by tsujan** [comment]
After several months, yesterday I encountered a crash I couldn't explain but now, I think it was about this issue. I'll look into it.

**Comment by npmiller** [comment]
@tsujan I've actually just fixed it, it was just about cancelling the job in the destructor

**Comment by tsujan** [comment]
> I've actually just fixed it

Great!

The indexing issue you mentioned, made me think that https://github.com/lxde/pcmanfm-qt/issues/326 might have a similar cause. The fact that some can reproduce it and some can't may be related to cache formation. Hence searching for a deeper cause.

**Comment by tsujan** [comment]
@nonamethanks Could you please test if https://github.com/lxde/libfm-qt/pull/20 fixed this issue?

**Comment by nonamethanks** [comment]
@tsujan  Still crashes. gdb now returns a different error however:
```
Thread 1 "pcmanfm-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff75f78b4 in g_type_check_instance_cast () from /usr/lib/libgobject-2.0.so.0

```

**Comment by Ilya87** [comment]
@nonamethanks Compile please pcmanfm-qt with debugging symbols and run backtrace command after segfault error appears in gdb.

**Comment by nonamethanks** [comment]
I'm not familiar with cmake, do I have to append the flag "-DCMAKE_BUILD_TYPE=Debug" ?

**Comment by Ilya87** [comment]
```
delete FolderModel
[Thread 0x7fffc4ff9700 (LWP 17838) exited]

Thread 1 "pcmanfm-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff60878b4 in g_type_check_instance_cast () from /usr/lib/libgobject-2.0.so.0
(gdb) backtrace
#0  0x00007ffff60878b4 in g_type_check_instance_cast () from /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff7b88d55 in Fm::FilePropsDialog::onFileSizeTimerTimeout() () from /usr/lib/libfm-qt.so.3
#2  0x00007ffff7b891cf in Fm::FilePropsDialog::onDeepCountJobFinished(_FmDeepCountJob*, Fm::FilePropsDialog*) ()
   from /usr/lib/libfm-qt.so.3
#3  0x00007ffff6063174 in ?? () from /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff607d976 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff607e05f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff665217a in ?? () from /usr/lib/libfm.so.4
#7  0x00007ffff5d8ec3a in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#8  0x00007ffff5d8efe0 in ?? () from /usr/lib/libglib-2.0.so.0
#9  0x00007ffff5d8f08c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#10 0x00007ffff6b4233f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#11 0x00007ffff6ae937a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff6af133c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#13 0x00005555555759bc in PCManFM::Application::exec (this=0x7fffffffe4a0)
    at /home/ilya/build/lxqt/lxqt/pcmanfm-qt-git/src/pcmanfm-qt/pcmanfm/application.cpp:319
#14 0x000055555557da51 in main (argc=1, argv=0x7fffffffe768)
    at /home/ilya/build/lxqt/lxqt/pcmanfm-qt-git/src/pcmanfm-qt/pcmanfm/pcmanfm.cpp:12
```

**Comment by tsujan** [comment]
@Ilya87
Could you please test with https://github.com/lxde/libfm-qt/pull/20#issuecomment-198908970 ? Or you could wait until @npmiller changes the commit.
