### ISSUE TITLE
libfm-qt dependency contradiction

### ISSUE THREAD

**Issue by HymiR** [lxde/pcmanfm-qt#331]
In CMakeLists.txt:
`find_package(fm-qt REQUIRED)`

seems contradictive to the statement in README.md:
`Includes libfm-qt, the Qt port of the libfm - a library providing components to build desktop file managers.`

Seems one of the two is not up-to date, because without satisfying the latter
dependency, build fails as expected...

What's going on here?

**Comment by npmiller** [comment]
Good catch, thanks!

Libfm-qt was extracted into its own repository fairly recently, it was previously included in this one, I guess the README wasn't updated to reflect that.

**Comment by HymiR** [comment]
Ah, thx for the fast reply, shall I close this issue now?

**Comment by npmiller** [comment]
No, leave it open, we'll close it when the README is updated

**Comment by pmattern** [comment]
While I agree it's the README which isn't accurate here I think the real missing point is that libfm-qt itself still depends on libfm right now, see `ldd <Path to libfm-qt.so.3.0.0>`, isn't it?

Personally I wonder whether it wouldn't make sense to include the missing pieces of libfm into libfm-qt so as to have a single component only but that's a different story, of course.

**Comment by tsujan** [comment]
> Personally I wonder whether it wouldn't make sense to include the missing pieces of libfm into libfm-qt...

libfm is the only component directly based on GLib, so it should be kept separate. I seriously doubt that we could reach the ideal of a unified libfm independent from GLib but ideals are worth considering.

**Comment by luis-pereira** [comment]
I worked on the split. This is just something left behind.
