### ISSUE TITLE
no search results with CTRL+Shift+F

### ISSUE THREAD

**Issue by wmra** [lxde/pcmanfm-qt#338]
I don't get any search results.
files are there - I find them with shell search

Lubuntu with PCManFM 1.2.3

**Comment by pmattern** [comment]
This tracker is dealing with PCManFM-*Qt*, the counterpart of LXDE's PCManFM written in Qt and belonging to [LXQt](http://lxqt.org).
Regarding it's GTK counterpart you may want to have a look at https://sourceforge.net/projects/pcmanfm.
