### ISSUE TITLE
Per-Folder Item Sorting

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#342]
Currently, the item sorting is global in the main window of PCManFM, i.e. if the sorting is changed for one folder, it'll apply to other folders too (the desktop, _as a place that includes panel and wallpaper_ but not as a folder, is an exception). Although such an arrangement may seem good to some users (including me), others may prefer a "per-folder" sorting (https://github.com/lxde/pcmanfm-qt/pull/341#issuecomment-211224392).

Here we could discuss how that should be done and what's best for UX.

**Comment by tsujan** [comment]
My preliminary idea of a per-folder sorting:

(1) A check box is added to the end of the Sorting sub-menu (of the folder's context menu) after a separator with the text, "Preserve sorting for this folder";

(2) Once the box is checked, the sorting will be saved for that folder, such that it won't be changed if the the global sorting is changed (in the context menu of another folder);

(3) If the box is already checked, any change in the sorting will be saved *only* for that specific folder and not globally; and

(4) If the box isn't checked, any change in the sorting will be global, as before.

Can the user easily discern this functionality just by seeing the check box?

**Comment by palinek** [comment]
> Can the user easily discern this functionality just by seeing the check box?

Sounds reasonably. But it realy depends on the actual presentation... can you paste some (may be a fake) screenshot? (one picture could be better than 100 words)

**Comment by tsujan** [comment]
@palinek Thanks! A screenshot:

![2016-04-19-15 45 40-scrot](https://cloud.githubusercontent.com/assets/981076/14637389/308ddfce-0646-11e6-8823-2af0aaa0f9cd.png)

**Comment by palinek** [comment]
>  A screenshot:

Seems intuitive for me. Just one note: the view mode (icon, thumbnail...) will not be configurable per folder?

**Comment by tsujan** [comment]
> Just one note: the view mode (icon, thumbnail...) will not be configurable per folder?

Good point! Then the four view menu-items could be put into a separate sub-menu with a similar check box ("Preserve view for this folder").

On the coding level, I'm thinking about a separate and single settings file containing the required info on such folders, but I haven't decided on its structure (grouping) yet. @palinek What do you think?

**Comment by tsujan** [comment]
This setting structure came to me:
````
[FOLDER_NAME]
Path=(a string list, because multiple folders can have the same name)
Mode=(view mode)
SortColumn=
SortFolderFirst=
SortOrder=
````
(1) When the sorting or view mode is preserved, the group is created or, if it already exists, the folder path is added to it.
(2) When only the sorting is preserved, the Mode key has an empty value.
(3) When only the view mode is preserved, the sorting keys have empty values.
(4) When nothing is preserved, the folder path is removed from the Path key or the whole group is removed if the Path key has no other string in it.

This enables the user, for example, to give the thumbnail view to his/her wallpaper folder while leaving its sorting as that of other folders, or sort a folder in a special way while leaving its view mode like that of others.

I think I'll go with something like it.

**Comment by palinek** [comment]
> I'm thinking about a separate and single settings file containing the required info on such folders,

Aren't you going to use the [@PCMan's suggestion](https://github.com/lxde/libfm/blob/master/src/base/fm-folder-config.h)?

**Comment by tsujan** [comment]
> Aren't you going to use the @PCMan's suggestion?

First I try to use Qt-only methods. If affordable, I'll go with them; if not, I'll follow @PCMan's suggestion.

**Comment by tsujan** [comment]
As the first step, I implemented the per-folder sorting for the View menu (and not context menu) in https://github.com/lxde/pcmanfm-qt/tree/preserve_setting. The code isn't polished at all -- I just wanted to see if it works -- and uses the function `fm_path_hash()`, which hopefully will do the job.

The reason why I insist on not using total per-folder settings is that my goal is separate settings for per-folder sorting and view mode.
