### ISSUE TITLE
PCManFM-qt complains about existing file/directory when filename contains '|'

### ISSUE THREAD

**Issue by Atalanttore** [lxde/pcmanfm-qt#344]
Hi,

PCManFM-qt (master) reports an existing file/directory when copying a file or directory with '**|**' in filename to an external drive (e.g. USB stick). That's at least a wrong error message, because the external drive is empty.

Regards,
Ettore

**Comment by tsujan** [comment]
This is a special case of https://github.com/lxde/pcmanfm-qt/issues/555. Please follow that report.
