### ISSUE TITLE
wallpaper not fit into a 4k panel (non-hdpi)

### ISSUE THREAD

**Issue by sl1pkn07** [lxde/pcmanfm-qt#346]
when set the wallpaper into a 4k panel (non-hdpi) , this is the result:

![](http://wstaw.org/m/2016/04/24/Screenshot_20160424_114654.png)

testing with all options. no sucess, like center image:

![](http://wstaw.org/m/2016/04/24/Screenshot_20160424_114946.png)

Uising pcmanfm-qt 0.10.0 on archlinux and Qt5 5.6.0

**Comment by sl1pkn07** [comment]
any notice?

**Comment by tsujan** [comment]
@sl1pkn07 
I'll look into it, although I don't have any knowledge about 4k displays (yet).

**Comment by PCMan** [comment]
This is unfortunately a regression bug of Qt.
FYI: https://github.com/lxde/lxqt/issues/1027
Please vote on the upstream Qt bug.

**Comment by pmattern** [comment]
So let's sum up the discussion in lxde/lxqt#1027 then.
