### ISSUE TITLE
changes are seemingly not applied when using Qt Creator

### ISSUE THREAD

**Issue by r-a-v-a-s** [lxde/pcmanfm-qt#356]
If I change all `show()` to `showMaximized()` in `application.cpp` in Qt Creator, 
it will see the file has changed and rebuild it before running. 
Yet when the app loads nothing has changed.
No windows will ever be shown maximized.
The executable's path is:
`/home/username/repositories/build-pcmanfm-qt-Desktop-Default/pcmanfm/pcmanfm-qt`

If I do everything the same with qTerminal's `main.cpp` it will start maximized.
What am I missing?
And where is the call to show() for the initial main window?

Qt Creator 4
Qt 5.6.0
openSUSE TumbleWeed

**Comment by palinek** [comment]
Sorry, but what is this issue abiut? You are changing the source code of application and your changes don't bring expected behaviour?
IMO this definitely isn't an issue. You need to invetigate/debug/test...normal development cycle.

**Comment by luis-pereira** [comment]
I really also don't understand what's the point here.

**Comment by agaida** [comment]
@r-a-v-a-s - in such cases it might be better to visit us in freenode #lxde

**Comment by r-a-v-a-s** [comment]
> IMO this definitely isn't an issue.

Usually I wouldn't have posted this as an issue; but this project doesn't have a forum I can find.
Is it acceptable to use the LXDE forum for lxqt questions? I don't use chatrooms.

However, if this isn't a problem on my end, it is most definitely an issue.
Did anyone try my simple test?

> You are changing the source code of application and your changes don't bring expected behaviour?

It doesn't seem to matter what I change in the code, it is not reflected in the program.

>  You need to investigate/debug/test...normal development cycle.

I spent most of my day yesterday setting up lxqt and doing what you stated...
I even confirmed that another lxqt project (qTerminal) doesn't have the same issue...

**Comment by agaida** [comment]
i guess that a normal user use the package manager of choice to install lxqt packages. And i guess this is the supported way for distributions. Hmm - anyway,  in case i want distribution like packages i would take their packages and update the code - and build these packages with the distribution tools. And if i would need help doing so i would try to reach the package maintainer of the distribution in charge and ask him for help.  my 2 ¢

**Comment by r-a-v-a-s** [comment]
I'm not a normal user; I'm a potential contributor.

**Comment by paulolieuthier** [comment]
@r-a-v-a-s I think the problem is that pcmanfm-qt is running in the background, for the desktop. You have to kill it before running it again.

> I'm a potential contributor.

Welcome!

**Comment by r-a-v-a-s** [comment]
Thank you :-]

You were right about it being in the background;
although, I think I misunderstood most of the code I changed. :astonished: 

I just found the correct `show()` in `launcher.cpp`.

:v:
