### ISSUE TITLE
remember window size and position, or start maximized

### ISSUE THREAD

**Issue by r-a-v-a-s** [lxde/pcmanfm-qt#357]
I've setup other programs to remember the window size and position,
with an option to start maximized instead.
I can do the work for this program.

**Comment by r-a-v-a-s** [comment]
Actually it looks like the code exists:

launcher.cpp
```
    mainWindow->resize(app->settings().windowWidth(), app->settings().windowHeight());

    if(app->settings().windowMaximized()) {
        mainWindow->setWindowState(mainWindow->windowState() | Qt::WindowMaximized);
    }
  }
```

**Comment by r-a-v-a-s** [comment]
It never starts maximized for me, and the size is always the same.

**Comment by r-a-v-a-s** [comment]
Sigh... it's somehow not remembered when launching from Qt Creator.
Launching directly from the executable will remember.

**Comment by r-a-v-a-s** [comment]
Hm... actually... LOL...
I launched it from within an already running instance....
If I launch the executable from konqueror, then the the window state is not remembered.
It seems to only be applied to secondary windows.
Can anyone confirm that?

**Comment by r-a-v-a-s** [comment]
A possible explanation is that
when you close the app after launching it from Creator
the background process does not exist.

When I use the installed version (downloaded with zypper)
the process will exist after closing,
and the dimensions will be remembered.

I'll reopen this because it looks like the position is never remembered.

**Comment by mir3x** [comment]
I think instead saving width , height and pos.
it should just saveGeometry onCloseEvent
and then restore onSowEvent.

Do u want me to send patch ?

**Comment by r-a-v-a-s** [comment]
I tried implementing it but was unsuccessful. 
I think the problem is I don't really understand pcmanfm's background process.

I'm busy with a few other projects right now... so go ahead if you are inspired.

**Comment by mir3x** [comment]
I did it but I think I srcewed something a bit.
I had config as ~/.config/pcmanfm-qt/lxqt/settings.conf
and now another one is created ~/.config/pcmanfm-qt/default/settings.conf
and that new one is used, or idk, mb it was there but I doubt.

Dont foroget to kill pcman-qt before restarting, bastard sits in memory, and I was
thinking wtf is wrong.
Probably I screwed more than this.


[geometry.zip](https://github.com/lxde/pcmanfm-qt/files/511387/geometry.zip)

**Comment by tsujan** [comment]
pcmanfm-qt remembers the size of its last closed window correctly when the corresponding option is enabled in its Preferences. It also has a setting for a fixed size.

As for remembering the position, it's only useful with some kinds of apps like notes managers, not with apps like file managers or text editors. Most apps should follow the WM positioning.
