### ISSUE TITLE
change focus order (<Tab> key) in connection dialog

### ISSUE THREAD

**Issue by antis81** [lxde/pcmanfm-qt#365]
Not sure, if this is the right repo, but the (login) dialog appears from PCManFM-Qt, when establishing a connection to a remote Samba share. Currently I don't have a screenshot available, so I try to explain. The three line edits from top to bottom …

1. Username
2. Domain
3. Password

… are ordered `1 -> 3 -> 2` when pressing the < Tab > key - should be `1 -> 2 -> 3`. I know it's a small usability issue, but especially annoying behavior for Windows user's (well, I'm none :smile:).

**Comment by npmiller** [comment]
You are correct, thanks for reporting this, https://github.com/lxde/libfm-qt/pull/31 should fix this.
