### ISSUE TITLE
BookMarks should be icon compliant

### ISSUE THREAD

**Issue by ghost** [lxde/pcmanfm-qt#37]
Booksmarks are all currently the default folder icon, they should instead use special folder icons, if needed, i.e. "Downloads folder"  "Images Folder" "Music Folder" etc.

Looks like the code is somewhere in libfm-qt gonna try to work on it myself.. but still getting up to speed

**Comment by tsujan** [comment]
Since pcmanfm-qt supports custom folder icons now, this is more relevant now than before.

**Comment by tsujan** [comment]
Looking through old reports is helpful sometimes. I use a patch since 2015 but forgot to make a PR ;)
