### ISSUE TITLE
Git and svn support (feature request)

### ISSUE THREAD

**Issue by AlexYeCu** [lxde/pcmanfm-qt#372]
Git and svn support, at least marking unversioned/untracking files and addind/removing any of them. That'll be great for projects which have a lot of graphical or multimedia resources.

**Comment by jleclanche** [comment]
This will never happen natively in pcmanfm-qt. If someone wants to write some sort of plugin, feel free.

**Comment by tsujan** [comment]
I agree with @jleclanche . pcmanfm-qt isn't supposed to do jobs of other apps. I also vaguely remember another feature request about music tags. Such features would bloat pcmanfm-qt, IMO.

**Comment by ahsand97** [comment]
I did a minimal implementation (not a real plugin) based on Dolphin's rabbitvcs implementation (only context menu actions), you can check it [here](https://github.com/rabbitvcs/rabbitvcs/pull/341)

**Comment by tsujan** [comment]
@ahsand97 
That's the correct way. In 2016 (when this report was opened), custom actions might not be completely ready. Now, the custom action functionality is exactly for such jobs.

**Comment by ahsand97** [comment]
@tsujan 
Can something like expose a service via Dbus to change an emblem to a file be done?? I think that's one of the most liked things about using TortoiseSVN (on Windows) or RabbitVCS with the file managers that has official support, you can see if a full folder is up to date or if there are files with changes just by looking at the emblems, that way pcmanfm-qt wouldn't be responsible to write a plugin but it can be done externally.

**Comment by tsujan** [comment]
> Can something like expose a service via Dbus to change an emblem to a file be done??

Theoretically it's possible but will be worth the effort only if it needs a relatively small code. I might look into it if I find the time.
