### ISSUE TITLE
Buggy file selection

### ISSUE THREAD

**Issue by AlexYeCu** [lxde/pcmanfm-qt#373]
This bug is for version 0.10, so please check if it's still presented at 0.11 and later.
Bug: two files can be selected in one click.
The way to reproduce is unusual.
1. Install xmonad (may be other tile wm will show the same result too).
2. Make a directory, which contains several files with long names — about 100 symbols (not so much for a musical clip, for example).
3. Install ffmpegthumbnailer to watch video thumbs).
4. Make pcmanfm's icons size equal to 96 or 128.
5. Close pcmanfm-qt and then open it (should be tiled by default).
6. We can see some rows of files.
7. Now, select one and you'll select another one above (or under) selected one. Two (or more) files selected, and any action (renaming,deleting,etc) will work for all files, selected this way.
8. This works only for files with long names, not for files with short names.
9. Untiling and tiling again the pcmanfm's window removes the bug for current pcmanfm's process.

**Comment by pmattern** [comment]
Issues like this have been discussed in lxde/pcmanfm-qt#251 and lxde/lxqt#768 and fixed in lxde/pcmanfm-qt#252.
So I suggest you test a recent checkout or wait until 0.11 is available on your system before we perform the rather sophisticated tests you propose.

**Comment by tsujan** [comment]
@AlexYeCu 
If this isn't related to what's fixed by https://github.com/lxde/pcmanfm-qt/pull/252, the problem might be in xmonad. Is https://github.com/lxde/pcmanfm-qt/pull/252 applied in the version you have? *If it is*, do you see the same behavior with other WM's?

**Comment by tsujan** [comment]
@AlexYeCu If you can see file names with 4 lines, you don't have https://github.com/lxde/pcmanfm-qt/pull/252.

**Comment by AlexYeCu** [comment]
I can see 4 lines, dolphin, for example, shows 2 only.

**Comment by tsujan** [comment]
> I can see 4 lines

Then your installed version is old. Please update pcmanfm-qt!
