### ISSUE TITLE
improve folderitemdelegate when icons are not available at the requested size

### ISSUE THREAD

**Issue by rafirafi** [lxde/pcmanfm-qt#377]
I've seen that the code in folderitemdelegate assumes that the returned pixmap is of the asked size, but Qt doesn't scale the pixmap automatically. I propose a simple solution but I must say that I'm not really familiar with the code base, and maybe this is already checked by the consummer ? If so fell free to ignore this.

```
--- libfm-qt-master/src/folderitemdelegate.cpp	2016-06-17 09:13:17.000000000 +0200
+++ libfm-qt-master/src/folderitemdelegate.patched.cpp	2016-07-27 23:27:09.017724424 +0200
@@ -92,6 +92,10 @@
     QIcon::Mode iconMode = iconModeFromState(opt.state);
     QPoint iconPos(opt.rect.x() + (opt.rect.width() - opt.decorationSize.width()) / 2, opt.rect.y());
     QPixmap pixmap = opt.icon.pixmap(opt.decorationSize, iconMode);
+    // rescale the icon if necessary
+    if (pixmap.size() != opt.decorationSize) {
+        pixmap = pixmap.scaled(opt.decorationSize, Qt::KeepAspectRatio, Qt::SmoothTransformation);
+    }
     painter->drawPixmap(iconPos, pixmap);
 
     // draw some emblems for the item if needed
```

[folderitemdelegate.cpp.patch.zip](https://github.com/lxde/pcmanfm-qt/files/387244/folderitemdelegate.cpp.patch.zip)

**Comment by tsujan** [comment]
> I've seen that the code in folderitemdelegate assumes that the returned pixmap is of the asked size

`QIcon::pixmap()` returns a pixmap that might be smaller than the requested size but never larger. So, in pcmanfm-qt, if an icon/image is smaller than what is set in `Preferences → Display → Icons`, it'll be shown with its real size but if it's larger that it, it'll be scaled down to it.

I don't see a problem here but if you do, please explain it more clearly, for example, with a screenshot. Thanks!

**Comment by tsujan** [comment]
In the following screenshot, the only available icon for mutt is `/usr/share/pixmaps/mutt.xpm`, which is 32x32, while the grid icon size is 64x64. So, the mutt icon occupies only 1/4 of the available area.

![icons](https://cloud.githubusercontent.com/assets/981076/17199808/0ffced98-5495-11e6-855d-75d9b2cd3d65.png)

IMO, this is the correct behavior; otherwise the mutt icon would be blurred. If, for example, an icon set doesn't provide icons > 48x48, it should be considered imcomplete. And if a file manager scales up such icons, I'll see *that* as a bug.

**Comment by rafirafi** [comment]
You're right usually icons are usually not scaled in file managers, I just tested again and it's ok to scale a little but too much is really ugly. Anyway, the patch was not complete.

> an icon set doesn't provide icons > 48x48, it should be considered imcomplete

It was more for the .desktop files, some only have a ridiculously small icon.
 
 I would still prefer the text aligned and the icon centered in a rect of the requested icon size, like it's done in thunar p.ex. Let me know if you're interested.
 
 If you want to test quickly, you can save the option.decorationSize before initStyleOption and use it to calculate textRect in ::sizeHint and ::paint (but the iconPos.y() is not corrected).
 
 Thanks for the quick answer.

**Comment by tsujan** [comment]
> It was more for the .desktop files, some only have a ridiculously small icon.

If the icons they refer to are also small, that can't be seen as a bug, IMHO. If not, an example please!

> I would still prefer the text aligned and the icon centered in a rect of the requested icon size

I agree. `folderitemdelegate.cpp` and some other files were edited to fix old bugs about icon and text rects, all of which seem to be resolved now. So, any change should be made with care. I'll look into it but if you have a working patch, you're welcome to make a PR.

**Comment by tsujan** [comment]
Oh, here I can also see a real bug: if the icon of the desktop file is small, the whole item won't be shown correctly at first but it will be shown correctly after the page is reloaded. To test it, first stop pcmanfm-qt by going to `Configuration Center → Session Settings` and stopping Desktop, and then start it again and go to a folder containing a desktop file with a small icon!

**Comment by tsujan** [comment]
OK! I succeeded in fixing both issues:

![small_icon](https://cloud.githubusercontent.com/assets/981076/17204107/bf09bc80-54b8-11e6-9d6c-9da2c389a5db.png)

Now, small icons are centered and their texts are aligned with other item texts. I'll make a PR after some tests -- maybe tomorrow.

**Comment by rafirafi** [comment]
I just saw the message but I already made a patch, you can compare with yours in case it helps. 
[folderitemdelegate.cpp.patch.zip](https://github.com/lxde/pcmanfm-qt/files/388506/folderitemdelegate.cpp.patch.zip)

**Comment by tsujan** [comment]
Yes, that's the way of centering small icons in the icon view but there are still other issues, on which I'm working. They are related to compact and list views and are caused by big icons as well as small ones.

**Comment by tsujan** [comment]
@rafirafi 
The problems in compact and list views were deeper than I thought and deserve a separate bug report, which I'll make. I haven't found a solution to them yet.

However, https://github.com/lxde/libfm-qt/pull/32 is the fix I found for this issue. It's essentially the same as your last patch.
