### ISSUE TITLE
Text direction of files/dirs name is base on the layout

### ISSUE THREAD

**Issue by SafaAlfulaij** [lxde/pcmanfm-qt#378]
The text direction of the name of the files/dirs is based on the UI layout. If it is RTL, all the items are RTL (Even for LTR items).
Please check this screeshot:
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17213339/af7b647a-54dc-11e6-8bec-ca0d5f0b868d.png)
The first folder is named "safa123 العربية". The "العربية" part is on the left while it should be on the right as in Konsole.
And the second is "test_". Same goes for the underscore here.

**Comment by tsujan** [comment]
Yes, the painter draws text based on the layout direction while it should do so based on the string direction. Thanks for reporting!

**Comment by tsujan** [comment]
Before trying to fix this issue, I wanted to ask a question: Are items with very long Arabic texts OK? In English, if ending letters of a long word are drawn on the next line, the word will still be legible:
````
Programm
ing
````
What about Arabic? I ask because in the case of illegibility, the fix might be really tricky if possible at all.

**Comment by SafaAlfulaij** [comment]
It is fine. As long as the shaping doesn't break (Like what is now), it's ok. Other file managers do the same (Dolphin, Nautilus).

![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17237371/f1f0dfb0-5559-11e6-8c3c-228e0f96c5f2.png) (Nautilus)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17237372/f1f12128-5559-11e6-9db7-756df2c89476.png) (PCManFM-Qt)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17237373/f1f1aeea-5559-11e6-81b6-08ee7c1435e9.png) (Dolphin)

**Comment by tsujan** [comment]
@SafaAlfulaij 
OK! That was good news.

Would you please also test https://github.com/lxde/libfm-qt/issues/33 to see if it fixes the direction problem?

**Comment by SafaAlfulaij** [comment]
@tsujan Now it's LTR for all the items :(

**Comment by tsujan** [comment]
But here, with `-reverse`, they are OK:

![test](https://cloud.githubusercontent.com/assets/981076/17237811/0461f02e-556b-11e6-9671-5703b6729072.png)

Could you show a screenshot?

**Comment by SafaAlfulaij** [comment]
Here you are:
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17237865/07abc716-555f-11e6-9197-20b8333f9f6d.png)

Notice the underscore at the right in PCManFM-Qt and at the left in Dolphin.

**Comment by tsujan** [comment]
Even underscores are correct here:

![test1](https://cloud.githubusercontent.com/assets/981076/17237978/f1b12f2e-556c-11e6-91c1-aeb7e5549094.png)

Are you sure there isn't something wrong with your test? Because `-reverse` should have the same effect.

**Comment by SafaAlfulaij** [comment]
Strange. If it's right for you then just ignore my screenshot.
Just to be sure, you wrote "العربية" then the underscore right? :smile:

**Comment by tsujan** [comment]
> Just to be sure, you wrote "العربية" then the underscore right?

Yes! I'm familiar with the Arabic alphabet ;) The names are exactly the same as when they're copy/pasted into a text editor.

> Strange. If it's right for you then just ignore my screenshot.

I couldn't merge the PR unless it works for you too.

**Comment by SafaAlfulaij** [comment]
:)
I changed anything related to locale that I could think of, nothing is working.
What is your Qt version?

**Comment by tsujan** [comment]
> What is your Qt version?

On Debian, it's 5.6.1. I haven't tested it under Manjaro with Qt-5.7 yet but I could if your Qt is 5.7.

I vaguely remember you had a similar issue in testing a PR related to the panel but later you said it was fixed.

Are your results the same under LXQt and KDE?

**Comment by SafaAlfulaij** [comment]
> I vaguely remember you had a similar issue in testing a PR related to the panel but later you said it was fixed.

That's why I told you to ignore my issue, it may fix itself later on :$

And yes, the results are the same. Using Qt 5.7.
Thanks for fixing this bug :)

**Comment by tsujan** [comment]
Sorry! It was my fault: that wasn't a *real* underscore (long story short, I realized that under Manjaro). Please test the revised PR https://github.com/lxde/libfm-qt/pull/33!

**Comment by SafaAlfulaij** [comment]
YES! It is fixed now! Thanks :)

**Comment by tsujan** [comment]
Thanks for your patience and sorry for that underscore thing -- I had 4 languages on my keyboard layout and after adding Arabic, I made that mistake ;)

**Comment by tsujan** [comment]
It seems that the compact and detailed list views have this problem too. However, in those modes, the text is drawn by Qt itself, so it can be seen as a Qt issue. If, in future, pcmanfm-qt also draws those items directly, the problem could be fixed in a similar way.

BTW, a fix for desktop will come soon.

**Comment by SafaAlfulaij** [comment]
Oh, yes. I forgot to mention it! I think there won't be a fix in Qt in the near future, so why don't you do the same by subclassing? And when a fix is released we can remove it ;)

**Comment by pmattern** [comment]
> EDIT: Filed a bug report :)

Would be good if you linked it here.

**Comment by tsujan** [comment]
> Oh, yes. I forgot to mention it! I think there won't be a fix in Qt in the near future...

Drawing icon and text directly in those modes requires a lot of work. If they present further problems, there might be enough reason to do so, but not yet, IMO.

**Comment by SafaAlfulaij** [comment]
> Would be good if you linked it here.

Here you are: https://bugreports.qt.io/browse/QTBUG-55012

> Drawing icon and text directly in those modes requires a lot of work. If they present further problems, there might be enough reason to do so, but not yet, IMO.

An easier way is prepending "RLE" and "LRE" just for the view, not the actual filename.

**Comment by tsujan** [comment]
Let's make it clearer:

**Drawing text should be based on its own direction, not on the layout direction.** There are some places in Qt where this rule isn't followed -- in view items and combo boxes, for example. That's an *old* and annoying bug that should be fixed in Qt. (I'll think about a workaround in Kvantum but no promise.)

However, pcmanfm-qt draws texts directly in icon and thumbnail views and, in those cases, it does so correctly after https://github.com/lxde/libfm-qt/pull/33.

**Comment by SafaAlfulaij** [comment]
> BTW, a fix for desktop will come soon.

https://github.com/lxde/pcmanfm-qt/blob/master/pcmanfm/desktopitemdelegate.cpp#L97 ?

**Comment by tsujan** [comment]
Exactly! I wanted to make a unified PR for this and the desktop version of https://github.com/lxde/libfm-qt/pull/32 but you could make a separate PR for this if you want.
