### ISSUE TITLE
Scrambled statusbar message for files with RTL names

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#379]
This image explains everything:

![1](https://cloud.githubusercontent.com/assets/981076/17270283/665b03ec-5674-11e6-8b9d-db622e1f443d.png)

I couldn't find a way of showing the message correctly for both LTR and RTL layouts, especially with mixed strings (I even tried `0x202E` and `0x202D`).

**Comment by SafaAlfulaij** [comment]
Please ping me in case you are stuck with RTL stuff ;)
This is an easy task:

LTR layout:
`LRM + "\"%1\"" + LRM + "(b...."`
RTL layout:
`RLM + "\"%1\"" + RLM + "(b...."`

For the file name, if `isRightToLeft` then you should prepend and append RLM to it, if it's not then LRM.
And that should fix it :)
RTL filename: `RLM + %1 + RLM`
LTR filename: `LTR + %1 + LTR`

While I'm not sure if we really need to prepend the RLM/LRM, need to be tested by all possibilities :)

**Comment by SafaAlfulaij** [comment]
But we have to think to not make string puzzles for the translators, that is not a good i18n practise.

**Comment by tsujan** [comment]
@SafaAlfulaij 
Thanks for the hint, but aren't `RLM` and `LRM` the same as `0x202E` and `0x202D` respectively? As I said above, I'd already tried them (in the same way you suggested). They worked with "pure" RTL strings but with mixed ones they caused a mess.

As for translation, I agree with you. However, the rest of tthe statusbar message doesn't seem translatble to me because of its source in libfm.

**Comment by tsujan** [comment]
OK, `0x202E` and `0x202D` are RLO and LRO respectively, while RLM and LRM are `0x200F` and `0x200E`. I'll try them tomorrow.

**Comment by tsujan** [comment]
@SafaAlfulaij
I reached a seemingly acceptable formula at https://github.com/lxde/pcmanfm-qt/pull/380. Would you please test it?

Please note that:

(1) This is for both LTR and RTL layouts;

(2) The "underscore problem" persists because of a problem like QTBUG-55012 for label texts; and

(3) The info part of message is always in English for now but a future translation for RTL languages is predicted in the commit.

**Comment by tsujan** [comment]
Two screenshots, one for ltr layout:

![ltr](https://cloud.githubusercontent.com/assets/981076/17275051/5bde5b58-570f-11e6-998b-ac8f36957305.png)

And the other for rtl layout:

![rtl](https://cloud.githubusercontent.com/assets/981076/17275052/6373c556-570f-11e6-9551-4c32daa08e45.png)

**Comment by SafaAlfulaij** [comment]
Well, English folders still miss up the string. You should use the Arabic translation for checking that.
I did this small patch that worked for me:
```diff
diff --git a/pcmanfm/tabpage.cpp b/pcmanfm/tabpage.cpp
index 72c22c6..e2cb6ce 100644
--- a/pcmanfm/tabpage.cpp
+++ b/pcmanfm/tabpage.cpp
@@ -417,15 +417,21 @@ void TabPage::onSelChanged(int numSel) {
       FmFileInfoList* files = folderView_->selectedFiles();
       FmFileInfo* fi = fm_file_info_list_peek_head(files);
       const char* size_str = fm_file_info_get_disp_size(fi);
+      QString dispName = QString("%1").arg(QString::fromUtf8(fm_file_info_get_disp_name(fi)));
+      QChar directionOfDispName = dispName.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
+      dispName = directionOfDispName + dispName + directionOfDispName;
+      QChar directionOfMessage = (QApplication::layoutDirection() == Qt::RightToLeft) ? QChar(0x200F) : QChar(0x200E);
       if(size_str) {
-        msg = QString("\"%1\" (%2) %3")
-                        .arg(QString::fromUtf8(fm_file_info_get_disp_name(fi)))
+        msg = QString("%1\"%2\"%1 (%3) %4")
+                        .arg(directionOfMessage)
+                        .arg(dispName)
                         .arg(QString::fromUtf8(size_str ? size_str : ""))
                         .arg(QString::fromUtf8(fm_file_info_get_desc(fi)));
       }
       else {
-        msg = QString("\"%1\" %2")
-                        .arg(QString::fromUtf8(fm_file_info_get_disp_name(fi)))
+        msg = QString("%1\"%2\"%1 %3")
+                        .arg(directionOfMessage)
+                        .arg(dispName)
                         .arg(QString::fromUtf8(fm_file_info_get_desc(fi)));
       }
       /* FIXME: should we support statusbar plugins as in the gtk+ version? */
```

**Comment by tsujan** [comment]
> Well, English names still miss up the string.

Yes, that was my point (2) above (it isn't limited to underscores). I'm surprised to see your approach fixes that but it creates another problem with RTL layouts. This is with your method:

![2016-08-01-13 03 03-scrot](https://cloud.githubusercontent.com/assets/981076/17288261/62fc043c-57e9-11e6-9730-e1e7414b1a4c.png)

An this with mine:

![2016-08-01-13 03 45-scrot](https://cloud.githubusercontent.com/assets/981076/17288269/6ce64cc8-57e9-11e6-9152-f57637bea109.png)

We have to find a way to use the best of both.

**Comment by SafaAlfulaij** [comment]
Well, another QChar variable can be made for the size_str, but I don't think we really need to go into this because the Arabic layout will be translated, right?

**Comment by tsujan** [comment]
If you're OK with that I couldn't disagree. However, I'll try a little to fix it too when I have time and if not possible, will copy your method.

**Comment by SafaAlfulaij** [comment]
I can fix it, but need to know why is https://github.com/lxde/pcmanfm-qt/blob/master/pcmanfm/tabpage.cpp#L423 while there is an if statement for it..

**Comment by tsujan** [comment]
You mean why there's a condition on `size_str`? Files like `inode/socket` don't have size.

**Comment by SafaAlfulaij** [comment]
No, the code is checking the `size_str` in 420, and if it doesn't have size (Null/Empty), it goes to the `else` block. The thing is that it is checked again in the `if` statement while the variable contain something..

It's like:
```c++
int a = 0
if a
    cout << a? 1 : 0;
```

If there is something strange that is happening, it needs a comment ;)

**Comment by tsujan** [comment]
Oh, you're right. I never paid attention to that. It was probably needed at some point but is left as it was. It's redundant now.

**Comment by SafaAlfulaij** [comment]
Well, I tried this:
```diff
diff --git a/pcmanfm/tabpage.cpp b/pcmanfm/tabpage.cpp
index 72c22c6..b5ad147 100644
--- a/pcmanfm/tabpage.cpp
+++ b/pcmanfm/tabpage.cpp
@@ -416,17 +416,32 @@ void TabPage::onSelChanged(int numSel) {
     if(numSel == 1) { /* only one file is selected */
       FmFileInfoList* files = folderView_->selectedFiles();
       FmFileInfo* fi = fm_file_info_list_peek_head(files);
-      const char* size_str = fm_file_info_get_disp_size(fi);
-      if(size_str) {
-        msg = QString("\"%1\" (%2) %3")
-                        .arg(QString::fromUtf8(fm_file_info_get_disp_name(fi)))
-                        .arg(QString::fromUtf8(size_str ? size_str : ""))
-                        .arg(QString::fromUtf8(fm_file_info_get_desc(fi)));
+
+      QString sizeStr = QString("%1").arg(QString::fromUtf8(fm_file_info_get_disp_size(fi)));
+      QChar directionOfSizeStr = sizeStr.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
+
+      QString dispName = QString("%1").arg(QString::fromUtf8(fm_file_info_get_disp_name(fi)));
+      QChar directionOfDispName = dispName.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
+      dispName = directionOfDispName + dispName + directionOfDispName;
+
+      QString fileDesc = QString("%1").arg(QString::fromUtf8(fm_file_info_get_desc(fi)));
+      QChar directionOfFileDesc = fileDesc.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
+      fileDesc = directionOfFileDesc + fileDesc + directionOfFileDesc;
+
+      QChar directionOfMessage = (QApplication::layoutDirection() == Qt::RightToLeft) ? QChar(0x200F) : QChar(0x200E);
+      if(!sizeStr.isEmpty()) {
+        msg = QString("%1\"%2\"%1 %3(%4)%3 %1%5")
+                        .arg(directionOfMessage) // RTL/LTR layout
+                        .arg(dispName)
+                        .arg(directionOfSizeStr)
+                        .arg(sizeStr)
+                        .arg(fileDesc);
       }
       else {
-        msg = QString("\"%1\" %2")
-                        .arg(QString::fromUtf8(fm_file_info_get_disp_name(fi)))
-                        .arg(QString::fromUtf8(fm_file_info_get_desc(fi)));
+        msg = QString("%1\"%2\"%1 %3")
+                        .arg(directionOfMessage) // RTL/LTR layout
+                        .arg(dispName)
+                        .arg(fileDesc);
       }
       /* FIXME: should we support statusbar plugins as in the gtk+ version? */
       fm_file_info_list_unref(files);
```
This fixes all the files, but not the dirs (multiselection).
I really think that we can go mad with it but it's not really needed. :smile:

**Comment by tsujan** [comment]
Thanks a lot! Right now I'm very busy but I'll surely look into it as soon as I have time. At a glance, it seems more complex than my method ;)

**Comment by tsujan** [comment]
Your last method works in most cases but

(1) It doesn't work in the LTR layout direction when an RTL string is followed by an LTR one without a space; and
(2) It doesn't treat all strings in the same way, so the logic is obscure.

Based on my recent understanding of bidi, strong chars, weak chars and so on, I modified your method to treat all strings on the same level and it worked as before; (1) still persisted though.

All in all, I'm getting the impression that there's something wrong in how Qt handles bidi. IMO, the logic shouldn't be so complex. Actually, I think that if Qt handled bidi correctly, we wouldn't need to change anything.

**Comment by tsujan** [comment]
My version of your code, in which all strings are treated in the same way:

````
.....
      QString ld = QApplication::layoutDirection() == Qt::RightToLeft ? QChar(0x200F) : QChar(0x200E);

      QString dispName = QString::fromUtf8(fm_file_info_get_disp_name(fi));
      QString dispNameDir = dispName.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
      dispName = ld + QString("\"") + dispNameDir + dispName + dispNameDir + QString("\"");

      QString sizeStr = QString::fromUtf8(fm_file_info_get_disp_size(fi));
      QString sizeStrDir = sizeStr.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
      sizeStr = ld + sizeStrDir + QString("(") + sizeStr + QString(")") + sizeStrDir;

      QString fileDesc = QString::fromUtf8(fm_file_info_get_desc(fi));
      QString fileDescDir = fileDesc.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
      fileDesc = ld + fileDescDir + fileDesc + fileDescDir;

      if(!sizeStr.isEmpty()) {
        msg = QString("%1 %2 %3").arg(dispName).arg(sizeStr).arg(fileDesc);
      }
.....
````

**Comment by SafaAlfulaij** [comment]
In case it works for you then fine.
But I think that sizeStr will have a value since you modified it before the `if `statement. I'm not sure if that's correct.

And for Qt, open a bug :)

**Comment by tsujan** [comment]
I didn't write the whole code. Anyway, I admit that it can't be correct. The logic is absurdly complex ;)

As for reporting the bug, the problem is that we may not be able to provide the Qt developers with a clear explanation of the problem. My vague statement would be so:

QString().arg() doesn't work as expected with bidi, especially when it includes characters like `\"` and "(".

**Comment by tsujan** [comment]
We should have considered LRE/RLE beside LRM/RLM. This *seems* to work in all cases for me:
````
      /* consider the text and layout directions */
      QString mDir, eDir;

      QString dispName = QString::fromUtf8(fm_file_info_get_disp_name(fi));
      mDir = dispName.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
      eDir = dispName.isRightToLeft() ? QChar(0x202B) : QChar(0x202A);
      dispName = mDir + QString("\"") + mDir + eDir + dispName + mDir + QString("\"");

      QString sizeStr = QString::fromUtf8(fm_file_info_get_disp_size(fi));
      mDir = sizeStr.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
      eDir = sizeStr.isRightToLeft() ? QChar(0x202B) : QChar(0x202A);
      sizeStr = mDir + QString("(") + mDir + eDir + sizeStr + mDir + QString(")");

      QString fileDesc = QString::fromUtf8(fm_file_info_get_desc(fi));
      mDir = fileDesc.isRightToLeft() ? QChar(0x200F) : QChar(0x200E);
      fileDesc = mDir + fileDesc + mDir;

      if(size_str) {
        msg = QString("%1 %2 %3").arg(dispName).arg(sizeStr).arg(fileDesc);
      }
      else {
        msg = QString("%1 %2").arg(dispName).arg(fileDesc);
      }
      /* FIXME: should we support statusbar plugins as in the gtk+ version? */
````
However, the logic is still ridiculously complex ;) Such a change isn't worth a PR, IMO.

**Comment by SafaAlfulaij** [comment]
Well, I think we should stick with https://github.com/lxde/pcmanfm-qt/issues/379#issuecomment-236516917 if it works. We really don't have to go this far and it was just a challenge for me (and you maybe).
You can see what the Konversation team done years ago: [Here](https://quickgit.kde.org/?p=konversation.git&a=blob&h=e43b9c3f85d92c8773fb226456b771f117940dd0&hb=86ea44df0a3c0f6e0de082af807f4d729675ccbf&f=src%2Fviewer%2Fircview.cpp) (Line 531 and down for like 8 methods).
_And now it's broken :P_

I liked this:
> QString().arg() doesn't work as expected with bidi, especially when it includes characters like \" and (.

They should do exactly what we are doing here, adding RLM/LRM around the strings.
But I'm not sure if it will land because one can use QString in an edit box and the user will get like 6 unicode marks that the cursor won't move while moving through the letters.
All the applications behave as Qt behaves right now, even the HTML renderer in the browser.

**Comment by tsujan** [comment]
@SafaAlfulaij 
I found a concise and logical way of doing it, considering both mark and embedding directions, and will make another PR later.

Now I think this isn't something Qt devs could fix in all places -- it should be fixed in apps.

And yes, it was a challenge but I don't like the current bias toward LTR, although I don't use RTL. Anyway, we can't ignore Arabic, Hebrew, Persian, ....

**Comment by tsujan** [comment]
@SafaAlfulaij 
This is my latest attempt to tame RTL+LTR. Please test it and tell *it works in all cases*, or I'll tear my hair out ;)

**Comment by SafaAlfulaij** [comment]
I think you just forgot:
`QChar directionOfMessage = (QApplication::layoutDirection() == Qt::RightToLeft) ? QChar(0x200F) : QChar(0x200E);
`
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17329828/045d3150-58cd-11e6-8a17-1582052f58a5.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17329829/045e7f1a-58cd-11e6-86b3-e35619ce6ece.png)

**Comment by tsujan** [comment]
No, I don't think it's needed. Both screenshots seem OK to me (if the the first filename is "0eng" and the second it "صفاـ").

**Comment by tsujan** [comment]
In short, all LTR strings should be written left to right and all RTL strings right to left -- and they are in your screenshot.

**Comment by SafaAlfulaij** [comment]
But I don't see it nice that if the name is RTL, it's on the right, and if it's LTR it's on the left..
But it is not a big problem. Can be pushed now!
Thanks :)

**Comment by tsujan** [comment]
I agree it isn't nice, but that's because some strings are *not* translated into Arabic in it; once they are, it should read from right to left correctly. Actually, checking `QApplication::layoutDirection()` was one of the reasons why it didn't work in all cases.

I tested it for both LTR and RTL layouts, with pure and mixed LTR and RTL texts. As far as I see, it works as intended. Your opinion is more important, of course.

**Comment by SafaAlfulaij** [comment]
> but that's because some strings are not translated into Arabic in it

The strings will be _after_ the file name, not before it. So the filename direction will decide the direction of the whole line, or I missing something?

_The scrollbar is waay too small, seems that we talked about a really serious bug in the app :P_

**Comment by tsujan** [comment]
> The strings will be after the file name...

The meaning of "after" depends on *the string direction* itself, not on the layout direction. When I understood that, all things got easier and I realized why my previous attempts weren't successful.

> The scrollbar is waay too small, seems that we talked about a really serious bug in the app :P

Which scrollbar? I didn't get it.

**Comment by tsujan** [comment]
Think about this example:
![rtl](https://cloud.githubusercontent.com/assets/981076/17332152/062bd70a-58e3-11e6-9064-4292ea22b513.png)
I started with صفا and switched to English in a text editor. It's exactly as it should be.

**Comment by SafaAlfulaij** [comment]
**OH**! My bad! I thought the sequence is Name - Type - Size !! Sorry!
Where is the "0 bytes" string? :)

**Comment by SafaAlfulaij** [comment]
Finally I'm back to lxqt for a while :-) It is really great how stable it is! Great work you made guys :+1: 

Since I worked on fixing the bidi problems in _Konversation_, I used a better way of having all of this neatly (to some extent).
The idea is to have one function that will take a string, prepend and append the needed mark, and return it back (for each one of the placeholders).
And then in the final _translatable_ string we use LRM mark like so:
(we can use `QString::fromUtf8` here, to make them [visible](https://stackoverflow.com/questions/35215398) to translators)
```
msg = QString(LRM"\"%1\" LRM(%2) LRM%3")
```
and the Arabic/Persian/Hebrew translation will have RLM instead. That's all.
Same lines, but shorter and separated depending on the function.

**Comment by tsujan** [comment]
The problem shown in the first screenshot still persists.

In the meanwhile, I acquired some experience about how to make translating easier. IMHO, a GUI program should be written in such a way that its translation be about *language*, not about computer terms. For example, the translator shouldn't need to know what `LRM` or `LRM` is. It's even better to remove signs like `"\"%1\"`, `<i>` or `<b>` from translatable strings as far as possible (exceptions are acceptable).

My previous solution worked but was too complex. @SafaAlfulaij I'll look into this problem again but feel free to make a PR if you've found a simple way to fix it.

**Comment by SafaAlfulaij** [comment]
> The problem shown in the first screenshot still persists.

You mean with the function thing, or without? Yes I know it's still there since this bug is still open :)

> its translation be about language, not about computer terms.

Well, we are surrounded with computer terms everywhere, we can't just omit them. Tab, button, zip, mouse, etc.

> For example, the translator shouldn't need to know what `LRM` or `RLM` is.

We can tell him to have it in the same way it's there in the original text, e.x. before each of the placeholders.

> It's even better to remove signs like `"\"%1\"`, `<i>` or `<b>` from translatable strings as far as possible (exceptions are acceptable).

This is okay till you reach to a place where you make [word puzzles](https://techbase.kde.org/Development/Tutorials/Localization/i18n_Mistakes#Pitfall_.232:_Word_Puzzles), and you must stop and step back :)

> My previous solution worked but was too complex.

I'll check it again, but I just had to say one thing:
If the UI is LTR, then the sequence of placeholders must be LTR. The name should appear on the left, and it's size to its right, and the description to the size's right.
I treat it as an invisible table.

`"ARABIC_TEXT" (5 bytes) Writer file.`
not:
`Writer file. (5 bytes) "ARABIC_TEXT"`
The later is only if the UI is RTL.

**Comment by tsujan** [comment]
As for "word puzzles", they're signs of bad coding, of course; each translatable string should convey a complete meaning --  a "Gestalt". And by computer terms, I really meant *coding* terms and signs, as the above examples showed.

**Comment by tsujan** [comment]
An example: This is good:
```
Do you want to use <b>MS Windows</b> end-of-lines?
```
But this is not:
```
<center>Do you want to use <b>MS Windows</b> end-of-lines?</center>
```
Anyhow, on this page, we're dealing with parentheses and how they're opened/closed.

**Comment by SafaAlfulaij** [comment]
I tested this (not an _actual_ diff):
``` diff
+QString TabPage::getFinalFormat(QString text) {
+    QChar bidiMark = text.isRightToLeft()? QChar(0x200f) : QChar(0x200e);
+    return bidiMark+text+bidiMark;
+}

// when the current selection in the folder view is changed
void TabPage::onSelChanged() {
    QString msg;
    if(folderView_->hasSelection()) {
        auto files = folderView_->selectedFiles();
        int numSel = files.size();
        /* FIXME: display total size of all selected files. */
        if(numSel == 1) { /* only one file is selected */
            auto& fi = files.front();
            if(!fi->isDir()) {
+                msg = QString("%4\"%1\" %4(%2) %4%3")
+                      .arg(getFinalFormat(fi->displayName()))
+                      .arg(getFinalFormat(Fm::formatFileSize(fi->size(), fm_config->si_unit))) // FIXME: deprecate fm_config
+                      .arg(getFinalFormat(fi->mimeType()->desc()))
+                      .arg(QString::fromUtf8(
+                          (!layoutDirection() == Qt::LeftToRight) ? "\u200f" : "\u200e"));
            }
            else {
+                msg = QString("%3\"%1\" %3%2")
+                      .arg(getFinalFormat(fi->displayName()))
+                      .arg(getFinalFormat(fi->mimeType()->desc()))
+                      .arg(QString::fromUtf8(
+                          (!layoutDirection() == Qt::LeftToRight) ? "\u200f" : "\u200e"));
            }
```

And I didn't find any issue!

**Comment by tsujan** [comment]
Just for the record, these are all cases that should be tested:

(1) LTR layout + LTR Locale (English,...) + RTL file name (Arabic, Persian, Hebrew,...)
(2) RTL layout + RTL Locale + LTR file name
(3) Everything LTR
(4) Everything RTL

**Comment by SafaAlfulaij** [comment]
I used `!` and `_` as first and last characters to test if the marks are working as intended.
So `!user_` should not be displayed as `_user!` or `_!user`, etc.

And yes, I tested the 4 cases, and all worked fine.
The only problem will happen if you used LTR locale in RTL layout, or vice versa, but this isn't an acceptable case to mess the code for. :)

**Comment by tsujan** [comment]
> The only problem will happen if you used LTR locale in RTL layout, or vice versa, but this isn't an acceptable case to mess the code for

I agree.

If all tests are passed, please make a PR!
