### ISSUE TITLE
Saving and Restoring Search Utility Checkboxes

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#387]
Based on my frequent use of the nifty search utility, I found that regular expression and subdirectory checkboxes were better checked by default, so I changed their default state for my personal use.

What about _saving_ the states of checkboxes for regular expresion, case sensitivity, subdirectory and hidden file search and restoring them on the next use?

**Comment by stefonarch** [comment]
+1 for saving, I actually have always to select case sensitity and subfolders before searching.

**Comment by tsujan** [comment]
Sorry for opening a duplicate issue at  https://github.com/lxde/pcmanfm-qt/issues/563 -- I'd forgotten about this page. Please follow that issue instead of this. Closing.
