### ISSUE TITLE
Terminal termite isn’t known

### ISSUE THREAD

**Issue by Markus00000** [lxde/pcmanfm-qt#392]
>WARNING **: terminal termite isn't known, consider report it to LibFM developers

https://github.com/thestinger/termite

*PCManFM 0.11.0 (also applies to PCManFM 1.2.4)*

**Comment by agaida** [comment]
terminal termite is known - please check your libfm version. Get the sources an look into data/terminals.list. You should find:
```
[termite]
open_arg=-e
noclose_arg=--hold -e
desktop_id=termite.desktop
```
