### ISSUE TITLE
Rename "close next tabs" to "close right tabs"

### ISSUE THREAD

**Issue by stefonarch** [lxde/pcmanfm-qt#393]
as subject, I recently saw that "close right/left tabs" got replaced by "close previous/next tabs" right-clicking the tab title. It closes actually all right tabs, not next tabs.

In the code and translations are still present "actionsCloseLeft" and "actionCloseRight" but I don't see them anywhere anymore.

**Comment by tsujan** [comment]
"next" means "right" for LTR layouts; doesn't it?

"right" and "left" are replaced with "next" and "previous" to support RTL layouts too.

**Comment by stefonarch** [comment]
I didn't  think of that, true. But by reading "next "  one does not understand which tabs actually get closed, could mean as well only the left one and the right one together. So maybe add a comment for translaters, in arabic, hebrew and others it would be left, for all others right?

**Comment by tsujan** [comment]
> So maybe add a comment for translaters, in arabic, hebrew and others it would be left, for all others right?

I don't know if it's possible.

Which words do you suggest instead of "right" and "left"? I mean words that are neutral toward layout direction.

**Comment by stefonarch** [comment]
Following tabs? 

I see that commenting is done in the main .ts file:
`<message>
        <location filename="../../main-win.ui" line="746"/>
        <source>Close &amp;next tabs</source>
        <comment>This is right tabs for RTL layouts and left tabs for LTR layouts</comment>
        <translation type="unfinished"></translation>
    </message>`
it shows up as "developer comment" in qtlinguist

**Comment by tsujan** [comment]
> I see that commenting is done in the main .ts file

I don't know about translation but, for example, most (all?) "go-next" action icons are right arrows while "go-previous" icons are left arrows. So, this isn't something new. Please go to `/usr/share/icons/breeze/actions/24` and filter "next" or "previous"!

**Comment by stefonarch** [comment]
I did not notice that the icons are visibile too in the menu.
Closing.
