### ISSUE TITLE
Won't Open As Root

### ISSUE THREAD

**Issue by AcarBurak** [lxde/pcmanfm-qt#398]
Recently, on an Arch Fluxbox system (running lxqt-policykit-agent daemon and setting Qt theme by qt5ct if those matter) pcmanfm-qt (0.10.0) has started to fail opening as root.

Running `lxsu pcmanfm-qt` from the command line produces

> ** (process:5449): WARNING **: The directory '~/Templates' doesn't exist, ignoring it

though I've got ~/Templates.

Running `lxqt-sudo pcmanfm-qt` doesn't produce the above, yet it too fails to open pcmanfm-qt as root.

I can launch, for instance, qtcreator or spacefm as root without any issues.

**Comment by tsujan** [comment]
Does it also happen when you set the authentication mode to `sudo` in `gksu-properties` (belonging to libgksu)?

**Comment by AcarBurak** [comment]
I don't have libgksu and such.

**Comment by tsujan** [comment]
> I don't have libgksu and such.

Ignore it! Now I'm using my laptop with the latest LXQt and see the same problem. It's a regression because it doesn't exist with an older LXQt version on my desktop computer.

**Comment by tsujan** [comment]
The change that has caused this regression should be made in the last three months. Does anybody have a clue?

**Comment by AcarBurak** [comment]
It has appeared here at most a month ago, or more likely 1-2 weeks ago.

**Comment by tsujan** [comment]
> It has appeared here at most a month ago, or more likely 1-2 weeks ago.

Thanks! That could narrow down the search.

**Comment by tsujan** [comment]
This issue isn't in pcmanfm-qt or libfm-qt. On an LXQt from 3 months ago, I upgraded *only* libfm-qt and pcmanfm-qt to their latest github versions and pcmanfm-qt opened as root correctly.

Since the rest of the system is up-to-date here, another LXQt component may have caused this issue but I can't see how. @palinek, @paulolieuthier, @luis-pereira, any idea?

**Comment by tsujan** [comment]
Never mind! Found the cause: it was Arch itself!

@AcarBurak, please see if reinstallarion of dbus fixes the problem! It did on both of my Manajro systems. (The above-mentioned experiment was done under Debian.)

**Comment by palinek** [comment]
It may be somehow connected to some preserved environment.... back then, I needed to following "hack" -> https://github.com/lxde/lxqt-sudo/commit/dd8903d630d5f9568727df70d81768345b31ad9a for pcmanfm-qt

**Comment by tsujan** [comment]
@palinek, thanks for your reply!
It happened with `sudo` and `kdesu` too. When I saw that konsole couldn't be opened as root either, I became suspicious of dbus. There has been a change in Arch's dbus that can cause such issues.

**Comment by agaida** [comment]
hmm - i don't have these problems with the latest git, so i suspect a problem outside of the code.

**Comment by tsujan** [comment]
> hmm - i don't have these problems with the latest git, so i suspect a problem outside of the code.

I agree.

**Comment by AcarBurak** [comment]
Reinstalling dbus didn't solve the issue, but launching it by

`lxsu dbus-launch pcmanfm-qt
`

solves.

**Comment by stefonarch** [comment]
Here on arch pcmanfm-qt is the very only application which does not start with lxsudo (or kdesu), other qt filemanager like qtfm do. Sure this is not in the code?

**Comment by tsujan** [comment]
> Sure this is not in the code?

On Manjaro (whose packages are mostly those of Arch), I have no problem. Please consider the fact that some apps -- like pcmanfm-qt -- need dbus support to run as root!

**Comment by Myrddin-Wyllt** [comment]
dbus-x11 from the AUR is the simplest solution in Arch distros, but It's a bit behind compared to Arch's dbus (one could edit the pkgbuild during install and modernize it fairly easily). After installing dbus-x11 on Manjaro, I didn't have the issue (on Manjaro, dbus-x11 is a package with the latest version).
I believe the relevant compilation flag is --enable-x11-autolaunch. Not sure on that though.

@ghost is correct that dbus-launch solves the issue without having to alter dbus installations.

Using an alias including dbus-launch for specific applications could work, but is a bit tedious.
