### ISSUE TITLE
Can not open as root from user X session

### ISSUE THREAD

**Issue by theredbaron1834** [lxde/pcmanfm-qt#402]
So, it seems that at least on Arch running LXQT you can not get pcmanfm-qt to run as root, from within a user X session (on both a fresh installed laptop and a old desktop install). IE: I log in as my user from SDDM, and tried to launch pcmanfm-qt as root and it fails. I have tried gksu (using both sudo and su), sudo, su, lxqt-sudo, kdesu, and kdesudo, both from the cli and via open as root. They all do the same thing, as soon as admin is given, it silently fails. Plus, I have no idea how to check pcmanfm-qt logs either (where would they be?). 

The weird thing is that I can launch it if I am logged into a root from SDDM. Thus I thought maybe it was some weird coexisting bug, but I KILLed the user pcmanfm-qt, and tried running it again, to no effect. 

Not sure what other info you might need/want, except maybe distro info. 

I am currently on Arch, fresh install, fully updated. 

    pcmanfm-qt --version
    pcmanfm-qt 0.11.1

    uname -a
    Linux Arch-Pavilion 4.7.5-1-ARCH #1 SMP PREEMPT Sat Sep 24 13:04:22 CEST 2016 x86_64 GNU/Linux

    sudo --version
    Sudo version 1.8.18
    Sudoers policy plugin version 1.8.18
    Sudoers file grammar version 45
    Sudoers I/O plugin version 1.8.18

**Comment by tsujan** [comment]
I had the same problem with pcmanfm-qt, konsole and some other apps 2 months ago. The problem was fixed by reinstalling dbus-x11 under Manjaro.

**Comment by theredbaron1834** [comment]
And that worked, thanks tsujan.

Is dbus-x11 depreciated? It is no longer in the mainline Arch repos, installed it via the AUR. Or it is just a "weird" thing, that not many people need?

**Comment by agaida** [comment]
https://lists.debian.org/debian-devel/2016/08/msg00554.html - the background section of the bug might be worth reading - and it is distribution agnostic - so one should get a dbus user session i guess. No clue what is needed to achive this in Arch

**Comment by tsujan** [comment]
> Is dbus-x11 depreciated?

Arch and , as a consequence, Manjaro had a dbus transition. Something may have gone wrong during that transition but now everything seems OK. As for dbus-x11, it is in Manjaro's repos. I don't know about Arch but everything that happens there, will happen in Manjaro sooner or later. What you've observed may be related to the conflict between dbus and dbus-x11.
