### ISSUE TITLE
pcmanfm-qt depends on gvfs for many fonctionalities

### ISSUE THREAD

**Issue by thomaspierson** [lxde/pcmanfm-qt#405]
Hi there,

I'm a new lxqt user and I'm trying to use lxqt without using the half of gnome libs.
For example I'm not able to mount a usb device or any other devices/shares with pcmanfm-qt without gvfs. And gvfs depends on many gnome stuffs.

Is it plan to implement a more independent volume backend?

Cheers

**Comment by tsujan** [comment]
Hi,

pcmanfm-qt depends on GLib (through libfm) and uses gvfs for mounting, among other jobs. gvfs doesn't depend on Gnome.

**Comment by tsujan** [comment]
Previously, I believed that moving away from GLib was a good option. Now, (being convinced by @PCMan's arguments) I think that using the potentials of both Qt and GLib may be a better option.

**Comment by pmattern** [comment]
Also, gvfs does necessarily pull GNOME stuff. E. g. on Arch Linux gvfs is working flawlessly without a single bit of GNOME itself.
Care to let us know which OS you're running?

**Comment by thomaspierson** [comment]
I use Debian. But I just take a look at the gvfs Arch package depends and it seems there are a lot of depends with «gnome» in name or description… Maybe «a single bit of GNOME itself» is a bit strong or I miss something?

**Comment by tsujan** [comment]
These are gvfs dependencies in Arch: `avahi dconf fuse libarchive libcdio-paranoia libsoup udisks2 libsecret libbluray libgudev gcr psmisc`. It's in the Gnome group but that's just a name, not a dependency.. Debian isn't different.

**Comment by PCMan** [comment]
Debian installs unnecessary packages as dependencies for years.
It's a "feature", not a bug.
Try apt-get install --no-install-recommends.
This will install true dependencies without other recommended ones.
Gvfs is quite modular. Just install whatever you need.
By default backend plugins for sftp,mtp,  smb, etc. are not installed.

**Comment by thomaspierson** [comment]
> It's in the Gnome group but that's just a name, not a dependency.. Debian isn't different.

@tsujan Ok, for me it's not just names but libraries developed by the Gnome team but maybe it's just a question of point of view.

> Debian installs unnecessary packages as dependencies for years.

@PCMan I maintain some packages in Debian and I choose very carefully the recommends and suggested non-strict dependencies. But ok… just forget the evil Debian maintainers for this time. I was just talking about the fact that pcmanfm-qt needs gvfs and some gnome libraries to mount a usb stick.

And in fact maybe you can close this issue if its ok for everyone if pcmanfm-qt depends on gvfs and its libs for some functionalities. So please do so.
I don't want make more noise here. :)

Cheers

**Comment by tsujan** [comment]
> @tsujan Ok, for me it's not just names but libraries developed by the Gnome team...

Yes, it's developed by the Gnome team but it does not *depend* on Gnome. The Gnome team develops GLib too, which is an essential part of every Linux system.

That being said, I (may) understand your reaction to the word "Gnome" but here isn't a place for discussing such matters.
