### ISSUE TITLE
pcmanfm-qt --desktop shows white dot while moving an icon

### ISSUE THREAD

**Issue by alex3kov** [lxde/pcmanfm-qt#410]
This is a very small glitch, but still:  

This is upper left corner of a desktop when I'm not doing anything with it:
![Static](http://i.imgur.com/m7WOzOC.png)

This is when icon is being moved, there's a small white dot in the corner (1 pixel probably):  
![Moving](http://i.imgur.com/km0X3Hk.png)  

pcmanfm-qt 0.11.1

**Comment by tsujan** [comment]
I can't see that microscopic dot here but even if it exists, it can't be related to the program itself.

**Comment by alex3kov** [comment]
> I can't see that microscopic dot here but even if it exists

Click on it - you'll see it against dark background.  
> it can't be related to the program itself.

Why? Only `pcmanfm-qt --desktop` manages icons and background of my desktop.

**Comment by tsujan** [comment]
>  you'll see it against dark background.

I'd chosen a dark bg to test: no change with DND.

> Only pcmanfm-qt --desktop manages icons and background of my desktop.

And it has no code that can create a dot on DND.

I think the dot you see is created by WM and/or compositor that you use. Here, I use kwin (composited).
