### ISSUE TITLE
pcmanfm-qt: fm_file_info_ref()

### ISSUE THREAD

**Issue by Sniperq2** [lxde/pcmanfm-qt#412]
[New LWP 10265]
[New LWP 10275]
[New LWP 10312]
[New LWP 10315]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `pcmanfm-qt --desktop --profile=lxqt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  fm_file_info_ref (fi=0x0) at base/fm-file-info.c:866
866	base/fm-file-info.c: No such file or directory.
[Current thread is 1 (Thread 0x7f3981159900 (LWP 10265))]

Thread 1 (Thread 0x7f3981159900 (LWP 10265)):
#0  fm_file_info_ref (fi=0x0) at base/fm-file-info.c:866
No locals.
#1  0x00007f397fa11c72 in _fetch_file_info_for_shortcut (target=target@entry=0x7f3954005610 "trash:/", ctx=ctx@entry=0x7f394c001930, launcher=launcher@entry=0x7f3981099020 <Fm::FileLauncher::funcs>, user_data=user_data@entry=0x564a5eb63638) at base/fm-file-launcher.c:146
        job = 0x564a5eb30040
        data = {ctx = 0x7f394c001930, launcher = 0x7f3981099020 <Fm::FileLauncher::funcs>, user_data = 0x564a5eb63638}
        fi = 0x0
        path = <optimized out>
#2  0x00007f397fa1209c in fm_launch_files (ctx=0x7f394c001930, file_infos=file_infos@entry=0x564a5ecf8760, launcher=launcher@entry=0x7f3981099020 <Fm::FileLauncher::funcs>, user_data=user_data@entry=0x564a5eb63638) at base/fm-file-launcher.c:262
        path = <optimized out>
        mime_type = 0x0
        fis = <optimized out>
        filename = <optimized out>
        scheme = <optimized out>
        target = 0x7f3954005610 "trash:/"
        l = 0x564a5ecf8760
        hash = 0x564a5ecf91e0
        folders = 0x0
        fi = <optimized out>
        targets = 0x0
        err = 0x0
        app = <optimized out>
        type = 0x564a5ecf8760 " X"
#3  0x00007f3980e3e33a in Fm::FileLauncher::launchFiles (this=0x564a5eb63638, parent=parent@entry=0x0, file_infos=file_infos@entry=0x564a5ecf8760) at /usr/src/debug/libfm-qt-0.11.1/src/filelauncher.cpp:50
        context = 0x7f394c001930
        ret = <optimized out>
#4  0x00007f3980e45c95 in Fm::FolderView::onFileClicked (this=0x564a5eb63500, type=<optimized out>, fileInfo=<optimized out>) at /usr/src/debug/libfm-qt-0.11.1/src/folderview.cpp:997
        files = 0x564a5ecf8760
#5  0x00007f397feab326 in QtPrivate::QSlotObjectBase::call (a=0x7ffc72221f30, r=0x564a5eb63500, this=<optimized out>) at ../../src/corelib/kernel/qobject_impl.h:130
No locals.
#6  QMetaObject::activate (sender=sender@entry=0x564a5eb63500, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7ffc72221f30) at kernel/qobject.cpp:3723
        obj = {d = 0x564a5eb68de0}
        receiver = 0x564a5eb63500
        receiverInSameThread = <optimized out>
        sw = {receiver = 0x564a5eb63500, previousSender = 0x7ffc72222070, currentSender = {sender = 0x564a5eb63500, signal = 7, ref = 1}, switched = true}
        c = 0x564a5eb12600
        last = 0x564a5eb12600
        locker = {val = 139884938157920}
        connectionLists = {connectionLists = 0x564a5ebaa270}
        list = 0x564a5eb09eb8
        currentThreadId = 0x7f3981159900
        signal_index = 7
        empty_argv = {0x0}
#7  0x00007f397feab8b7 in QMetaObject::activate (sender=sender@entry=0x564a5eb63500, m=m@entry=0x7f3981095980 <Fm::FolderView::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7ffc72221f30) at kernel/qobject.cpp:3602
No locals.
#8  0x00007f3980e76627 in Fm::FolderView::clicked (this=this@entry=0x564a5eb63500, _t1=<optimized out>, _t1@entry=0, _t2=<optimized out>, _t2@entry=0x7f3954005820) at /usr/src/debug/libfm-qt-0.11.1/x86_64-redhat-linux-gnu/src/moc_folderview.cpp:220
        _a = {0x0, 0x7ffc72221f2c, 0x7ffc72221f20}
#9  0x00007f3980e438ad in Fm::FolderView::onItemActivated (this=0x564a5eb63500, index=...) at /usr/src/debug/libfm-qt-0.11.1/src/folderview.cpp:423
        data = {d = {data = {c = 32 ' ', uc = 32 ' ', s = 22560, sc = 32 ' ', us = 22560, i = 1409308704, u = 1409308704, l = 139884199172128, ul = 139884199172128, b = 32, d = 6.9111977206962985e-310, f = 2.20493722e+12, real = 6.9111977206962985e-310, ll = 139884199172128, ull = 139884199172128, o = 0x7f3954005820, ptr = 0x7f3954005820, shared = 0x7f3954005820}, type = 31, is_shared = 0, is_null = 0}}
#10 0x00007f3980e46f00 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QModelIndex const&>, void, void (Fm::FolderView::*)(QModelIndex)>::call (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:507
No locals.
#11 QtPrivate::FunctionPointer<void (Fm::FolderView::*)(QModelIndex)>::call<QtPrivate::List<QModelIndex const&>, void> (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:526
No locals.
#12 QtPrivate::QSlotObject<void (Fm::FolderView::*)(QModelIndex), QtPrivate::List<QModelIndex const&>, void>::impl (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt5/QtCore/qobject_impl.h:149
        which = 1
        ret = <optimized out>
        a = <optimized out>
        this_ = <optimized out>
        r = <optimized out>
#13 0x00007f397feab326 in QtPrivate::QSlotObjectBase::call (a=0x7ffc722220e0, r=0x564a5eb63500, this=<optimized out>) at ../../src/corelib/kernel/qobject_impl.h:130
No locals.
#14 QMetaObject::activate (sender=0x564a5eb62360, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7ffc722220e0) at kernel/qobject.cpp:3723
        obj = {d = 0x564a5eb67c50}
        receiver = 0x564a5eb63500
        receiverInSameThread = <optimized out>
        sw = {receiver = 0x564a5eb63500, previousSender = 0x0, currentSender = {sender = 0x564a5eb62360, signal = 15, ref = 1}, switched = true}
        c = 0x564a5eb68210
        last = 0x564a5eb68210
        locker = {val = 139884938157600}
        connectionLists = {connectionLists = 0x564a5eb679a0}
        list = 0x564a5eb68368
        currentThreadId = 0x7f3981159900
        signal_index = 15
        empty_argv = {0x0}
#15 0x00007f397feab8b7 in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x7f3981095940 <Fm::FolderViewListView::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7ffc722220e0) at kernel/qobject.cpp:3602
No locals.
#16 0x00007f3980e76742 in Fm::FolderViewListView::activatedFiltered (this=<optimized out>, _t1=...) at /usr/src/debug/libfm-qt-0.11.1/x86_64-redhat-linux-gnu/src/moc_folderview_p.cpp:135
        _a = {0x0, 0x564a5ecfe0f0}
#17 0x00007f397feab326 in QtPrivate::QSlotObjectBase::call (a=0x7ffc72222210, r=0x564a5eb62360, this=<optimized out>) at ../../src/corelib/kernel/qobject_impl.h:130
No locals.
#18 QMetaObject::activate (sender=sender@entry=0x564a5eb62360, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7ffc72222210) at kernel/qobject.cpp:3723
        obj = {d = 0x564a5eb67800}
        receiver = 0x564a5eb62360
        receiverInSameThread = <optimized out>
        sw = {receiver = 0x564a5eb62360, previousSender = 0x0, currentSender = {sender = 0x564a5eb62360, signal = 10, ref = 1}, switched = true}
        c = 0x564a5eb68060
        last = 0x564a5eb68060
        locker = {val = 139884938157600}
        connectionLists = {connectionLists = 0x564a5eb679a0}
        list = 0x564a5eb68318
        currentThreadId = 0x7f3981159900
        signal_index = 10
        empty_argv = {0x0}
#19 0x00007f397feab8b7 in QMetaObject::activate (sender=sender@entry=0x564a5eb62360, m=m@entry=0x7f3980bc3460 <QAbstractItemView::staticMetaObject>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7ffc72222210) at kernel/qobject.cpp:3602
No locals.
#20 0x00007f39809154e5 in QAbstractItemView::activated (this=this@entry=0x564a5eb62360, _t1=...) at .moc/moc_qabstractitemview.cpp:660
        _a = {0x0, 0x564a5ecfe0f0}
#21 0x00007f3980922b91 in QAbstractItemView::mouseDoubleClickEvent (this=this@entry=0x564a5eb62360, event=event@entry=0x7ffc72222950) at itemviews/qabstractitemview.cpp:1954
        index = {r = 4, c = 0, i = 94877416175168, m = 0x564a5eb47b80}
        persistent = {d = 0x564a5ecfe0f0}
#22 0x00007f3980e46447 in Fm::FolderViewListView::mouseDoubleClickEvent (this=0x564a5eb62360, event=0x7ffc72222950) at /usr/src/debug/libfm-qt-0.11.1/src/folderview.cpp:169
        activationWasAllowed = true
#23 0x00007f3980714488 in QWidget::event (this=this@entry=0x564a5eb62360, event=event@entry=0x7ffc72222950) at kernel/qwidget.cpp:8782
No locals.
#24 0x00007f39807fb8ae in QFrame::event (this=0x564a5eb62360, e=0x7ffc72222950) at widgets/qframe.cpp:550
        result = <optimized out>
#25 0x00007f39809227b3 in QAbstractItemView::viewportEvent (this=0x564a5eb62360, event=0x7ffc72222950) at itemviews/qabstractitemview.cpp:1745
No locals.
#26 0x00007f397fe83f12 in QCoreApplicationPrivate::sendThroughObjectEventFilters (receiver=0x564a5eaea580, event=0x7ffc72222950) at kernel/qcoreapplication.cpp:1099
        obj = <optimized out>
        i = 3
#27 0x00007f39806cc945 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x564a5eaea580, e=0x7ffc72222950) at kernel/qapplication.cpp:3795
No locals.
#28 0x00007f39806d4fcd in QApplication::notify (this=<optimized out>, receiver=0x564a5eaea580, e=0x7ffc72222950) at kernel/qapplication.cpp:3273
        res = false
#29 0x00007f397fe8412a in QCoreApplication::notifyInternal2 (receiver=0x564a5eaea580, event=0x7ffc72222950) at kernel/qcoreapplication.cpp:988
        selfRequired = true
        result = false
        cbdata = {0x564a5eaea580, 0x7ffc72222950, 0x7ffc7222279f}
        d = <optimized out>
        threadData = 0x564a5ea9e620
        scopeLevelCounter = {threadData = 0x564a5ea9e620}
#30 0x00007f39806d365d in QApplicationPrivate::sendMouseEvent (receiver=0x564a5eaea580, event=0x7ffc72222950, alienWidget=0x564a5eaea580, nativeWidget=0x564a5eb63500, buttonDown=<optimized out>, lastMouseReceiver=..., spontaneous=true) at ../../src/corelib/kernel/qcoreapplication.h:231
        receiverGuard = {wp = {d = 0x564a5ecee340, value = 0x564a5eaea580}}
        nativeGuard = {wp = {d = 0x564a5eb685f0, value = 0x564a5eb63500}}
        alienGuard = {wp = {d = 0x564a5ecee340, value = 0x564a5eaea580}}
        activePopupWidget = {wp = {d = 0x0, value = 0x0}}
        widgetUnderMouse = <optimized out>
        wasLeaveAfterRelease = true
        result = <optimized out>
#31 0x00007f398072ddd0 in QWidgetWindow::handleMouseEvent (this=this@entry=0x564a5eaec470, event=event@entry=0x7ffc72222df0) at kernel/qwidgetwindow.cpp:613
        contextMenuTrigger = QEvent::MouseButtonPress
        widget = 0x564a5eaea580
        mapped = {xp = 64, yp = 461}
        receiver = 0x564a5eaea580
#32 0x00007f3980730603 in QWidgetWindow::event (this=0x564a5eaec470, event=0x7ffc72222df0) at kernel/qwidgetwindow.cpp:239
No locals.
#33 0x00007f39806cc96c in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x564a5eaec470, e=0x7ffc72222df0) at kernel/qapplication.cpp:3799
No locals.
#34 0x00007f39806d4111 in QApplication::notify (this=0x7ffc722231a0, receiver=0x564a5eaec470, e=0x7ffc72222df0) at kernel/qapplication.cpp:3556
        res = false
#35 0x00007f397fe8412a in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x564a5eaec470, event=event@entry=0x7ffc72222df0) at kernel/qcoreapplication.cpp:988
        selfRequired = true
        result = false
        cbdata = {0x564a5eaec470, 0x7ffc72222df0, 0x7ffc72222c3f}
        d = <optimized out>
        threadData = 0x564a5ea9e620
        scopeLevelCounter = {threadData = 0x564a5ea9e620}
#36 0x00007f39801c2ba8 in QCoreApplication::sendSpontaneousEvent (event=0x7ffc72222df0, receiver=0x564a5eaec470) at ../../src/corelib/kernel/qcoreapplication.h:234
No locals.
#37 QGuiApplicationPrivate::processMouseEvent (e=0x564a5ed437d0) at kernel/qguiapplication.cpp:1952
        doubleClickType = QEvent::MouseButtonDblClick
        dblClickEvent = {<QInputEvent> = {<QEvent> = {_vptr.QEvent = 0x7f398055ccb8 <vtable for QMouseEvent+16>, static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7f3980042780 <qt_meta_stringdata_QEvent>, data = 0x7f39800421c0 <qt_meta_data_QEvent>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x0, t = 4, posted = 0, spont = 1, m_accept = 1, reserved = 0}, modState = {i = 0}, ts = 15602826}, l = {xp = 64, yp = 461}, w = {xp = 64, yp = 461}, s = {xp = 64, yp = 461}, b = Qt::LeftButton, mouseState = {i = 1}, caps = 0, velocity = {xp = 0, yp = 0}}
        type = <optimized out>
        stateChange = <optimized out>
        window = 0x564a5eaec470
        localPoint = {xp = 64, yp = 461}
        globalPoint = {xp = 64, yp = 461}
        button = Qt::LeftButton
        doubleClick = true
        frameStrut = false
        ev = {<QInputEvent> = {<QEvent> = {_vptr.QEvent = 0x7f398055ccb8 <vtable for QMouseEvent+16>, static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7f3980042780 <qt_meta_stringdata_QEvent>, data = 0x7f39800421c0 <qt_meta_data_QEvent>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x0, t = 2, posted = 0, spont = 0, m_accept = 1, reserved = 0}, modState = {i = 0}, ts = 15602826}, l = {xp = 64, yp = 461}, w = {xp = 64, yp = 461}, s = {xp = 64, yp = 461}, b = Qt::LeftButton, mouseState = {i = 1}, caps = 65536, velocity = {xp = 0, yp = 0}}
#38 0x00007f39801c4925 in QGuiApplicationPrivate::processWindowSystemEvent (e=<optimized out>) at kernel/qguiapplication.cpp:1693
No locals.
#39 0x00007f39801a57cb in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at kernel/qwindowsysteminterface.cpp:654
        nevents = 1
#40 0x00007f396f3dec60 in userEventSourceDispatch (source=<optimized out>) at eventdispatchers/qeventdispatcher_glib.cpp:76
        userEventSource = <optimized out>
        dispatcher = <optimized out>
#41 0x00007f397ef49e42 in g_main_dispatch (context=0x7f39640016f0) at gmain.c:3203
        dispatch = 0x7f396f3dec50 <userEventSourceDispatch(GSource*, GSourceFunc, gpointer)>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x564a5eb0d930
        current = 0x564a5eb36500
        i = 1
#42 g_main_context_dispatch (context=context@entry=0x7f39640016f0) at gmain.c:3856
No locals.
#43 0x00007f397ef4a1c0 in g_main_context_iterate (context=context@entry=0x7f39640016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3929
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = 5
        allocated_nfds = 5
        fds = <optimized out>
#44 0x00007f397ef4a26c in g_main_context_iteration (context=0x7f39640016f0, may_block=may_block@entry=1) at gmain.c:3990

Timeout exceeded: 240 seconds, killing gdb.
Looks like gdb hung while generating backtrace.
This may be a bug in gdb. Consider submitting a bug report to gdb developers.
Please attach coredump from this crash to the bug report if you do.

**Comment by tsujan** [comment]
Which version?

**Comment by agaida** [comment]
@tsujan - we should close this one as invalid and incompleed - and i guess we know the bug and solved it. Sorry, but my glass ball, the black cat and the crow are on holliday and thake have the cauldron in their baggage too. Anyways, this will be solved with a new release of libfm - on which distribution ever - so have a look for backports soon - if no backports available, bad luck.

**Comment by agaida** [comment]
if my glass ball is right this one was: https://github.com/lxde/libfm/commit/2a537414def87ebd75024a74030e60582cd78c45

**Comment by tsujan** [comment]
@agaida, thanks! Yes, it should be lxde/libfm@2a53741.

On the one hand, I'm happy that more people use LXQt; on the other hand, incomplete reports can be so confusing.

**Comment by agaida** [comment]
i consider this as a downstream problem - if our guesses are right they could eventually port the patch or change the compiling options - has github some kind of bug templates available? Bugs would be more helpful if they provide a minimum of informations.

**Comment by tsujan** [comment]
> has github some kind of bug templates available?

I think the lack of such a template is a big disadvantage. I like KDE report templates: how to reproduce, which version, what's expected, etc.

**Comment by agaida** [comment]
@tsujan - glad we taöked about - https://github.com/blog/2111-issue-and-pull-request-templates :D 
Will file a bug

**Comment by tsujan** [comment]
@agaida, this is really great! All members should be consulted about the template.
