### ISSUE TITLE
A Minor Design Flaw in Path Buttons

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#414]
Even wih an elementary style like Fusion, the first path button isn't aligned with the others because it has an icon, while the others don't:

![path_buttons](https://cloud.githubusercontent.com/assets/981076/20859099/22c68224-b96a-11e6-9f5e-73442b638ee4.png)

**Comment by agaida** [comment]
GTM
![screen01](https://cloud.githubusercontent.com/assets/1162845/20860738/c919818e-b97f-11e6-8d37-41409d0f7e7a.jpg)

**Comment by tsujan** [comment]
@agaida, you meant https://github.com/lxde/libfm-qt/pull/51, didn't you?

**Comment by agaida** [comment]
yes - please merge

**Comment by tsujan** [comment]
Let's wait for @PCMan's review!
