### ISSUE TITLE
libqt-fm : QString to c string, dangling pointers

### ISSUE THREAD

**Issue by rafirafi** [lxde/pcmanfm-qt#427]
As I understand it, this is potentially problematic :
	QString().toByteArray().data()
as it only gives a pointer to a temporary QByteArray, there is no garanty the pointer will remain valid.

I remember seeing it at several places in libfm-qt, p.ex. :

project : libfm-qt
file : utilities.cpp
function : void createFileOrFolder(CreateFileType type, FmPath* parentDir, FmTemplate* templ, 
QWidget* parent) {

GFile* dest_gf = g_file_get_child(G_FILE(parent_gf), new_name.toLocal8Bit().data());
	
Sorry I didn't take the time to make a proper patch, but I thought it was worth it to point out the issue.

**Comment by tsujan** [comment]
> As I understand it, this is potentially problematic

First, thanks for your attention!

> there is no garanty the pointer will remain valid

We get the string and use it in `g_file_get_child()`. I don't see any problem here. It's better to use `constData()` though, as in https://github.com/lxde/libfm-qt/pull/55.

**Comment by rafirafi** [comment]
The issue is not with g_file_get_child but with : 
> QString.toByteArray().toCharPointer()

It's like this :

> QString string("data");
char *ptr = nullptr;
{
	QByteArray tmp = string.toByteArray(); // toLocal8Bit(), toUtf8() ...
	ptr = tmp.data();
} // out of scope, tmp is destroyed, and ptr is not valid anymore

=> here ptr is not valid, because the array returned by toLocal8Bit() (p.ex.) is already out of scope.

This is the same as:

> char *ptr = currentPrefix_.toLocal8Bit().constData();

=> here ptr is not valid, because the QbyteArray returned by toLocal8Bit() is already destroyed, and constData() points to the internal buffer of this QByteArray.

I reported it because this leads to annoying bugs, 99% of the time the memory is not reused and everything seems fine.

This is what I found on my local (out-of-date) copy of libfm-qt.

> libfm-qt-master/src$ find . -type f -exec grep -n '().data()\|().constData()' /dev/null {} +
./proxyfoldermodel.cpp:237:  // qDebug("ProxyFolderModel::onThumbnailLoaded: %d, %s", size, item->displayName.toUtf8().data());
./utilities.cpp:139:  GFile* dest = g_file_get_child(G_FILE(parent_gf), new_name.toLocal8Bit().data());
./utilities.cpp:196:  GFile* dest_gf = g_file_get_child(G_FILE(parent_gf), new_name.toLocal8Bit().data());
./filepropsdialog.cpp:442:      GFile* dest = g_file_get_child(G_FILE(parent_gf), new_name.toLocal8Bit().data());
./fileoperation.cpp:148:    *new_name = g_strdup(newName.toUtf8().constData());
./placesview.cpp:265:  fm_bookmarks_rename(bookmarks, bookmarkItem, item->text().toUtf8().constData());
./foldermodel.cpp:500:        // qDebug("thumbnail loaded for: %s, size: %d", item.displayName.toUtf8().constData(), size);
./foldermodel.cpp:534:    // qDebug("FolderModel::thumbnailFromIndex: %d, %s", thumbnail->status, item->displayName.toUtf8().data());
./filesearchdialog.cpp:60:      fm_search_add_dir(search, item->text().toLocal8Bit().constData());
./filesearchdialog.cpp:65:    fm_search_set_name_patterns(search, ui->namePatterns->text().toUtf8().constData());
./filesearchdialog.cpp:69:    fm_search_set_content_pattern(search, ui->contentPattern->text().toUtf8().constData());
./filesearchdialog.cpp:111:      fm_search_set_max_mtime(search, ui->maxTime->date().toString(QStringLiteral("yyyy-MM-dd")).toUtf8().constData());
./filesearchdialog.cpp:114:      fm_search_set_min_mtime(search, ui->minTime->date().toString(QStringLiteral("yyyy-MM-dd")).toUtf8().constData());
./pathedit.cpp:171:  job->dirName = fm_file_new_for_commandline_arg(currentPrefix_.toLocal8Bit().constData());
./pathedit.cpp:202:      // qDebug("%s", it->toUtf8().constData());

**Comment by tsujan** [comment]
> char *ptr = currentPrefix_.toLocal8Bit().constData();
> here ptr is not valid, because the QbyteArray returned by toLocal8Bit() is already destroyed

Destroyed by what? currentPrefix_ is a QString and `QString::toLocal8Bit()` returns its local 8-bit representation as a QByteArray. Why that QByteArray should be destroyed immediately?

Have you encountered a crash? A clean backtrace? The way of reproducing it?

**Comment by rafirafi** [comment]
In my example this is problematic QByteArray is destroyed after the ';' 
... but this is never used like this in libfm-qt, always as a function argument which is ok.
My mistake and sorry for the noise.
