### ISSUE TITLE
Path Editor disappears after entry

### ISSUE THREAD

**Issue by ferronrsmith** [lxde/pcmanfm-qt#437]
Having an issue where the path editor doesn't allow for any further editing. e.g. of the issue is attached  

![ezgif com-50b84005b2](https://cloud.githubusercontent.com/assets/159764/21520299/c5630ba2-ccc9-11e6-80b6-58adb721b120.gif)

os : Ubuntu 16.04.1 LTS
qt: 5.5

**Comment by tsujan** [comment]
That's the way the path bar works when path buttons are selected under View → Path Bar: the editor disappears on losing focus. If you want it to be always shown, check View → Path → Location!

**Comment by ferronrsmith** [comment]
Actually I don't agree with you.

The path buttons should reappear after entry, currently it doesn't.


**Before**
![2016-12-28-095703_3520x1080_scrot](https://cloud.githubusercontent.com/assets/159764/21523397/456f58b8-cce4-11e6-8c0d-0226da0217ea.png)

**After**
![2016-12-28-095714_3520x1080_scrot](https://cloud.githubusercontent.com/assets/159764/21523398/456fa2d2-cce4-11e6-8b51-4a9e26ae1a69.png)

**Comment by ferronrsmith** [comment]
If I switch to :  View → Path → Location!
 View → Path → Path Buttons! it comes back. That's a bug.

**Comment by tsujan** [comment]
> If I switch to : View → Path → Location, View → Path → Path Buttons! it comes back.

If you switch to View → Path → Location, only the path-edit will be shown. If you go back to View → Path → Path Buttons, path buttons will be shown and path edit will appear only *temporarily*, when it's being edited by clicking on the bar or by right clicking on a button and selecting "Edit Path".

**Comment by tsujan** [comment]
Oh, your screenshot is strange! It shouldn't be so. That may be an upstream problem because I can't reproduce it here: path buttons are all shown after editing is finished. Which Qt theme do you use?

**Comment by ferronrsmith** [comment]
My issue is when I exit the edit mode it should render the **path buttons** properly. As you can see above, it's not doing that. The Path button shrinks and the only thing visible in my case in the drive. See the image above

**Comment by agaida** [comment]
for me it works™ as expected -- so the question is as with any other bug: distribution, version and so on

**Comment by agaida** [comment]
@tsujan - do you rememer that libfm bug with the strange assets - can it be that an old libfm jumps in?

**Comment by ferronrsmith** [comment]
I'm using the `oxygen` theme. I build `pcmanfm-qt` off of the latest master branch. This issue is recent though. Didn't happen a few weeks back and I have been using that theme for 2 years, so I know it's something upstream.

**Comment by tsujan** [comment]
OK! Very sorry for misunderstanding your report!

As I said above, I can't reproduce the problem here. Something should be wrong with your pcmanfm-qt and/or libfm-qt installation. It would be great if you could compile the latest libfm-qt *and* pcmanfm-qt from github and test again.

**Comment by tsujan** [comment]
By the way, I meant *downstream* above but as you compile LXQt yourself, it isn't relevant anymore.

**Comment by tsujan** [comment]
@agaida 
Which libfm bug do you mean? Or do you mean libfm-qt?

**Comment by agaida** [comment]
https://github.com/lxde/pcmanfm-qt/issues/368 -- but it is only a wild guess (or it might be a similar thing)

**Comment by tsujan** [comment]
> #368 -- but it is only a wild guess (or it might be a similar thing)

No, I don't think it can have any effect on this. I guess this may be about wrong compilation. Let's wait for @ferronrsmith to recompile the latest sources.

**Comment by agaida** [comment]
you are probably right about it - but this one came to my mind - and it was in a place we hadn't in mind first place.

**Comment by tsujan** [comment]
@agaida I remember the surprise you and me had at #368 ;) You found a workaround and @palinek found the root cause...

**Comment by agaida** [comment]
and i guess i will set up a lubuntu 16.04 later - i know, there is a special word for it - in Germany we have "§168 StGB: Störung der Totenruhe"

**Comment by tsujan** [comment]
> in Germany we have "§168 StGB: Störung der Totenruhe"

:)

**Comment by tsujan** [comment]
> EDIT: In other words - imho it isn't the very best idea to compile the current code with an outdated Qt (with long fixed bugs) and maybe other outdated components.

That may also be the cause. Qt-5.5 *is* outdated. It's practically impossible to reread such a volume of code to know if it's OK with an old version of Qt5. Qt-5.6 should be OK but Qt-5.7.1 is the latest stable version now.

**Comment by ferronrsmith** [comment]
same issue for me, the reason i don't think it's a Qt issue is because of the following :


**This is how it is at default**
![2016-12-28-095703_3520x1080_scrot](https://cloud.githubusercontent.com/assets/159764/21523397/456f58b8-cce4-11e6-8c0d-0226da0217ea.png)

**This is how it becomes if I try to edit**
![2016-12-28-095714_3520x1080_scrot](https://cloud.githubusercontent.com/assets/159764/21523398/456fa2d2-cce4-11e6-8b51-4a9e26ae1a69.png)

If I do the following :

View → Path → Location (switch to location)
View → Path → Path Buttons (then switch back, it re-renders correctly)

**After switching from location -> path buttons re-rendering is done properly**
![2016-12-28-095703_3520x1080_scrot](https://cloud.githubusercontent.com/assets/159764/21523397/456f58b8-cce4-11e6-8c0d-0226da0217ea.png)

Something happens after you enter the location bar, then **fade** that prevents proper re-rendering.

**Comment by ferronrsmith** [comment]
I will give QT 5.7.1 a try.

**Comment by ferronrsmith** [comment]
Thanks guys! Tried QT 5.7.1 and it's working :)

**Comment by agaida** [comment]
Glad it works for you :)

**Comment by tsujan** [comment]
I'm curious what was the problem in Qt-5.5 but I guess we'll never know. Anyway, glad to know that your problem is fixed :)
