### ISSUE TITLE
Deleting folders/files sometimes crashes pcman

### ISSUE THREAD

**Issue by AcarBurak** [lxde/pcmanfm-qt#451]
Deleting folders/files sometimes crashes pcman (0.11.3 and 0.11.2 before that) on an Arch/Fluxbox system Qt theme set by qt5ct. I've seen the same issue with pcman-gtk as well.

**Comment by tsujan** [comment]
Without a backrace, nothing could be done.

If you find a backtrace that's included in https://github.com/lxde/pcmanfm-qt/issues/397, please close this and add a comment there!
