### ISSUE TITLE
custom actions: topic "Compress" misplaced in context menu

### ISSUE THREAD

**Issue by pmattern** [lxde/pcmanfm-qt#452]
When [custom actions](http://www.nautilus-actions.org/?q=node/377) are used item "Compress" is placed in the section of the context menu summarizing the custom actions
![libfm-qt_custom-action-position-compress_with-actions](https://cloud.githubusercontent.com/assets/9860801/22858687/74b1baae-f0c4-11e6-8279-fcd48a2aa89d.png)
while it's in fact a topic that belongs to the default context menu
![libfm-qt_custom-action-position-compress_no-actions](https://cloud.githubusercontent.com/assets/9860801/22858690/7e919f58-f0c4-11e6-98e0-dd4654c4835a.png)
and as such has nothing to do with the custom actions.

lxde/libfm-qt@e3e2839 and lxde/pcmanfm-qt@1d38bbd on Arch Linux.

**Comment by tsujan** [comment]
Yes! I've changed its place for my personal use but, as you know, PR's can't be merged for now. Added it to TODO.

**Comment by pmattern** [comment]
> [...] as you know, PR's can't be merged for now.

I guess by this you are probably referring to the massive changes introduced by lxde/libfm-qt#63 and lxde/pcmanfm-qt#450 but I'm not aware of some kind of agreement that the development of those components should be stalled until these PRs are considered.
Is there any such agreement? If so I have to say this, as well as those massive PRs themselves to some degree, would be a problem with regards to an optional next minor release of LXQt which we should think about in the not too distant future IMO.

**Comment by tsujan** [comment]
A reminder for myself to fix this: Those huge changes were merged a long time ago ;)
