### ISSUE TITLE
Improve Empty trash confirmation dialog

### ISSUE THREAD

**Issue by galdralag** [lxde/pcmanfm-qt#457]
Default button should be YES when confirm deleting files like in other file managers
In pcmanfm(lxde), dolphin(kde), thunar(xfce) sequence Shift+Del,Enter delete files but it is not work in pcmanfm-qt - very annoying

**Comment by tsujan** [comment]
NO is more cautious but I'm not against changing it to YES.

BTW, I've used it for a long time and have never found it annoying, let alone "very annoying".

**Comment by pmattern** [comment]
Absolutely agree with @tsujan here. Can be considered a matter of taste, even if several other file managers are defaulting to "Yes", could be changed, but isn't a disaster right now.
Was first wondering whether the default could be implemented as an option, but this would probably be overblown.
