### ISSUE TITLE
pcmanfm-qt sometimes shows files that don't exist

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#460]
Sometimes, after the creation/deletion of files is finished due to compilation or downloading, pcmanfm-qt shows files that don't exist. They vanish after refreshing the folder, of course, but they can be very confusing.

I started to compare pcmanfm-qt with Dolphin for a while and found this difference, among others. I've never seen such a behavior in Dolphin.

**Comment by tsujan** [comment]
This may be related to `CachedFolderModel` in libfm-qt. I'm afraid that the word "annoying" can be used in this case. A file manager should never show non-existent files; otherwise, it'll defeat its purpose.

**Comment by tsujan** [comment]
I tested and apparently it wasn't caused by `CachedFolderModel`.

A way to reproduce the issue:

(1) Create two empty folders "New folder" and "New folder1" inside the same folder;
(2) Copy a file "FILE" into "New folder";
(3) Change directory into "New folder", so that you see "FILE";
(4) Go to the parent folder (where "New folder" and "New folder1" were created) again and delete "New folder";
(5) Copy "New folder1" and paste it inside the same folder but with the name "New folder";
(6) Change directory to "New folder";

After (6), I always see the non-existent file  "FILE". Sometimes it disappears after a few seconds and sometimes after reloading the folder. 

**Could anyone confirm this, please?**

**Comment by palinek** [comment]
> Could anyone confirm this, please?

Tried twice (copying the file by pcmafm-qt and by simple cp) ... but no luck with seeing the non-existent file.

(up-to-date debian testing)

**Comment by palinek** [comment]
Or are we talking here about the new c++11 rework of libfm-qt version?

**Comment by tsujan** [comment]
> Tried twice (copying the file by pcmafm-qt and by simple cp) ... but no luck with seeing the non-existent file.

Thank you!
Strange! I can reproduce it with any style (Fusion, Breeze, Kvantum,...), with or without desktop, run from its desktop file or from terminal.

> Or are we talking here about the new c++11 rework of libfm-qt version?

No! I use the latest git version.

**Comment by tsujan** [comment]
Two potential causes can be ruled out: `CachedFolderModel` and the graphics -- the latter because when I do the same thing with Dolphin, there's no non-existent file.

**Comment by tsujan** [comment]
Ah, found the cause! It's a personal patch that selects the newly created items (without which I can't use a file manager). I modified it and the problem was solved :)

**Comment by tsujan** [comment]
I reopen this because it happens without my patch too; "New folder" should just be selected before going into it.

@palinek, couldn't you reproduce the issue if you select "New folder" *before* changing directory into it (step 6)?

**Comment by palinek** [comment]
> I reopen this because it happens without my patch too; "New folder" should just be selected before going into it.

> @palinek, couldn't you reproduce the issue if you select "New folder" before changing directory into it (step 6)?

No difference. Note: I'm using double click to activate (go into the folder), so the folder is always selected when going into it.

**Comment by tsujan** [comment]
@palinek 
My last question and I won't bother you again: You select a folder before going into it and then, you go into it by double clicking. Does the statusbar text change appropriately?

**Comment by palinek** [comment]
> You select a folder before going into it and then, you go into it by double clicking. Does the statusbar text change appropriately?

Yes.

**Comment by tsujan** [comment]
OK. I don't understand why we see different things because I also tested with a git cloned source (without any extra patch).

For me, it's about `folder_.isLoaded()` returning true in `TabPage::chdir()`, so I added a simple personal workaround. I leave this issue open for a while and then, if it isn't confirmed, will close it.

**Comment by tsujan** [comment]
OK, I didn't have illusions. This is a real bug. When a folder is trashed and a new folder with the same name is created, pcmanfm-qt will see the latter as already loaded and if the directory is changed into it, its old file(s) will be shown for a short interval (which may be different for different users) until the folder is reloaded by `queue_reload()` in libfm.

Why that "short" interval is an invisible moment for some and 2-3 seconds for others, I down't know but a workaround could be an explicit calling of `folder_.reload()` inside `TabPage::chdir()`.

**Comment by tsujan** [comment]
Good news! This is fixed by @PCMan's [PR](https://github.com/lxde/libfm-qt/pull/63).

**Comment by tsujan** [comment]
Definitely fixed by https://github.com/lxde/libfm-qt/pull/63. Closing this.
