### ISSUE TITLE
mouse scroll wheel randomly stops working

### ISSUE THREAD

**Issue by gothmog123** [lxde/pcmanfm-qt#466]
Just like the title says. Some days it works fine, others I can't use the mouse wheel to scroll and need to grab the scroll bar. Is this a qt bug maybe?

**Comment by tsujan** [comment]
> Is this a qt bug maybe?

Do yo have Qt-5.8?

**Comment by gothmog123** [comment]
yes

**Comment by tsujan** [comment]
Then yes, it's a Qt bug. See https://github.com/lxde/lxqt/issues/1257. It's fixed in the next version, which may be 5.8.1 or 5.9.0.
