### ISSUE TITLE
Inline Rename

### ISSUE THREAD

**Issue by MggMuggins** [lxde/pcmanfm-qt#468]
A feature suggested in #465 but moved here; Inline Renaming of files. I've seen it in mac's finder (the implementation I like, that takes a slow double-click to rename the file), but is also included in numerous other FM's. This would be a handy feature to have for PCManFM-Qt.

**Comment by tsujan** [comment]
I have an extra reason why this should be added to pcmanfm-qt (as an option?): KWin isn't happy with the rename dialog. When a file is going to be renamed in a window while there's another window in another desktop, KWin brings that window to the current desktop.

This may be a bug in kwin or even in pcmanfm-qt but inline renaming is something that many users see as a natural way of renaming files -- although I don't ;)

**Comment by MggMuggins** [comment]
Which is of course why it should be included as an optional (although enabled by default I would think) feature. Don't want to go forcing features on people.

**Comment by tsujan** [comment]
OK, I succeeded in adding inline renaming in an easy but "lousy" way. It needs a lot of polishing and decisions should be taken about how to add it as a feature instead of replacing the current renaming. I'll work on it in my free time.

**Comment by MggMuggins** [comment]
Cool. Where can I get the source for your "lousy" implementation?

**Comment by tsujan** [comment]
I'll tell you when it's worth a PR.

**Comment by tsujan** [comment]
One of several problems I've encountered is how inline renaming should start:

(1) Double-click isn't an option (it's used to open files);
(2) Middle and right clicks are also reserved by other actions;
(3) Renaming just by selecting an item and typing is too easy and may cause problems.

I chose the shortcut `Ctrl+;` for code testing, so that dialog renaming and inline renaming could coexist.

@MggMuggins, any suggestion? Is a keyboard shortcut acceptable?

**Comment by MggMuggins** [comment]
Is it possible to use a slow double-click? That is what OSX uses and works really well. However, there would have to be something in Qt to do that, and I just don't know. 
I usually find keyboard shortcuts really annoying and a pain to use. The right-click menu would be more useful to me, if there weren't a double-click option.

**Comment by tsujan** [comment]
Even if it was a slow double click, it wouldn't be easy to use -- anyhow, there isn't any.

How a keyboard shortcut could be annoying when this is about *typing* a name?! In such cases, using mouse can be annoying.

I don't want to add yet another item to the right-click menu. I don't like to make dialog renaming and inline renaming mutually exclusive either.

**Comment by MggMuggins** [comment]
I agree that the slow double-click can be annoying. How much configuration for keyboard shortcuts is there? If there were a complete controls Dialogue, it would really reduce this kind of argument over what would be the best keystroke. You put in a Ctrl+<whatever> as default and then if I don't like it, then I can go and change it. Costumizablility is really nice...

**Comment by tsujan** [comment]
Almost done -- this time, in a clean way:

![1](https://cloud.githubusercontent.com/assets/981076/24777589/4c4486d6-1b3b-11e7-869c-fd344bfb0928.png)

After some more polishing and testing it for a day or two, I'll make a PR.

> I agree that the slow double-click can be annoying.

Who knows, maybe later it could be implemented too.

>  If there were a complete controls Dialogue

If you mean customizing shortcuts in pcmanfm-qt, it isn't implemented (yet) because most shortcuts are standard. You could open another issue for it but I think most users don't need it.

**Comment by MggMuggins** [comment]
No reason to implement that kind of customization unless it's necessary. However, if there were some configuration available (especially for actions that would commonly be bound to mouse buttons...), that would be great. I'm considering learning Qt in C++, but this program is so big and complicated I'm not sure where to start.
Btw, I love your dark theme. What OS are you running?

**Comment by tsujan** [comment]
> I'm considering learning Qt in C++, but this program is so big and complicated I'm not sure where to start.

An app like pcmanfm-qt can't be a starting point for learning Qt, especially because its core is based on GLib -- unless you have experience with GLib.

> What OS are you running?

Manjaro and Debian but the style is [here](https://github.com/tsujan/Kvantum/releases/tag/V0.10.4).

**Comment by tsujan** [comment]
Done at https://github.com/lxde/libfm-qt/pull/67.

Now, if a single file/folder is selected, the "Rename" menu-item of the right-click menu will do inline renaming. The keyboard shortcut `Ctrl+R` also exists for inline renaming of the "current" item ("current" means having keyboard focus), even when several items are selected.

Desktop needs another PR, which I'll make soon.

**Comment by tsujan** [comment]
The desktop PR is made here: https://github.com/lxde/pcmanfm-qt/pull/471.

**Comment by tsujan** [comment]
The up-to-date PR is [here](https://github.com/lxde/libfm-qt/pull/98).
