### ISSUE TITLE
Nonexistent files on Desktop with dowanloading

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#475]
This happens after https://github.com/lxde/libfm-qt/pull/63.

When a file `X` is downloaded by Qupzilla (for example) on Desktop, 3 things might happen:

(1) `X` appears on Desktop and can be deleted without problem. This is the correct behavior.

(2) `X` and `X.download` both appear on desktop. The extension `.download` is used by Qupzilla when the file is being downloaded. After the download is finished, `X.download` is removed but its icon is still on Desktop and when the user tries to delete it, he gets:
````
GLib-CRITICAL **: g_error_free: assertion 'error != NULL' failed
````
That's because the file doesn't exist. `X.download` disappears on refreshing desktop.

(3) `X` appears on Desktop but when deleted, its icon remains on Desktop. The above-mentioned message is issued on trying to delete it and it disappers on refreshing desktop.

This may depend on various factors (CPU speeed, other files on Desktop, size of `X`, connection speed,...). Qupzilla is just used for testing.

I think the cause is the unordered map in `folder.h`, which is used to keep track of files inside a folder:
````
std::unordered_map<const char*, std::shared_ptr<const FileInfo>, CStrHash, CStrEqual> files_;
````
To add elements to it, `c_str()` is used for the key while the pointer returned by `c_str()` may be invalidated easily and so, `files_` may contain invalid keys. Hence, random problems may be caused.

Once I used this instead of it:
````
std::unordered_map<const std::string, std::shared_ptr<const FileInfo>, std::hash<std::string>> files_;
````
(2) and (3) didn't occur anymore. I'll add a PR after some testing.

**Comment by agaida** [comment]
Cool, we run into this at Linuxtag in Chemnitz - but i was not able to reproduce it.

**Comment by tsujan** [comment]
@agaida 
Thanks for the confirmation. It's a random bug. I test the fix for a day or two and will make a PR if everything is fine.

**Comment by tsujan** [comment]
@agaida 
BTW, please tell me about bugs that are found by others too, even if you can't reproduce them. The code is new and may still have other hidden/random bugs.

**Comment by tsujan** [comment]
Oh, I'd written "...(1) and (3) didn't occur anymore...", while I meant (2) and (3). Corrected the report.
