### ISSUE TITLE
Copy Paths

### ISSUE THREAD

**Issue by MggMuggins** [lxde/pcmanfm-qt#485]
Apologies in advance if this is a repeat or a request for a feature that already exists, but I use the Ubuntu repository version of PCManFM-Qt, so it's of course incredibly out of date. Anyway, in regular PCManFM there is a feature in the right click menu for "Copy path(s)". This is a feature I find incredibly useful when I'm using both the shell (for actually doing stuff), and the FM for quickly and easily seeing what the structure of the filesystem is.

**Comment by tsujan** [comment]
It's OK. An updated version of pcmanfm-qt has a path-bar (containing path buttons) with a "Copy Path" on its right-click menu (in addition to "Edit Path").

**Comment by MggMuggins** [comment]
Awesome, thanks for the confirmation. Now if I can only get up-to-date builds...
