### ISSUE TITLE
Side mouse buttons should not drag files 

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#486]
Side mouse buttons currently can go back/forward through folders, which is nice. But they can also drag files, which shouldn't happen, especially because you can mess with files without noticing.

**Comment by palinek** [comment]
What version of pcmanfm-qt are you using? I can't reproduce it here with current master.

**Comment by fulalas** [comment]
I'm using Arch last build, from January 2017. This issue is easily reproducible if you try to drag a file with forward mouse button.

**Comment by palinek** [comment]
> I'm using Arch last build, from January 2017. 

Well, that's before the "huge under the hood C++11 libfm-qt" change. Please, try if it is reproducible with current master.

**Comment by fulalas** [comment]
Ok, thanks. I have to wait for a build since I'm not able to compile it at the moment. :)

**Comment by MggMuggins** [comment]
You could try AUR, but that is still building...

**Comment by fulalas** [comment]
I've just re-tested this issue with the current Git, and it's still there.

The easiest way to reproduce it is opening a new pcmanfm-qt window and clicking with mouse side button that goes forward over a file/folder. With it still pressed, if you move the mouse, you'll notice that you are dragging the icon, which isn't the expected behavior.

**Comment by palinek** [comment]
Confirmed.... (I wasn't able to reproduce it before, because my crappy mouse gives a release on forward button even on a single press :))

But this is a (wrong?) behavior of Qt -> you can try it with any "open file" dialog in Qt based app.
I believe, the cause is here -> https://github.com/qt/qtbase/blob/dev/src/widgets/itemviews/qabstractitemview.cpp#L1861 (there is a check for any pressed button). 

If built & run with the modified qt:
```diff
diff --git a/src/widgets/itemviews/qabstractitemview.cpp b/src/widgets/itemviews/qabstractitemview.cpp
index d24456edef..72715d2e7e 100644
--- a/src/widgets/itemviews/qabstractitemview.cpp
+++ b/src/widgets/itemviews/qabstractitemview.cpp
@@ -1858,7 +1858,7 @@ void QAbstractItemView::mouseMoveEvent(QMouseEvent *event)
     if (d->pressedIndex.isValid()
         && d->dragEnabled
         && (state() != DragSelectingState)
-        && (event->buttons() != Qt::NoButton)
+        && (event->buttons() & Qt::LeftButton)
         && !d->selectedDraggableIndexes().isEmpty()) {
             setState(DraggingState);
             return;
```
... the issue is gone.

But now I don't know if this is a bug of feature in Qt.

**Comment by fulalas** [comment]
@palinek, thanks for this report. I can confirm that any Qt app has this same behavior. I haven't notice it before because it's very uncommon to navigate through files inside open/save dialogs. :P

Is it possible to inherit from QAbstractItemView and reimplement mouseMoveEvent just like you did?

**Comment by fulalas** [comment]
Although maybe the better solution is to allow right mouse button too. I like Windows behavior:

1- when dragging with left button you're always moving if you're pointing the file/folder to the same unit, or copying if you're pointing to a different unit;
2- when dragging with left button +ctrl you're always copying, regarding which unit you're pointing to;
3- when dragging with left button +shift you're always moving, regarding which unit you're pointing to;
4- when dragging with right button you'll see a context menu asking what to do;

**Comment by palinek** [comment]
@fulalas you can try with lxde/libfm-qt#91
