### ISSUE TITLE
Annoying error dialog when accessing camera/smartphone through libgphoto2

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#487]
When using libgphoto2 (no matter which version), if we plug a camera/smartphone we receive the following error: 'Error initializing camera: -53: Could not claim the USB device'. This a known old bug already reported so many times, like here: https://lists.ubuntu.com/archives/lubuntu-users/2014-September/008469.html

**Comment by tsujan** [comment]
It may not be able to "claim the USB device" because gvfs-gphoto2-volume-monitor (belonging to gvfs-gphoto2) is running.

**Comment by fulalas** [comment]
Thanks, tsujan. In fact, this error doesn't forbid me to access the files. It's just annoying. Do you have any suggestion to get rid of it?

**Comment by tsujan** [comment]
> Do you have any suggestion to get rid of it?

I've never needed gphoto2 but it seems to me that `gvfs-gphoto2-volume-monitor` and `Libgphoto2` don't like each other. You could try to stop the former somehow.

Anyway, I don't think this is a pcmanfm-qt issue. I close this but feel free to add comments to or reopen it if needed.

**Comment by fulalas** [comment]
Sorry, I still don't get it. How do you access your camera/smartphone files using LXQt? Is there other way than using libgphoto2?

**Comment by tsujan** [comment]
> Sorry, I still don't get it.

I closed this because (most probably) it was about a conflict between gvfs-gphoto2-volume-monitor and Libgphoto2, not about pcmanfm-qt.

> How do you access your camera/smartphone files using LXQt?

Can't your digital camera/smartphone be mounted by pcmanfm-qt as a normal USB storage device? If not, did you try to stop gvfs-gphoto2-volume-monitor and see whether libgphoto2 works?

**Comment by fulalas** [comment]
If I don't install libgphoto2 or If i kill 'gvfs-gphoto2-volume-monitor' I can't mount any camera/smartphone. :(

**Comment by tsujan** [comment]
(1) First, don't kill gvfs-gphoto2-volume-monitor; let it run! I ask again: Can't your digital camera/smartphone be mounted by pcmanfm-qt as a normal USB storage device *when gvfs-gphoto2-volume-monitor is running*?

(2) Only if the answer is "No," install libgphoto2, stop gvfs-gphoto2-volume-monitor and use libgphoto2. I've never tried this but googled your problem and the answer was apparently so.

**Comment by tsujan** [comment]
Or maybe you think that you need to use libgphoto2 when the camera can be mounted as a USB device?! I quote ArchWiki: "Some digital cameras will mount as normal USB storage devices and may not require the use of libgphoto2.".

**Comment by fulalas** [comment]
@tsujan, gvfs-gphoto2-volume-monitor can only run if we install libgphoto2.

1- No, my smartphone isn't recognized as a normal USB storage because it uses MTP (Media Transfer Protocol).
2- If a install libgphoto2 and stop gvfs-gphoto2-volume-monitor, nothing happens when I plug my smartphone. It makes sense, once gvfs-gphoto2-volume-monitor has 'gphoto2' on its name, so it depends on it, right? The only way to see my smartphone files is to keep both gvfs-gphoto2-volume-monitor and libgphoto2, but then I got the annoying error message.

I guess this might be a Pcmanfm-qt bug, once Mint works with libgphoto2 without any error message.

**Comment by tsujan** [comment]
> once gvfs-gphoto2-volume-monitor has 'gphoto2' on its name, so it depends on it, right?

No! In Arch, `gvfs-gphoto2-volume-monitor` belongs to `gvfs-gphoto2`, which doesn't depend on `gphoto2`; I have the former without the latter.

>  Mint works with libgphoto2 without any error message

Is `gvfs-gphoto2-volume-monitor` running there? What's the default file manager there?

**Comment by tsujan** [comment]
One more thing: In your report or in the link you provided, there's no trace of pcmanfm-qt or libfm-qt in the error messages. This is a problem that `gphoto2` has with `gvfs` and you can find similar reports on Internet without pcmanfm-qt too. So, I don't think it can be a pcmanfm-qt bug but rather a `gphoto2` bug.

**Comment by fulalas** [comment]
Not gphoto2, indeed, but libgphoto2 -- man, these names are so confusing, hahaha! Look my terminal output:

```
#/usr/libexec/gvfs-gphoto2-volume-monitor
/usr/libexec/gvfs-gphoto2-volume-monitor: error while loading shared libraries: libgphoto2.so.6: cannot open shared object file: No such file or directory
```

So, if I install libgphoto2, you know... It works, but with that message error.

I tested Mint with XFCE. I think Thunar is the default FM.

**Comment by fulalas** [comment]
Just to make it clear: I'm not using gphoto2 binary, since gphoto2 doesn't help me at all. I'm only using libgphoto2 package because gvfs-gphoto2-volume-monitor depends on it.

**Comment by tsujan** [comment]
> Not gphoto2, indeed, but libgphoto2

Both `gvfs-gphoto2` and `gphoto2` depend on `libgphoto2` but they're independent of each other -- `gvfs-gphoto2-volume-monitor` belongs to `gvfs-gphoto2`, not to `libgphoto2`.

BTW, that error message may show a problem in your system but it isn't related to pcmanfm-qt or libfm.

> I tested Mint with XFCE. I think Thunar is the default FM.

And is `gvfs-gphoto2-volume-monitor` running there?

> I'm not using gphoto2 binary

Now, I don't get what this report is about at all. Both the title and the link you'd added point to `gphoto2` and now you tell it isn't about it?! You say that your smartphone isn't recognized as a normal USB storage, which means you may need `gphoto2`.

> gvfs-gphoto2-volume-monitor can only run if we install libgphoto2.

Completely wrong! I explained why above.

**Comment by tsujan** [comment]
EDIT: Sorry for my the  last statement in tha above comment (I deleted it): I thought you said gvfs-gphoto2-volume-monitor can only run if we install gphoto2....

**Comment by fulalas** [comment]
So, how do you explain this:

```
#ldd ./gvfs-gphoto2-volume-monitor 
        libgphoto2.so.6 => /usr/lib64/../lib64/libgphoto2.so.6 (0x00007f21bf92b000)
        libgphoto2_port.so.12 => /usr/lib64/../lib64/libgphoto2_port.so.12 (0x00007f21bf4db000)
```

?

**Comment by tsujan** [comment]
> So, how do you explain this:

`libgphoto2.so.6` belongs to `libgphoto2`, which is a dependency of both `gvfs-gphoto2` and `gphoto2`. Yes, as you said (and as I deleted my wrong statement) both of them need `libgphoto2`. However, this report is about `gphoto2` giving error messages and, from what I saw on Internet, I think that's because `gphoto2` may not run well when `gvfs-gphoto2-volume-monitor` is running.

**Comment by fulalas** [comment]
> Now, I don't get what this report is about at all. Both the title and the link you'd added point to gphoto2 and now you tell it isn't about it?!

Sorry if this is confusing, but I've been using libgphoto2, never gphoto2.

> You say that your smartphone isn't recognized as a normal USB storage, which means you may need gphoto2.

I simply don't need gphoto2. My smartphone and camera can all be seen by gvfs-gphoto2-volume-monitor + ligphoto2 :)

Thanks for your effort. I'll try to dig a bit deeper. :+1:

**Comment by tsujan** [comment]
@agaida, could you also add a suitable template for reporting pcmanfm-qt bugs to provide users with a clear guide? I think it's needed.

**Comment by fulalas** [comment]
I don't know if you're familiar with Porteus distro, but it has just 4 main modules: kernel, core, xorg and the DE you want to use. Each module is compressed in one single package file (.xzm extension). I'm telling this because Porteus has this unique decoupling so it's easy to test things.

1- Test with LXQt (Pcmanfm-qt FM): everything works, except for the error message.
2- Test with XFCE (Thunar FM): everything works, no message error at all.

I tested both with the same kernel, core and xorg modules, so there's only one variable here: DE. That's why I think this is a problem with Pcmanfm-qt (or maybe another LXQt module).

**Comment by tsujan** [comment]
@fulalas, sorry but, now, I even don't know what the problem is. After a reporting template is added, if you think this is really a pcmanfm-qt bug, you could open another issue with a clear explanation of the problem.

**Comment by fulalas** [comment]
Hmmmm... The problem is the same as written in the first message of this topic: if we plug a camera/smartphone we receive the following error: 'Error initializing camera: -53: Could not claim the USB device'. Just it.

**Comment by tsujan** [comment]
Oh, if it's just about an error message -- which doesn't contain any word about pcmanfm-qt or libfm-qt -- and if you could *use* your camera/smartphone, then it isn't a problem -- or at least, not a pcmanfm-qt problem.

What I saw as a problem was that you might not be able to use your camera/smartphone with pcmanfm-qt for an unknown reason. When people tell about error messages, they usually mean that something doesn't work.

Anyway, a template is really needed; @agaida?

**Comment by tsujan** [comment]
Yes, you said, "In fact, this error doesn't forbid me to access the files," and I read it but I thought you meant you could access it *in another way* because that error was serious.

**Comment by fulalas** [comment]
Yeah, it's not the end of the world, indeed. :)

But it's a problem related to LXQt for sure, as I explained above when testing the **exact** same system using XFCE and got no error message.

**Comment by tsujan** [comment]
It may be about the way libfm uses gvfs but it doesn't prove that way is incorrect. Since it only happens with gphoto2, it's logical to see it as a gphoto2 problem that shows up when gvfs is used in some way but not in another.

Anyway, pcmanfm-qt is going to be independent from libfm -- a long process that's already started. Let's see what will happen when that process is complete!

**Comment by fulalas** [comment]
Right! Let't keep our fingers crossed. :)

**Comment by palinek** [comment]
Where is the error message shown/logged? Can it be, that the pcmanfm-qt/libfm is just a bit more verbose with the errors (than the mentioned thunar)?

**Comment by tsujan** [comment]
> Can it be, that the pcmanfm-qt/libfm is just a bit more verbose with the errors (than the mentioned thunar)?

Maybe but I don't think digging into libfm's code can does anything good now -- unless for porting. I just hope that @PCMan will port the mounting code to libfm-qt soon, so that (1) some serious libfm problems will be eliminated and (2) we could find and fix new problems sooner. A stable pcmanfm-qt without libfm is what I look forward to.

**Comment by fulalas** [comment]
> Where is the error message shown/logged? Can it be, that the pcmanfm-qt/libfm is just a bit more verbose with the errors (than the mentioned thunar)?

It's a MessageBox with a red circle and an exclamation mark inside it: http://img.photobucket.com/albums/v256/Delerue/couldnotclaimusb_zpsdbvxfep2.png

**Comment by tsujan** [comment]
> t's a MessageBox with a red circle and an exclamation mark inside it:

Wow! And I thought it was a message in terminal. That dialog should be annoying!

I reopen this (and will change its title) but please test after libfm-qt becomes independent from libfm in mounting! I'll tell you when.

**Comment by fulalas** [comment]
Some update! I've managed to fix the dialog error by updating Gvfs and removing Libgphoto2. The problem now is that Pcmanfm-qt can't show device labels anymore. Do you know from where it reads the labels?

**Comment by fulalas** [comment]
Everything is fixed now. I had to update glib2 using Slackware package. I'm closing this issue. Thanks, guys!
