### ISSUE TITLE
Can't drag 'n drop a file from Engrampa to any folder, except Desktop

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#488]
This seems to be a pcmanfm-qt specific bug, once Engrampa works fine with Thunar, fo example.

**Comment by tsujan** [comment]
Engrampa's DND doesn't work with Dolphin either. That should be a problem in Engrampa because its DND only works with gtk file managers (like Thunar).

**Comment by tsujan** [comment]
However, since Engrampa's DND works with desktop, this may also be a problem in pcmanfm-qt.

**Comment by tsujan** [comment]
No problem with the latest github version of pcmanfm-qt and Engrampa 1.18.1. Closing this.

**Comment by fulalas** [comment]
This problem remains, even with the latest Git. Do you know any other light archiver manager?
