### ISSUE TITLE
LXQt 0.11 + Qt 5.8 = issue with drag 'n drop files into some text editors

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#490]
With Qt 5.7 if you drop a text file from pcmanfm-qt into a blank instance of Leafpad (text editor) it simply opens it. However, if you do the same with Qt 5.8, Leafpad oddly just writes the file path inside it.

I'm sure this is a problem related to Qt 5.8 since I tested the same LXQt version (0.11 final release) and the problem doesn't appear when using Qt 5.7. Maybe Pcmanfm-qt has to change something in order to work with newer Qt versions.

**Comment by tsujan** [comment]
I can confirm this with Leafpad (which is gtk based) but NOT with FeatherPad or Kate (which are Qt based).

Qt 5.8 has a bad [problem](https://github.com/lxde/lxqt/issues/1257), which will be fixed in the next version, but I don't think this is related to it.

**Comment by fulalas** [comment]
Yep! Tested with FeatherPad and it works flawlessly.

Sad that Qt 5.8 is broken.

**Comment by tsujan** [comment]
This doesn't happen with gEdit, which is also based on gkt (but gtk3). It may be about an old Leafpad code that isn't supported anymore.

Leafpad is very old; do you see this problem with another app too?

**Comment by agaida** [comment]
please try mousepad

**Comment by fulalas** [comment]
Mousepad works.

**Comment by tsujan** [comment]
So, if mousepad, FeatherPad, gEdit and Kate work and only Leafpad doesn't, this should an old piece of code in Leafpad that isn't supported anymore.

**Comment by agaida** [comment]
Did i mention that mouspad is a leafpad fork made by the XFCE guys? And they made a nice, fast and able little editor out of it.

**Comment by fulalas** [comment]
@agaida, cool to know that. :)

BTW, I had the opportunity to test Extix distro with LXQT (extix-64bit-17.4-lxqt-nvidia-1550mb-170418.iso) + Qt 5.7.1, and this problems also happens. So it seems to be a problem starting with this Qt 5.7.1, once 5.7.0 doesn't have it.

**Comment by tsujan** [comment]
> So it seems to be a problem starting with this Qt 5.7.1, once 5.7.0 doesn't have it.

As I said above, I don't think this is a Qt issue but a Leafpad one.

@agaida you've betrayed the qt-based FeatherPad by using the gtk-based mousepad ;)
