### ISSUE TITLE
[regression] Free disk space is not shown in the status bar

### ISSUE THREAD

**Issue by PCMan** [lxde/pcmanfm-qt#494]
Free disk space is no longer shown in the status bar.
Suspect regression bugs caused by recent merge of the c++ 11 port. :-(

**Comment by tsujan** [comment]
Confirming. Strange that I never saw it!

**Comment by tsujan** [comment]
@PCMan 
When fixing this, would you also add
```cpp
folderView_->selectionModel()->clear();
```
before `lastFolderPath_ = folder_->path();` in `TabPage::pathName()`? The statusbar message won't change if the folder is selected before changing directory; the above line fixes that.

**Comment by tsujan** [comment]
I meant in `TabPage::chdir()` -- corrected the comment.

**Comment by PCMan** [comment]
@tsujan Well, let's separate them in differnt issues. I just fixed the free space display one.

**Comment by tsujan** [comment]
OK. I mistakenly though your fix was in pcmanfm-qt.

**Comment by agaida** [comment]
fixed with lxde/libfm-qt#78
