### ISSUE TITLE
Grey out files that have been Ctrl-X'ed

### ISSUE THREAD

**Issue by pkonow** [lxde/pcmanfm-qt#503]
To have some form of visual feedback, files that have been 'cut' via the menu or via Ctrl-X should be marked in some way, e.g. by graying out the icon or text+icon. This is the default behavior on all other file managers and operating systems, afaik.

**Comment by tsujan** [comment]
I agree.

**Comment by agaida** [comment]
+1

**Comment by tsujan** [comment]
This is one of those things that seem very simple but may be hard to implement.

**Comment by tsujan** [comment]
Done by @vc-01 in https://github.com/lxde/libfm-qt/pull/88. Closing.
