### ISSUE TITLE
Include gvfs as a dependency/package on Fedora

### ISSUE THREAD

**Issue by TruboXL** [lxde/pcmanfm-qt#509]
Long standing bug all the way from Fedora 23, still present on Fedora 26
https://bugzilla.redhat.com/show_bug.cgi?id=1300404

Without gvfs, the Devices section in pcmanfm-qt will be blank.

Please include it in the LXQt spin or make it as a dependency.
Thanks.

**Comment by tsujan** [comment]
pcmanfm-qt does not depend on gvfs but could use it if present. It's (rpm, deb,...) packagers' responsibility to add gvfs as a recommendation. But I agree that LXQt should tell its users about that in a more specific way.

**Comment by TruboXL** [comment]
Hmm? I kind of surprised that downstream maintainers are not working on upstream here as opposed to other desktop environments (or maybe there is?)...

Anyway, I have reported to downstream: https://pagure.io/lxqt-remix/issue/3

**Comment by tsujan** [comment]
@agaida has packages for Debian sid (based distros) and Arch has nice PKGBUILDs but I don't know of an LXQt developer that also works on rpm packages for Fedora or OpenSUSE. I can be wrong though.

**Comment by lupinix** [comment]
As I'm one of the Fedora maintainers I'll take care of that. Fedora 26 LXQt will include it by default. In pcmanfm-qt package i will add gvfs as a weak dependency.

**Comment by lupinix** [comment]
Everything submitted, so will be fixed in final, maybe already in beta.

https://pagure.io/fedora-comps/pull-request/126
https://bodhi.fedoraproject.org/updates/pcmanfm-qt-0.11.3-5.fc26

So I guess this can be closed here.

**Comment by TruboXL** [comment]
Thanks! 👍

And to quote someone here that whether pcmanfm-qt should use gvfs or KIO in the future...

> [We'll probably use gvfs. pcmanfm-qt uses gvfs already.](https://github.com/lxde/pcmanfm-qt/issues/61#issuecomment-133776214)

**Comment by tsujan** [comment]
@lupinix Thank you very much!

@TruboXL Yes, we've concluded (implicitly) that GIO is better than KIO; so, as far as I know, pcmanfm-qt will keep using GLib and GIO. Recently, we've had a great change by @PCMan to use GLib is libfm-qt directly and without libfm (the C library). The plan is making pcmanfm-qt and libfm-qt independent of libfm. An important part of the job is already done by @PCMan.
