### ISSUE TITLE
Window of a newly started program added in "Open With..." is by default not in the front

### ISSUE THREAD

**Issue by timlee1** [lxde/pcmanfm-qt#511]
In PCManFM, I right click a pdf file, and set up in "Open With..." to use a Windows program run under Wine to open pdf files.

Now when I double click a pdf file, the Windows program starts and open the pdf file. But the window for the program is not in the front, i.e. doesn't have the focus. How can I make it in the front by default after I double click a pdf file?

I saw https://github.com/lxde/pcmanfm-qt/issues/18, which seems to say that my problem is a feature of OpenBox, the Window Manage of LXDE. However, my problem only happens to the Windows program that I added, not to other programs. When I open pdf files with other programs such as evince, the new windows are in the front.

So how shall I solve my problem?

Thanks.

Note that I asked my question at https://askubuntu.com/q/925540/1471, and a comment pointed me here.

**Comment by agaida** [comment]
erm - this bug tracker is about pcmanfm-qt, not about pcmanfm.

**Comment by tsujan** [comment]
This "issue" isn't related to pcmanfm either. It is about how a window manager may interact with Wine.

Anyhow, as @agaida said, here we develop pcmanfm-qt, not pcmanfm.

**Comment by timlee1** [comment]
Where shall I ask my question? Thanks.
