### ISSUE TITLE
Spacing between files in 'Detailed List' view is incoherent

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#516]
Considering 'Detailed List' view and thumbnail on, If you open a folder with images the spacing between files is incoherent -- i.e. the space between them should not be related to the thumbnail size/proportion. Let's compare.

Thumbnail on:
![spacing](https://user-images.githubusercontent.com/27843666/27434876-574d9cc0-57ae-11e7-8630-e98cf7f022a2.png)

Thumbnail off:
![spacing2](https://user-images.githubusercontent.com/27843666/27435022-d1c56ffa-57ae-11e7-94a6-95521b9fd0ce.png)

**Comment by tsujan** [comment]
Yes, this is a very old bug and its fix is easy. The following screenshot is taken with the fix:

![correct_height](https://user-images.githubusercontent.com/981076/28067192-75a83026-6655-11e7-83c0-2c99f07251e8.png)

But the related libfm-qt PRs should be merged first before a PR is added for this.

**Comment by fulalas** [comment]
Great news! Looking forward to see that :)

**Comment by tsujan** [comment]
To any programmer who might read my comment above before I fix the bug:

It's easy but not as easy as `setUniformRowHeights(true)` because Qt's `uniformRowHeights()` is based on a bad calculation.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxde/libfm-qt/pull/103 -- it needs the latest git source, of course.
