### ISSUE TITLE
Mouse cursor isn't reset after resizing window

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#517]
If you resize pcmanfm-qt by graping the right bottom corner with left mouse button, the cursor doesn't come back to the normal arrow after you release mouse button.

**Comment by agaida** [comment]
for me it does

**Comment by tsujan** [comment]
@fulalas You probably have Qt 5.8, which has this bug among others.

Such problems are never caused by the app itself, whether it is pcmanfm-qt or any other app

**Comment by fulalas** [comment]
@tsujan, you're totally right. I've just built LXQt with Qt 5.9 and I can't see this problem anymore. :)

**Comment by tsujan** [comment]
That was a part of a bad bug in Qt5.8. When Qt was 5.8, I patched it because I couldn't use it with that bug ;)
