### ISSUE TITLE
Drag 'n drop from other programs doesn't work in 'Detailed List'

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#520]
It was kind of reported [here](https://github.com/lxde/pcmanfm-qt/issues/488), but at that time I wasn't aware of the specific scenario, which is pcmanfm-qt being in 'Detailed List' view -- all other views work flawlessly.

So a very easy way to test this is to open an archiver manager like xarchiver/engrampa/etc and drag a file/folder from there to any folder (except desktop).

**Comment by tsujan** [comment]
Should be fixed by https://github.com/lxde/libfm-qt/pull/94.

**Comment by fulalas** [comment]
It fixed. Thanks, man!
