### ISSUE TITLE
compiling doesn't work: filepath.h not found

### ISSUE THREAD

**Issue by HybridDog** [lxde/pcmanfm-qt#523]
When l run make, it aborts compiling:
```
[  1%] Automatic moc for target pcmanfm-qt
[  1%] Built target pcmanfm-qt_automoc
[  3%] Building CXX object pcmanfm/CMakeFiles/pcmanfm-qt.dir/application.cpp.o
In file included from pcmanfm-qt/pcmanfm/desktopwindow.h:24:0,
                 from pcmanfm-qt/pcmanfm/settings.h:28,
                 from pcmanfm-qt/pcmanfm/application.h:25,
                 from pcmanfm-qt/pcmanfm/application.cpp:21:
pcmanfm-qt/pcmanfm/view.h:25:36: fatal error: libfm-qt/core/filepath.h: No such file or directory
 #include <libfm-qt/core/filepath.h>
                                    ^
compilation terminated.
pcmanfm/CMakeFiles/pcmanfm-qt.dir/build.make:195: recipe for target 'pcmanfm/CMakeFiles/pcmanfm-qt.dir/application.cpp.o' failed
make[2]: *** [pcmanfm/CMakeFiles/pcmanfm-qt.dir/application.cpp.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'pcmanfm/CMakeFiles/pcmanfm-qt.dir/all' failed
make[1]: *** [pcmanfm/CMakeFiles/pcmanfm-qt.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
Do l need to set CMAKE_INSTALL_LIBDIR?
If so, what do l need to set it to (not told in README)?

**Comment by HybridDog** [comment]
apt show tells this:

> Package: libfm-qt-dev
Version: 0.11.2-1build1~1

**Comment by agaida** [comment]
and why should this work?  Anyways, downstream problem or picnic, closing this right now.

**Comment by HybridDog** [comment]
According to the README, you do not need qt5 but libdm-qt.

**Comment by tsujan** [comment]
> According to the README, you do not need qt5 but libfm-qt.

LXQt -- including libfm-qt -- is based on Qt5 for ages.

**Comment by HybridDog** [comment]
I'm using lubuntu 17.04 and apt tells me libfm-qt is purely virtual. l can't install it.
l thought for compiling l need to install libfm-qt-dev anyway, installing the dev package in my experience causes also the installation of the one without dev extension because of dependencies.

**Comment by agaida** [comment]
As i said - downstream problem or picnic. I place a bet on the second. And btw.: This is not an upstream problem and we can't solve it. But i don't know that much about ubuntu packages, i tinker only a little bit with debian.
