### ISSUE TITLE
Compact view has serious alignment problems

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#524]
While preparing a patch for inline renaming, I had to work with the compact view for an hour. In short, it's a mess. The alignment problem is random but can be seen with all style plugins (Fusion, Kvantum, Breeze), especially when folders like `/usr/share/applications` are opened. A reload fixes the issue temporarily.

I guess most users don't use the compact view; otherwise someone would report this. I'll think about fixing it but if really no one uses it, why not removing it altogether?

**Comment by fulalas** [comment]
If by 'no one uses it' you mean 'no one comes here in this Git to complain', then I don't think this is a good metric.

Compact View exists in many different FMs, including Windows Explorer, right? I don't think companies would spend money on something that no one uses (Start Menu and recent Windows rings a bell?).

**Comment by tsujan** [comment]
Fixed by https://github.com/lxde/libfm-qt/pull/103. Closing.
