### ISSUE TITLE
Desktop properties shows a wrong size with Ctrl+A, even when some files are deselected

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#525]
If you put a file with X bytes in the desktop, select all (ctrl+a) and then get the properties (alt+enter), you will see more bytes than the actual file size you put there.

Tested with both Manjaro 17.0.2 x64 and current git on Porteus x64.

**Comment by palinek** [comment]
Can you provide some screenshots and output of `ls -l` or something else proving the wrong size reporting?
(here I can't see any discrepancies)

**Comment by fulalas** [comment]
Sure :)

![pcmanfm-qt](https://user-images.githubusercontent.com/27843666/27949782-12768e8a-6353-11e7-81a7-63002aa7a194.png)

At left the single file property, in the middle the ls command inside terminal, and at right the select all property.

**Comment by tsujan** [comment]
@palinek I can't see any problem either. Probably, there was a folder among files he selected.

**Comment by tsujan** [comment]
Wait a minute! There's something funny on Desktop....

**Comment by palinek** [comment]
hm... here is a screenshot with different sizes repored (left side files selected with `ctrl+a`, right `contextMenu->Select All`):
![screenshot](https://user-images.githubusercontent.com/10990929/27950447-ac251fe4-6301-11e7-84e8-4dcb7f2ebb87.png)

... I can kind of repeat it for desktop ... in normal window the sizes are identical.

**Comment by tsujan** [comment]
@palinek yes, there is a bug... I'll try to explain it precisely.

**Comment by tsujan** [comment]
When all files are selected on Desktop with Ctrl+A and then some of them are *deselected*, Properties dialog shows the size of all files: selected + deselected. This only happens on Desktop and not inside the window of pcmanfm-qt, even if desktop is opened as a folder.

I think the fix should be easy...

**Comment by tsujan** [comment]
Apparently, with Ctrl+A and deselection on desktop, files are deselected only visually, while with `Select All` and deselection, files are really deselected:

Ctrl+A+deselection:

![ctrla](https://user-images.githubusercontent.com/981076/27951311-b639a5fa-6319-11e7-9c4e-9244df614802.png)

`Select All`+same deselection:

![selectall](https://user-images.githubusercontent.com/981076/27951315-bc3e9942-6319-11e7-835e-510f71385dfd.png)

**Comment by tsujan** [comment]
No, it's worse than that because I don't have 5.7 GiB on my desktop ;)

**Comment by tsujan** [comment]
Haha, found it! This:
```cpp
connect(shortcut, &QShortcut::activated, listView_, &QListView::selectAll);
```
should be changed to
```cpp
connect(shortcut, &QShortcut::activated, this, &FolderView::selectAll);
```
in `desktopwindow.cpp` :) Will make a PR later.
