### ISSUE TITLE
No custom action with right click in empty space

### ISSUE THREAD

**Issue by mooooonbaby** [lxde/pcmanfm-qt#530]
When i click in the empty space in a folder in the right panel of pcmanfm one of my custom actions is displayed in the context menu. but this doesn't work with pcmanfm-qt. is this the same problem reported here? https://github.com/lxde/pcmanfm-qt/issues/297. i don't right click on the desktop, i do the right click in a empty area in pcmanfm-qt. thsi is the .destop file i tried at last

```
[Desktop Entry]
Type=Action
Name=Edit as Root
Icon=dialog-password
Profiles=profile-zero;

[X-Action-Profile profile-zero]
Exec=gksu nano %f
Name=Default profile
```

its from here https://wiki.manjaro.org/index.php?title=Custom_Actions_for_PCmanFM-Qt

**Comment by tsujan** [comment]
`MimeTypes=inode/directory;` is missing in it. Custom actions work OK here; I use them often.

Closing this but feel free to add comments.

**Comment by tsujan** [comment]
Right clicking in an empty space needs `inode/directory` as MimeTypes but your action doesn't seem to be for directories and, if so, you couldn't expect it to appear on right clicking in an empty space...

**Comment by mooooonbaby** [comment]
No, sorry, doesn't work for me. i've added the mimetype and restarted pcmanfm and pcmanfm-qt and the context menu is displayed with pcmanfm but not with pcmanfm-qt.

i've checked this also in a virtual machine with an other ubuntu and here is the same behaviour.

i should say that i use xfce (xubuntu) and not lxde/lxqt.

**Comment by tsujan** [comment]
pcmanfm-qt's custom actions work OK everywhere, not just under LXQt. I have more than 34 of them and, as said above, use them often.

Maybe your installed version is too old or something else -- you didn't provide any info and I haven't worked on my telepathic faculty for a long time.
