### ISSUE TITLE
Hide folders in folder view

### ISSUE THREAD

**Issue by hollysheep** [lxde/pcmanfm-qt#531]
Is it possible to hide folders in folder view using .hidden files? at the moment it only hides folders in the window where the files and folders are displayed, but not in the tree view. it would be nice to hide all the unused folders (/etc, ...).

**Comment by tsujan** [comment]
Is this a question or a bug report?!

Files are hidden correctly with `.hidden` in both folder view and Directory Tree of the latest pcmanfm-qt.

**Comment by hollysheep** [comment]
a feature request.

the files are hidden, this is true. but not the folders in directory tree. i've made a screenshot how it looks. i created a .hidden file in /.

http://en.zimagez.com/zimage/bildschirmfoto2017-07-1120-20-35.php

**Comment by tsujan** [comment]
Here, all files whose names are included in `.hidden` are hidden in Directory Tree too. Maybe your installed versions of pcmanfm-qt and libfm-qt are too old.

Please fill in the template when reporting a bug or asking for a feature. The template is not just as a formality.

**Comment by hollysheep** [comment]
sorry for that.

my pcmanfm-qt version is 0.11.1. its installed from the lxqt repository. this what i could find about libfm-qt on my system:

```
dpkg -l libfm-qt*
un  libfm-qt
ii  libfm-qt-l10n  0.11.0-19-g7
un  libfm-qt2
ii  libfm-qt3:amd6 0.11.1-3~ubu
un  libfm-qt5-2
```

**Comment by hollysheep** [comment]
i'll try it with libfm-qt. i tought it was installed together with pcmanfm-qt.

**Comment by hollysheep** [comment]
i can't installed libfm-qt because libfm-qt3 ist already installed. i also can libfm-qt5-2 not install because it wants to overwrite "/usr/share/libfm-qt/translations/libfm-qt_it.qm" which is als used in libfm-qt-l10n.

uninstall libfm-qt-l10n first?

**Comment by tsujan** [comment]
> my pcmanfm-qt version is 0.11.1. its installed from the lxqt repository.

Oh, it's VERY old.

> i'll try it with libfm-qt. i tought it was installed together with pcmanfm-qt.

pcmanfm-qt always needs libfm-qt.

> i can't installed libfm-qt because libfm-qt3 ist already installed.....

This seems to be an Ubuntu (downstream) issue again. LXQt has nothing named `libfm-qt3`.

**Comment by tsujan** [comment]
You have 2 options if you want to stay with Ubuntu, IMO:

(1) Tolerate that buggy version until a recent version comes to Ubuntu; or
(2) Learn how to compile and make deb packages from sources.  (Never install with `sudo make install`!)

**Comment by hollysheep** [comment]
0.11.1 is the last version in the lxqt repository.

what do i need to install it from source. only the four dependencies listed here https://github.com/lxde/pcmanfm-qt? (qtx11extras, lxmenu-data, liblxqt and libfm-qt)

**Comment by tsujan** [comment]
> 0.11.1 is the last version in the lxqt repository.

You mean in *Ubuntu's* lxqt repository ;)

> what do i need to install it from source

As I said above, I'd recommend you make deb packages first and only install them. Installing from the source could have bad consequences.

You first need to compile and install `libfm-qt`, which needs `lxqt-build-tools`. And don't forget that you might need to uninstall your current installation first, so you might want to have a DE other than LXQt to do the job from there.

**Comment by tsujan** [comment]
The last recommendation: If you have Ubuntu LTS, you might want to upgrade it to the latest stable Ubuntu; otherwise, Its Qt5 or gcc version might not be supported by LXQt. LTS distros aren't for having bleeding-edge programs.

**Comment by agaida** [comment]
another recommendation - there are lubuntu next isos available - ok, they are in an early state of development, but i think that the lubuntu team will be helpful with any issues - and i think to that they will need a lot of feedback to improve the LXQt iso.

**Comment by hollysheep** [comment]
for me upgrading to 17.04 isn't a option. i use lts because i can install the most of my needed tools very simple using apt-get.

so i tried builing deb files. i started with libfm-qt. it needs qtx11extras, libfm, cmake and lxqt-build-tools. cmake is installed.

lxqt-build-tools needs also cmake and qt5core.

i can't find anything to install qt5core, libfm or qtx11extras. e.g. lxqt-build-tools: here i can find some packages in the repository, but the package name isn't the same. its 'qtx11extras5-dbg'. the same with libfm. for qt5core there is nothing how to install it.

**Comment by agaida** [comment]
then leave current lxqt alone and use the packages provided by ubuntu - and btw - current LXQt (git) will not build with 16.04 LTS. Long Term Support means in other words: No current versions for you, bad luck.

**Comment by hollysheep** [comment]
i could compile a lot of packages from source, but i fail with libfm-qt/libfm. i downloaded the source code for libfm from here https://github.com/lxde/libfm, but there isn't any information how to compile it. cmake and ./configure doesn't work. no CMakeLists.txt for cmake and no ./configure file.

how can i compile it with any information about that?

**Comment by tsujan** [comment]
You can't with Ubuntu LTS.  Do you read our replies? If not, why should we reply?

**Comment by hollysheep** [comment]
i understood it so that its not in the repositories.

can i install an older version of pcmanfm-qt and libfm-qt that supports hide folders also in directory tree on 16.04?

**Comment by tsujan** [comment]
> can i install an older version of pcmanfm-qt and libfm-qt that supports hide folders also in directory tree on 16.04?

No! Good news for you is that the latest version has several problems/regressions regarding Directory Tree (which I'm trying to fix).

**Comment by agaida** [comment]
the easiest way would be an ArchLinux with AUR builds - once @tsujan has finished fixing - or at least Ubuntu 17.10 - or Ubuntu 18.04 - i would recommend the 18.04 because it has apt ...

**Comment by hollysheep** [comment]
i'm on linux since one year and i'm happy to can handle ubuntu :-)

i think i will wait for 18.04.
