### ISSUE TITLE
pcmanfm-qt doesn't remember if hidden files are shown

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#533]
##### Expected Behavior
When `Ctrl+H` is used, pcmanfm-qt should remember if hidden files are shown or not.

##### Current Behavior
When hidden files are shown, if another folder is loaded or the window is closed and reopened, hidden files will be hidden again.

##### Steps to Reproduce (for bugs)

1. Use `Ctrl+H` to show hidden files
2. Change the directory or close and open the window
3. Hidden files will be hidden again

##### System Information

* Everything is the latest version

Please note:

I don't have this issue with my patched pcmanfm-qt and libfm-qt. I saw it once I started to use the default, unpatched sources. So, a confirmation is needed. If confirmed, I should see which one of my unpublished patches fixes the issue.

**Comment by tsujan** [comment]
@agaida Could you confirm this?

**Comment by tsujan** [comment]
Found it, after a long walk under rain :) The story is that I use the original per-folder settings patch I'd proposed in an old PR (which was replaced by @PCMan's method); in that patch, I'd fixed this issue.

Will wait for confirmation.

**Comment by MggMuggins** [comment]
I actually like it hiding the hidden files again. Could that be a configuration option?

**Comment by tsujan** [comment]
When the user presses `Ctrl+H`, he/she wants to see hidden files. Making them hidden again when the directory is changed is an annoying bug not a feature. `Ctrl+H` could be pressed again if hidden files aren't needed to be shown anymore. Sane file managers like Dolphin behave so (Dolphin can remember it with a single setting but that's another matter).

**Comment by tsujan** [comment]
A fix for this and related bugs is at https://github.com/lxde/pcmanfm-qt/pull/535.
