### ISSUE TITLE
inline renaming don't work with context menu

### ISSUE THREAD

**Issue by agaida** [lxde/pcmanfm-qt#545]
##### Expected Behavior
it should :p 

##### Current Behavior
inline renaming works with pcmanfm-qt menu, with F2 but not with Rename from the context menu - the rename dialog appears.

##### Possible Solution
fix it

##### System Information

* libfm-qt Version: latest git
* Package version: latest git

**Comment by tsujan** [comment]
Here it works because the context menu renaming is the first thing done by the PR. However, I'll download the sources and test as soon as I have time.

**Comment by tsujan** [comment]
I couldn't wait ;) downloaded the sources, compiled and installed them. Inline renaming works well both with `f2` and with context menu.

@agaida Are you sure that you don't have an older version of libfm-qt/pcmanfm-qt running?

**Comment by tsujan** [comment]
It even works in lximage-qt ;)

**Comment by agaida** [comment]
well - erm - äh:
```
libfm-qt3:
  Installiert:           0.11.3~134-g67c77de-2
pcmanfm-qt:
  Installiert:           0.11.4~68-g526e3f7-1
```

**Comment by agaida** [comment]
dammit, you are right

**Comment by tsujan** [comment]
@agaida I didn't mean the versions but the running instance of pcmanfm-qt.

I compiled and installed them from git three times and everything was OK. Actually, if anything didn't work, it couldn't be context menu renaming. To me, this report is a complete mystery ;)

**Comment by tsujan** [comment]
> dammit, you are right

How?

**Comment by agaida** [comment]
under investigation right now - it seems that i overlooked a ftbfs - most likely because a symbol change

**Comment by agaida** [comment]
one should remove remove PRs that are applied upstream from patches ... 
Works fine.

**Comment by tsujan** [comment]
> one should remove remove PRs that are applied upstream from patches ... Works fine.

:)

I make such mistakes too; so many patches...
