### ISSUE TITLE
Accept custom folder icons like Dolphin does

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#547]
##### Expected Behavior
It would be better if pcmanfm-qt showed custom folder icons as Dolphin does.

##### Current Behavior
Except for special folders in the home directory, pcmafm-qt shows the same folder icon for all directories because it lacks the capability of showing custom folder icons.

##### Possible Solution
Since I started to use LXQt, I fixed this by https://github.com/lxde/libfm/pull/8 for myself. However, after libfm-qt's C++11 port, there was no need to that patch: a simple libfm-qt patch does the job now and I use it since the C++11 port without problem.

Customizing folder icons is good for finding folders that are special to the user. Personally, I can't use a file manager without this capability. However, I'll wait for votes before adding a PR.

**Comment by vc-01** [comment]
I miss this feature, though I'm used to emblems from other file managers (small icons pinned to original one, mostly on bottom right). Emblems might keep the UI look more consistent but ok this issue is about folder icons. With emblems I use it on files too (not only folders).

(Please, ignore this if you don't want to discuss emblems in this issue)

**Comment by tsujan** [comment]
@vc-01 Emblems are supported for a long time :) You could make an appropriate custom action to add any emblem to any file/folder in pcmanfm-qt. I use emblems for temporary jobs. Custom folder icons can be permanent.

**Comment by tsujan** [comment]
BTW, if features like emblem (and this one when implemented) are hidden, we should find a way to tell users about them in pcmanfm-qt itself. A help dialog?

**Comment by tsujan** [comment]
For the record, I use this a simple script like the following (with `qarma`) in `~/bin` and a custom action to set emblems:
```sh
#!/bin/bash

icon="file://"`qarma --window-icon=emblem-default --file-selection --filename=$HOME/YOUR_EMBLEM_FOLDER/`
if [ "$icon" == "file://" ]; then
   #PLAY_A_SOUND
   exit 1
fi
emblem_name=$(basename "$icon")
emblem_name="`echo ${emblem_name%%.*}`"
if [ $? -eq 0 ]; then
	for arg in "$@"; do
		gvfs-set-attribute "$arg" -t stringv metadata::emblems "$emblem_name"
	done
	xte 'key F5' # reload the folder
fi
exit
```

**Comment by vc-01** [comment]
@tsujan Thank you for your supportive answer, i confirm it works great. Only `gvfs-set-attribute` is a new thing to me, so I thought (until now) emblems were more internal to file manager.

**Comment by tsujan** [comment]
@vc-01 You're welcome!

As far as I know, pcmanfm-qt is the only Qt file manager that *actively* uses GLib -- and I see that as an advantage for several reasons -- so, it can make use of things like `gvfs-set-attribute`. `gvfs-set-attribute` should also work with all gtk file managers that support emblems.

**Comment by tsujan** [comment]
We really need a "help" for pcmanfm-qt. There's no other way for advanced users to know about features that can't be seen in the GUI. The "Help" menu has only an "About" item.

**Comment by vc-01** [comment]
@tsujan I didn't want start an off-topic discussion in this thread but I think too, emblems are just hidden feature to most users in this current state. If it will be documented in "Help" or some new UI dialog for it will be created it's up to what gets more votes. I would prefer a simple in-built UI dialog.

With the GLib thing, I think too it's a plus, maybe in some time `gvfs-set-attribute` will in some way get standardized and land in freedesktop.org, it looks like a possibility to me, we'll see.

**Comment by tsujan** [comment]
@vc-01 I opened https://github.com/lxde/pcmanfm-qt/issues/550 for that.

> I would prefer a simple in-built UI dialog.

I agree.

BTW, `gvfs-set-attribute` isn't new -- gnome2 users knew about it too -- and since it's a GLib-only thing, I don't think it could be a freedesktop.org standard. For example, Dolphin doesn't support user-defined emblems.

**Comment by tsujan** [comment]
There's a "consistency" obstacle concerning a Dolphin-like custom folder icon. Although it's quite possible, GLib doesn't understand it and, as a result, doesn't emit any signal about its change. Any change should be enforced by the code.

However. the same thing can be said about emblems because, although GLib understands them, there's no update signal.

**Comment by tsujan** [comment]
Yet another obstacle to a consistent implementation:

File properties dialog can set the icon when its icon button is clicked but it should refresh the folder too. Refreshing could be implemented if the dialog is called by the File menu. So everything may look fine. However, properties dialog can be called by the context menu too and, unfortunately, such a dialog has no relation to the view and so, can't cause any reload. When file properties dialog was implemented for the first time, the need for a relation to the view couldn't be predicted.

On the other hand, custom folder icon isn't a GFile property, so there's no change signal for it.

Now I ask myself: Should this be implemented without using the icon button of properties dialog (like I use it through a custom action), or should a deeper change be made?

**Comment by tsujan** [comment]
Good news: found a way that's elegant IMO :)

**Comment by artmg** [comment]
Thanks @tsujan for sharing the trick with `gvfs-set-attribute`. 

FYI with gvfs-bin version 1.32.1 I get messages `This tool has been deprecated, use 'gio set' instead.` so the commands I ended up with were 
```
gio set -t stringv ~/FolderName metadata::emblems emblem-shared
gio info ~/FolderName
```
I appreciate the tips
