### ISSUE TITLE
Libfm compilation error

### ISSUE THREAD

**Issue by Ilya87** [lxde/pcmanfm-qt#548]
I use the following command line to compile libfm (master version): 
`./configure \
		--without-gtk \
		--disable-gtk-doc \
		--disable-udisks \
		--enable-actions \
		--prefix="/usr" \
		--sysconfdir="/etc" \
		--disable-debug \
		--disable-exif
&& make`
build fails with error:
`  VALAC    libfmactions_la_vala.stamp
condition.vala:149.18-155.34: warning: unhandled error `GLib.Error'
condition.vala:192.8-193.40: warning: unhandled error `GLib.SpawnError'
action.vala:81.4-81.30: error: use `new' operator to create new objects
                        FileAction.from_keyfile(kf);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
action.vala:144.4-144.34: error: use `new' operator to create new objects
                        FileActionMenu.from_keyfile(kf);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
action.vala:185.28-185.31: warning: Argument 1: Cannot pass null to non-null parameter type
                                cached_children.append(null);
                                                       ^^^^
action.vala:177.8-177.82: warning: unhandled error `GLib.SpawnError'
                                if(Process.spawn_command_line_sync(command, out output, null, out exit_status)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
action.vala:238.21-238.24: warning: Argument 1: Cannot pass null to non-null parameter type
                                children.append(null);
                                                ^^^^
action.vala:334.10-334.40: warning: unhandled error `GLib.KeyFileError'
                                                if(kf.load_from_file(full_path, 0)) {
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 6 warning(s)`

vala version is 0.36.4
##### System Information

* Distribution & Version: Arch Linux x86_64
* Kernel: 
* Qt Version: 5.9.1
* lxqt-build-tools Version: 0.3.2.5.g2fbc431-
* libqtxdg Version: 2.0.0.58.gbc64037
* libfm-qt Version: r536.8494885
* Package version:

**Comment by tsujan** [comment]
We don't develop libfm here. It's page is https://github.com/lxde/libfm and you probably reported this here because that page didn't have an issue section.

I don't close this only because I don't know where libfm issues should be reported. @agaida ?

**Comment by tsujan** [comment]
And if you're an Arch user, why don't you use its PKGBUILDs? [This](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libfm-git), for example.

**Comment by Ilya87** [comment]
I use PKGBUILD. My configure command is a little bit different than in aur's fild. I suppose vala needs to be older (I can obviously be mistaken).

**Comment by agaida** [comment]
@tsujan - yes, lxqt/libfm would work, also the lxde tracker on sourceforge is possible - but to be honest: This is a downstream bug.

**Comment by tsujan** [comment]
@Ilya87 I confirm the issue. I hadn't compiled libfm for months but a few minutes ago, compilation failed with vala-0.36.4:
````
action.vala:81.4-81.30: error: use `new' operator to create new objects
                        FileAction.from_keyfile(kf);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
action.vala:144.4-144.34: error: use `new' operator to create new objects
                        FileActionMenu.from_keyfile(kf);
````
Unfortunately and as I said above, we have no control over libfm. It seems that libfm started to become archaic. Please report the issue on sourceforge! It needs a fix as soon as possible.

Please also note that we started to become independent from libfm but the process isn't finished yet.

@agaida I don't think this is and upstream issue but a problem in libfm.

**Comment by tsujan** [comment]
Correction: I mean "downstream" but wrote "upstream".

**Comment by agaida** [comment]
ok, in that case @LStranger should know about

**Comment by tsujan** [comment]
@agaida It's fix should be straightforward but is important and should be done as soon as possible because it causes a FTBS.

**Comment by agaida** [comment]
https://github.com/lxde/libfm - and it should be fixed, i agree. And it is dead simple: We have three choices:
* We improve collaboration with LXDE - hey, we are the same project, aren't we?
* We get rid of any parts of LXDE as soon as possible, if collaboration is not possible
* If it is a FTBFS we make a pull request and ask polite to include it as soon as possible, if noting happend in an acceptable amount of time we merge it ourself.
I'm afraid that the LXDE Members will not like our last two options and that doing so will not improve the mood and collaboration between the projects but it is in the end the only choice if the first point (collaboration) don't work. 

Sorry, had to be that clear about our choices - and if it sounds to hard, sorry, but reality sucks sometimes. So i clearly would prefer a combination of improving collaboration, sending a PR and let the LXDE guys include it in a timely manner.

**Comment by tsujan** [comment]
> We get rid of any parts of LXDE as soon as possible, if collaboration is not possible

@PCMan has already done this to a great extent. It's not just about the lack of collaboration; *it's a necessity* (as @PCMan and I have explained in different places). It seems @PCMan is very busy, so I thought I might try to continue his work to make libfm-qt more independent from libfm. When the work is complete, we won't need to worry about collaboration :)

At for this part of libfm that causes FTBFS (actions), we don't use it anymore but I don't know of a way of compilation without it.

**Comment by tsujan** [comment]
> If it is a FTBFS we make a pull request and ask polite to include it as soon as possible, if noting happend in an acceptable amount of time we merge it ourself.

I agree. I don't know vala so sorry if this seems stupid but after adding a `new` before `FileAction.from_keyfile(kf);` and `FileActionMenu.from_keyfile(kf);` as the warning message said, the compilation was finished successfully. However, I can't make a PR due to my lack of knowledge about vala. Frankly, I never thought I needed to work with vala but it seems I should learn it ;)

**Comment by agaida** [comment]
nah - we shouldn't force it right now - but we should get rid of the dependencies in the long run. Right now it is important to get this FTBFS fixed, not only for us but for LXDE to.  God damn, why is it impossible in github to move a bug to another tracker?

**Comment by tsujan** [comment]
@agaida Yes, I mean that in the long run and, as I said before, I agree that this FTBFS should be fixed as soon as possible.

Anyone knowledgeable about vala (or with knowledge to fix this)?

**Comment by tsujan** [comment]
Fixed by https://github.com/lxde/libfm/pull/22. The sourceforge.net source may not be synced with github's.

**Comment by LStranger** [comment]
>Fixed by https://github.com/lxde/libfm/pull/22. The sourceforge.net source may not be synced with github's.

There is no sourceforge sources. Only github and git.lxde.org. Thank you very much for merging, it's nice catch.

**Comment by tsujan** [comment]
@LStranger Thanks for the info!

**Comment by tsujan** [comment]
> There is no sourceforge sources. 

Then Arch [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/libfm) should be corrected because it contains:
```
source=(https://downloads.sourceforge.net/pcmanfm/libfm-$pkgver.tar.xz)
```

**Comment by LStranger** [comment]
>source=(https://downloads.sourceforge.net/pcmanfm/libfm-$pkgver.tar.xz)

This is correct, but that are release tarballs, not current sources, so it will be there as soon next version is released.
