### ISSUE TITLE
Ability to go back / after in the history with the mouse

### ISSUE THREAD

**Issue by sudogooglex** [lxde/pcmanfm-qt#549]
With the mouse back/forward buttons, go back / forward, just like in any browser.

##### Expected Behavior

Clicking the mouse back button go back in the history.
Clicking the mouse next button go after in the history.

##### Current Behavior

Clicking the mouse back button does nothing.
Clicking the mouse next button does nothing.

##### Possible Solution

Monitor the back / next mouse buttons and bind the events to the back / after history if enabled.

##### Steps to Reproduce (for bugs)

1. Navigate to folder A
2. Navigate to folder B
3. Click the back mouse button
4. Should view A instead of B

##### Context

Tested with a basic mouse.

##### System Information

* Distribution & Version: LXDE 16.04
* Kernel: 4.4.0-83-generic
* Qt Version: 
* lxqt-build-tools Version: 
* libqtxdg Version:
* libfm-qt Version:
* Package version: PCManFM 1.2.4

**Comment by agaida** [comment]
ok - not having Qt, build tools, qtxdg and libfm-qt should make one rethink the sense of the bug - wrong application. And please file the bug in the Ubuntu Bug Tracker or in pcmanfm

**Comment by fulalas** [comment]
@sudogooglex, it seems that this feature doesn't work when in 'Detailed View List'. I reported this [here](https://sourceforge.net/p/pcmanfm/feature-requests/146/). However, since LXDE is now basically dead, I don't think PCMan will fix this.

**Comment by Demez** [comment]
Still having the issue with it not working in 'Detailed View List'

**Comment by tsujan** [comment]
This is LXQt, not LXDE.
