### ISSUE TITLE
Inline renaming isn't working in 'Detailed List' view

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#553]
Inline renaming is a nice feature, but it seems that it's not working when in 'Detailed List' view.

Also, since original pcmanfm has these useful shortcuts to change the current view (ctrl+1,2,3,4), could it be implemented in pcmanfm-qt too?

**Comment by tsujan** [comment]
Yes, as it was mentioned from the [beginning](https://github.com/lxde/libfm-qt/pull/98/commits/45169fa7cfd07cf20c9adcc01dfc313741a4f601): ".... (the detailed list view needs a separate handling)."

**Comment by tsujan** [comment]
As for shortcuts, yes they can be added.

**Comment by tsujan** [comment]
Detailed list inline renaming with right click menu is implemented by https://github.com/lxde/libfm-qt/pull/110.
Detailed list inline renaming with `F2` is implemented by https://github.com/lxde/pcmanfm-qt/pull/554.

Adding shortcuts for changing view is elementary and will be done in another PR.
