### ISSUE TITLE
device not auto mounted when URI passed on command line

### ISSUE THREAD

**Issue by damonlynch** [lxde/pcmanfm-qt#556]
Provide a URI like this, on the command line:
pcmanfm-qt "mtp://%5Busb%3A003,002%5D/Internal%20storage/DCIM/Camera"

if the device is not mounted, the URI is displayed, but no files are displayed, because the device is not automatically mounted.

I expect that the device should be mounted, and the files displayed. Nautilus does this, for instance.

pcmanfm-qt 0.11.3
Qt 5.7.1
Linux version 4.11.0-10-generic (buildd@lcy01-32) (gcc version 6.3.0 20170618 (Ubuntu 6.3.0-19ubuntu1) ) #15-Ubuntu SMP Thu Jun 29 15:03:41 UTC 2017
Lubuntu next 17.10 daily

**Comment by agaida** [comment]
not an upstream bug, closing this here - you might file a bug in launchpad. Maybe good read about mtp, mtpfs, mtp-tools and jmtpfs might help too. To be crystal clear about it: pcmanfm-qt has nothing to do with mounting devices and such things - that is the resort of udev and the needed device drivers.

If installing and setting up one of this packages helps, please file a bug for pcmanfm-qt in launchpad and ask that pcmanfm-qt should recommend the needed packages.

**Comment by damonlynch** [comment]
I'm sorry if my bug report didn't explain the scenario in enough detail. 

I think you're mistaken if you think the file manager shouldn't know about mounting devices. Allow me to explain why:

1. As you know, mtp / ptp devices can be accessed by a single process at a time. The MTP / PTP device must be freed by the process before it can be accessed another process. 
2. For example, if a process is not a client of GIO / KIO, either it or the user it must instruct GIO / KIO to free the MTP/ PTP device before it can access it. 
3. Consider this common workflow: user inserts PTP device (e.g. a camera), which is auto mounted by GIO or KIO. A GIO / KIO client such as Nautilus or Dolphin displays the device. User ejects / unmounts the PTP device, so they can start a non GIO / KIO program that accesses the device-- one that uses libgphoto2, for example. The device is never physically removed as such -- the user merely wants to use another program to access the device. The file manager still displays the device in its left-most pane, even though the device's contents are no longer currently accessible to it. The user then uses the libgphoto2 client program, which then calls on the file manager to open a URI pointing to somewhere on the PTP device.
4. Nautilus handles this scenario perfectly. Upon receiving the PTP URI, nautilus / GIO re-mount the PTP device and display the exact URI. Dolphin can mount and display the URI too, but Plasma provides no user facing way of "ejecting" (i.e. freeing) the PTP device, the details of which I won't go into here because they're a bit off-topic.
5. I don't know what Lubuntu next does compared to other distros in which pcmanfm-qt is installed. But in Lubuntu next, I guess pcmanfm-qt is using GIO -- is that correct? If pcmanfm-qt can / does use GIO, it's trivial to request it to mount the PTP/MTP device.

So in sum, if by design pcmanfm-qt knows nothing about when to mount a device, then you'll never be able to handle the workflow I outline above, a workflow that is easily handled by file managers like Nautilus, and to some extent by Dolphin.

**Comment by palinek** [comment]
The scenario seems reasonable... @tsujan can you check/confirm it?

**Comment by agaida** [comment]
and again - imho this isn't the filemanager or any other program - mtp is handled by udev and or some user space components. So it might be that downstreams should add the needed packages as dependencies or recommends. Can't really test it, my only available device has a firmware bug.

**Comment by tsujan** [comment]
> The scenario seems reasonable... @tsujan can you check/confirm it?

pcmanfm-qt needs gvfs for various tasks, although it doesn't *depend* on gvfs. If gvfs packages aren't installed, pcmanfm-qt can't even handle trash, let alone digital cameras. Whether this is a disadvantage or good for lightness is another question.

Anyhow, as far as I know, the mount code is still in libfm and we have no control over it until it's ported to libfm-qt.
