### ISSUE TITLE
Drag 'n drop from gtk archive managers misses subfolder drops

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#557]
If you drag a file from an archiver manager (Engrampa, for instance) to the current folder of a pcmanfm dialog it works nice. However if you drop directly to a subfolder, the file ends in the current folder.

**Comment by tsujan** [comment]
Confirmed.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxde/libfm-qt/pull/120
