### ISSUE TITLE
Adding shortcuts to View menu

### ISSUE THREAD

**Issue by artmg** [lxde/pcmanfm-qt#558]
Hi,

I was thinking of modifying **pcmanfm-qt/pcmanfm/main-win.ui** to add shortcuts in to make it work the same as original PCManFM

![pmmanfm-view-menu-shortcuts](https://user-images.githubusercontent.com/6281320/28994371-8548fefc-79c4-11e7-9f33-0e2fcc0cd009.png)

Can anyone let me know if Ctrl-1, Ctrl-2, Ctrl-3 and Ctrl-4 would be _unsuitable_ choices, before I submit a PR. Thanks

**Comment by artmg** [comment]
Doh! Of course, Ctrl+digit switches to the _nth_ tab open, just like in a browser window.

So is there any blueprint suggesting standards for implementing keyboard shortcuts in LxQt, to help guide the choice of which key combination to use?

**Comment by tsujan** [comment]
There's still a problem: `Alt+Right`, `Alt+Up`, ... are used for going forward, up,.... ;)

**Comment by tsujan** [comment]
Closed by https://github.com/lxde/pcmanfm-qt/commit/4a96c1c87498e517a5cda9cd37bbbc40151d9b10 because the view buttons are on the toolbar now.
