### ISSUE TITLE
Can't find breadcrumb / address bar options

### ISSUE THREAD

**Issue by leodom** [lxde/pcmanfm-qt#559]
##### Expected Behavior

To have a way to easily navigate the parent folders of present location.
https://github.com/lxde/pcmanfm-qt/issues/558 : I don't have these 'Path and toolbar" options in my menu (which is btw shown in French to me)

##### Current Behavior

I can only see the address bar and no options to get the breadcrumbs

##### Possible Solution

Not stoning the noob but pitying him and pointing solution

##### System Information

* Distribution & Version: Elementary OS 0.4 Loki
* Kernel: 4.10.0-30-generic
* Qt Version: 
* lxqt-build-tools Version: 
* libqtxdg Version:
* libfm-qt Version:
* Package version: 0.10.1-2

**Comment by tsujan** [comment]
pcmanfm-qt V0.10.1-2?! It's archaic.

BTW, the name is "path-bar".
