### ISSUE TITLE
Replace 20×20 with 22×22 in display settings of pcmanfm-qt

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#562]
Most icon themes include separate 22px icons but no 20px or 12px ones. Separate icons are important with such small sizes because if they're missing, tiny icons might seem blurry (there are well-known methods for making small icons sharp). Moreover, 20 and 12 aren't standard icon sizes anywhere in Linux, as far as I know.

So, I suggest replacing 20 with 22 and removing 12 in pcmafm-qt display settings. Please tell me about your opinion!

**Comment by palinek** [comment]
agreed

**Comment by tsujan** [comment]
This isn't as trivial as it may seem. A unified approach should be taken in `Settings` and `PreferencesDialog`.
