### ISSUE TITLE
Esc key should reset file cuts

### ISSUE THREAD

**Issue by fulalas** [lxde/pcmanfm-qt#565]
It would be nice to polish this great recent commit regarding the grey out cut files by allowing Esc key to reset this action, just like Windows Explorer does.

**Comment by tsujan** [comment]
It would be unintuitive and confusing. You can't compare Windows's clipboard with Linux's. Dolphin doesn't do it either and even if it did, it would be a bug to fix.

**Comment by fulalas** [comment]
So you think it would be a bug, then the issue is closed? Not exactly a democratic discussion, I guess.

**Comment by agaida** [comment]
we are not a democracy - we are a do-ocracy - so one can do two things - discuss some things, (not vote for things - we will never have like or +1 button for bugs) or do some things - esp. writing bugs, fixing bugs and so on.

**Comment by fulalas** [comment]
This a tragicomedy, but if you look very close you can still see some joy on it.

**Comment by tsujan** [comment]
@fulalas 

Your requests may be accepted or rejected -- unless you think they're commands, not requests. If you see it so tragic when they're rejected, no one is responsible for your exaggerated reaction.

**Comment by fulalas** [comment]
The drama is not a request being rejected (or even never being done), of course. But it's being rejected because just one person decides so, with no reasonable explanation, closing the issue with absolutely no interest in a dialog, in listening other opinions.

It does not surprise me that this Git page doesn't have much active members (programmers or users). While you guys insist to program basically for yourselves and behave like if you were gods, that's what is going to happen. It seems though that deep down you're not really interested in that.

Democracy has this _problem_ of requiring conversations, listening, thinking out of the box, changing our minds, etc. But, hey, @agaida already said: this project has no intention to be democratic. So never mind :)

**Comment by palinek** [comment]
> It does not surprise me that this Git page doesn't have much active members (programmers or users). While you guys insist to program basically for yourselves and behave like if you were gods, that's what is going to happen. It seems though that deep down you're not really interested in changing that.

Please, do not start an off-topic flame here. Yes, @tsujan did the decision, that your requested feature is not something we want to implement. As you see it is not the end of the discussion... You are still getting feedback. Any other member of the team can have other opinion and re-open this issue. But as you stated we're lacking man power and nowadays @tsujan is the only one actively developing pcmanfm-qt and we all honor his opinion.

**Comment by tsujan** [comment]
> The drama is not a request being rejected

There's no drama at all. The matter is as simple as @palinek, @agaida and I said. You just received a simple "No" in this specific case. No one ignored, ignores or will ignore your opinions -- otherwise, we wouldn't reply -- but that doesn't guarantee a "Yes".

We have a lot of work to do in spite of our limited free times plus our life problems, so we don't have time to explain everything.
