### ISSUE TITLE
An option to hide Places (in side-pane)

### ISSUE THREAD

**Issue by vit1-irk** [lxde/pcmanfm-qt#580]
GTK version of pcmanfm has much smaller "places" panel different from Qt version

#### Please add to Qt version

* Ability to hide such shortcuts as Desktop, Trash, Applications, Network, etc as GTK version allows
* A setting to remove unnecessary labels (Places, Devices, Bookmarks) to show all shortcut items straight in one column. It's pretty obvious that "16 GB disk" is a removable and "Images" is a directory bookmark

**Comment by tsujan** [comment]
The labels (Places, Devices, Bookmarks) are needed because those items have different meanings: Places are built-in, bookmarks can be changed by the user,....

Apart from labels, do you mean something like https://github.com/lxde/pcmanfm-qt/issues/573?

**Comment by vit1-irk** [comment]
The first point is exactly about a settings option which is present in GTK version and lacks in Qt, see the picture

<img src="https://i.imgur.com/SdsnV7o.png">

**Comment by vit1-irk** [comment]
About second it is at least worth mentioning that the word "Places" is typed twice: one word inside combobox (folder tree & places switch) and another as a label just below.

The first point will fix that UI misunderstanding by design ;)

**Comment by tsujan** [comment]
> ... the word "Places" is typed twice...

The combo label can be changed to "Directory List" or just "List".

Your fist point is quite valid.

**Comment by tsujan** [comment]
A few hours ago, I started to see what our options are. A "Show in Places" setting is quite possible and relatively easy to implement.

However, I'm thinking about a more general approach, like what Dolphin does: a "Hide" checkbox on right-click menus of *all* items and an additional "Show Hidden Items" checkbox somewhere. Contrary to its appearance, it isn't a piece of cake and, as far as I looked into it, there may be 2 different ways of doing it. I'll experiment with both ways in my free time.

**Comment by vit1-irk** [comment]
Ok, it will be cool to see only needed items in sidebar. Still waiting for this

**Comment by tsujan** [comment]
This video shows just a tiny part of the job -- the easiest part -- but explains the idea: https://www.dropbox.com/s/mkl0mb99rrmvxdg/hide_items.mkv

It might take a long time to be completed if agreed upon.

**Comment by tsujan** [comment]
Good news: The code took shape much faster than I thought it would. The `libfm-qt` part is complete; the `pcmanfm-qt` part will be very easy. I'll make two PRs after a few days of testing next week.

**Comment by tsujan** [comment]
If you compile from sources, you could try https://github.com/lxde/libfm-qt/pull/151 and https://github.com/lxde/pcmanfm-qt/pull/629, in this same order.

**Comment by vit1-irk** [comment]
It compiles and runs successfully, however Places is still typed twice =)

Waiting for merging into upstream, thanks

**Comment by tsujan** [comment]
> It compiles and runs successfully, however Places is still typed twice =)

As I said above, IMO, that wasn't an issue to fix. "Places" on the combobox means "places" in contrast to "tree" view.

Thanks for testing!

**Comment by tsujan** [comment]
BTW, neither "Directory List" nor "List" is a good name instead of combo "Places". That's something trivial compared to what's done by the patches and could be decided later but I really don't think it's an issue.
