### ISSUE TITLE
Suggestion: transparent side-pane

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#583]
What about merging the side-pane into its surroundings, as in Dolphin? I mean this:

![1](https://user-images.githubusercontent.com/981076/32145256-8da52a90-bcda-11e7-8296-7b556807ffdf.png)

instead of the default, which is this:

![2](https://user-images.githubusercontent.com/981076/32145260-9a36115c-bcda-11e7-89ce-0c21570765e2.png)

And the same for the side tree-view.

Kvantum can already enforce it with a hacking key.

**Comment by agaida** [comment]
looks good

**Comment by tsujan** [comment]
Yes, I think it looks cleaner and less cluttered that way.

**Comment by palinek** [comment]
How would it handle the scroll bars?

**Comment by tsujan** [comment]
> How would it handle the scroll bars?

Nothing else will change.

**Comment by tsujan** [comment]
The scrollbars in my screenshot are "transient". It isn't related to pcmanfm-qt, specifically.

**Comment by tsujan** [comment]
Sadly, it would be ugly with Breeze:

![breeze](https://user-images.githubusercontent.com/981076/32521129-951029d4-c427-11e7-8847-bb87791bbf52.png)

Although it's OK with fusion:

![fusion](https://user-images.githubusercontent.com/981076/32521249-0be90990-c428-11e7-8304-262bdb327c79.png)

There may be a way to fix the scrollbar for all styles but I don't think it would be worth the extra code -- new bugs might also be introduced. Apparently, we should leave it to the style.

Sorry for the noise! Closing this.

**Comment by MggMuggins** [comment]
Could you simply hide the scrollbar until it's rolled over?

**Comment by tsujan** [comment]
That not only would interfere with the style and so, could have unpredictable consequences but also would require many lines of code. It isn't worth the effort.

After several tests, I'm convinced that it should be left to the style engine.

**Comment by MggMuggins** [comment]
I've been using Breath, and I don't think this looks too bad. (Dolphin)
![screenshot_20171107_173648](https://user-images.githubusercontent.com/16041213/32523767-61fd8cf2-c3e2-11e7-9d3b-a096edda9226.png)
I don't mind the appearance you've got up there either.

**Comment by tsujan** [comment]
I think Dolphin is tuned to Breeze-like themes. I tested with a quite different app and saw the same ugly strip with Breeze.

Maybe I've got too tired today and should retry some other time ;) If I find an elegant way of doing it for all styles, I'll surely reopen this.

**Comment by tsujan** [comment]
OK, my mistake. It's simple and good now:

![breeze1](https://user-images.githubusercontent.com/981076/32525685-ed32938c-c43a-11e7-81d1-f6449f90a005.png)

But it should be done for the file dialog too.

**Comment by MggMuggins** [comment]
Kudos! If I may, what was the mistake?

**Comment by tsujan** [comment]
A silly mistake caused by tiredness ;) although it wasn't as straightforward as I thought either. Will make a PR in minutes.

**Comment by tsujan** [comment]
Here, at last : https://github.com/lxde/libfm-qt/pull/127.

**Comment by tsujan** [comment]
I modified the PR and limited side-pane transparency to the places-view for technical reasons. That's more logical too, IMO.
