### ISSUE TITLE
Unable to switch tabs (Ctrl+tab) while dragging a file

### ISSUE THREAD

**Issue by bennta** [lxde/pcmanfm-qt#585]
Use case would look like:

Pick up a file > Switch tabs (Ctrl+tab) > Drop file into folder open in other tab

Currently can hover the tab until it switches (slow) or just Ctrl+X & Ctrl+V.

This doesn't seem to work in most file managers.

**Comment by tsujan** [comment]
Put the dragged file on the tab you want to switch to and the switch will take place; then you could drop the file into the view. That's much easier; isn't it?

**Comment by bennta** [comment]
I wouldn't say easier, as the delay on hovering the tab to when it switches is pretty slow if you need to do this often, but it definitely works, yes.

Would be more of a nice to have than a need.

**Comment by tsujan** [comment]
The "delay" of hovering is not more than moving one's other hand, pressing `Ctrl` and then pressing `Tab`.
