### ISSUE TITLE
Change folder view by icon

### ISSUE THREAD

**Issue by Ygarr** [lxde/pcmanfm-qt#587]
Change folder view by icon for fast access like nautilus or nemo fm as most frequent action

##### Expected Behavior
Fast click by mouse on prefered folder view - thumbnail, compact, detailed, icon

##### Current Behavior
Currently need to manually to go to View> View > <select one of 4 views>

##### Possible Solution
Visually clear guessable buttons on pane. Hotkeys, shortcuts if  there was such a need previously

 

##### Context
 It is very need for convenient user experience

##### System Information
any

![2017-10-30-222500_283x587_scrot](https://user-images.githubusercontent.com/14309871/32193856-3c9361b6-bdc1-11e7-92de-04dfd71adb7f.png)

**Comment by tsujan** [comment]
I agree.

**Comment by tsujan** [comment]
Is anyone against this for any reason?

**Comment by agaida** [comment]
no

**Comment by MggMuggins** [comment]
If someone is there is always the option to add a config option to disable it in the UI.

**Comment by tsujan** [comment]
I think a config for this would be an overkill. I'm going to implement it without config, although an option could be added later (but for what?)... Since there can be no shortcut for views -- all good shortcuts are already in use (see https://github.com/lxde/pcmanfm-qt/issues/558) --  this should have been done sooner, IMO.

**Comment by tsujan** [comment]
I chose Dolphin's style and generic `QStyle` icons (exactly as in the LXQt file dialog). The look and grouping of buttons depends on the active style. For example, with a Kvantum theme:

![kvbeige](https://user-images.githubusercontent.com/981076/32354819-d2118278-c040-11e7-891e-088a4ee9529d.png)

And with Fusion:

![fusion](https://user-images.githubusercontent.com/981076/32354824-d859f4c6-c040-11e7-88ea-33946e75d8c9.png)

Will make a PR soon.

**Comment by tsujan** [comment]
BTW, if Fusion is used as the style, the icons for the icon and thumbnail views will be chosen from the hard-coded icons of Qt itself, both in the file dialog and here. This is a Fusion issue and isn't related to LXQt. I guess Fusion devs will never recognize it as a bug.
