### ISSUE TITLE
Search no longer works with latest head

### ISSUE THREAD

**Issue by ferronrsmith** [lxde/pcmanfm-qt#588]
##### Expected Behavior

When a search is performed the current window should be filter to only show the items that match your search request

##### Current Behavior

Shows everything

##### Steps to Reproduce (for bugs)

Run a search. e.g : search:///home/?recursive=1&name_regex=*.png

Screen will show the same as before a search was performed.

##### System Information

* Distribution & Version: ubuntu
* Kernel: 4.13.0-15-generic
* Qt Version: 5.9.1
* lxqt-build-tools Version: master
* libqtxdg Version:master
* libfm-qt Version:master
* Package version: 0.12.x

**Comment by tsujan** [comment]
This is about regular expressions. If you want png images, you could use `.\.png$`. Regular expressions are very flexible: different strings may mean the same thing in different ways.

**Comment by tsujan** [comment]
Oh, now I understand: you've mistaken shell name patterns with regular expressions. There are so many sources about regular expressions on the Internet.

**Comment by ferronrsmith** [comment]
I see what I was doing. It's an intermix of wildcard + regex. My bad. It works :+1:

**Comment by tsujan** [comment]
You could also use `^` if you want names with a specific number of characters. For exampe, `^.{2}\.jpg$` means jpg images whose names consist of 2 chars. There are infinite possibilities.
