### ISSUE TITLE
pcmanfm the folder contents are not refreshed

### ISSUE THREAD

**Issue by dglent** [lxde/pcmanfm-qt#595]
##### Expected Behavior
I have a folder with a file. If i delete the folder and i create a new one without this file, it shows however the file. If i press F5 the file disappears because physically never existed in this folder.
Is like a web-browser behaviour loading from the cache

##### Current Behavior
I see an non-existent file in the folder

##### Possible Solution
Refresh the folder when opening

##### Steps to Reproduce (for bugs)
I have a local folder (folder1) from a svn repository.
I delete the folder1 in order to do a fresh checkout
After the checkout i open the folder1 (with the same name) and i see files from the previous time. With a F5 these files disappears

##### System Information
* Distribution & Version: Mageia 6
* Kernel: 4.9.56-desktop-1.mga6
* Qt Version: 5.6.2
* lxqt-build-tools Version: lxqt-build-tools-0.3.2
* libqtxdg Version: lib64qt5xdg2-2.0.0
* libfm-qt Version: libfm-1.2.5 (there is no libfm-qt available in this distro release)
* Package version: 0.11.1

**Comment by tsujan** [comment]
This bug was fixed a long time ago. Your installed pcmanfm-qt is too old. Please upgrade to the latest version (0.12.0)!

**Comment by tsujan** [comment]
And it seems that you've mistaken pcmanfm for *pcmanfm-qt*; they're quit different and the former isn't supported here.

**Comment by dglent** [comment]
Ok thanks
* It is well for the pcmanfm-qt that i ask

**Comment by tsujan** [comment]
Just for the reference: reported [here](https://github.com/lxde/pcmanfm-qt/issues/460) and fixed [here](https://github.com/lxde/libfm-qt/pull/63).
