### ISSUE TITLE
Bulk renaming

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#599]
An option for bulk renaming (in contrast to the ordinary renaming of multiple files) is missing from pcmanfm-qt.

##### Expected Behavior
Bulk renaming would choose a base name and rename the selected files by adding ascending numbers to the base name.

**Comment by tsujan** [comment]
This is what I mean:

![1](https://user-images.githubusercontent.com/981076/32701994-f181116c-c7f4-11e7-870c-d0230ec50e69.png)
![2](https://user-images.githubusercontent.com/981076/32701998-f9bc619c-c7f4-11e7-969a-5dee34999eac.png)
![3](https://user-images.githubusercontent.com/981076/32702001-fef1fd48-c7f4-11e7-86d7-fd32050fdb7b.png)

**Comment by stefonarch** [comment]
Was about to open an issue but it can go here.

> Bulk renaming would choose a base name and rename the selected files by adding ascending numbers to the base name.

Actually it   removes  the extension or you have to  re-insert the extension manually:
<newname>#<extension>

So this could be improved to be more user friendly.

**Comment by agaida** [comment]
@stefonarch - please file a new bug - nobody cares about bugs that are closed one and a half year ago

**Comment by stefonarch** [comment]
ehm some months ;) 
Will do
