### ISSUE TITLE
Feature: Copy path-bar text to selection clipborad on showing path-edit

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#604]
Currently, when the path-edit is shown by clicking on the path-bar or choosing "Edit Path" from its right-click menu, the path text is selected but itsn't copied to the selection clipboard.
##### Expected Behavior
I think when a text is selected, users expect it to be copied into the selection clipboard.

##### Current Behavior
The path text is just selected but not copied.

##### Possible Solution
Easy to do. It has been useful to me for a long time. Is it a useful feature to you?

##### Steps to Reproduce (for bugs)

1. When path buttons are shown, click on an empty space inside the path-bar.
2. The path is selected but isn't copied to the selection clipboard, which seems a little weird to me.

**Comment by palinek** [comment]
Agreed.
