### ISSUE TITLE
Suggestion: A context menu-item to hide/show all Desktop items

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#609]
I'd like to know your opinions/comments about what follows.

I have an extra checkable menu-item in Desktop context menu, which says, "Hide Desktop Items". When it's checked, all Desktop items will disappear -- although they're really there -- and no interaction will be possible with Desktop; it'll just show and, probably, change the wallpaper, with only 2 items in its context menu. When I want to access Desktop items, I just uncheck that menu-item.

I know that an empty Desktop is possible by choosing an empty folder as Desktop but that's somehow artificial because interaction is still possible.

My reason for adding such a menu-item was that my Desktop is usually untidy -- they say, a clean desktop is a sign of a sick mind ;) -- but I have beautiful wallpapers.

Don't hesitate to reject this suggestion!

**Comment by MggMuggins** [comment]
I'm loving the same feature in KDE, so I'd say go for it!

**Comment by tsujan** [comment]
> I'm loving the same feature in KDE

I may be wrong but KDE -- and some other DEs -- give the user an option to have a desktop with or without items. The above-mentioned option is about hiding/showing them -- even when hidden, they are there -- and stop/start interactions with desktop at the same time. The difference may seem marginal at first but it isn't so in practice.

In short, I do want items on desktop but I also like to have a way to hide the mess ;)

**Comment by agaida** [comment]
full ack

**Comment by tsujan** [comment]
So, it wasn't as weird as I thought it might sound :) Will polish the patch I use and make a PR.
