### ISSUE TITLE
Backup file with `.bak` and `.old` too?

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#615]
Currently, `libfm-qt` recognizes `FILE~` as a backup file. However, we also have the extension `.bak`, which creates an `application/x-trash`. For example, I have `/etc/resolv.conf.bak`.

Shouldn't files with that extension be seen as backups too?

EDIT: The extension `.old` also creates `application/x-trash`.

**Comment by tsujan** [comment]
No opinion about this?

**Comment by palinek** [comment]
I never ever want a file manager to hide me any kind of files... so yes no opinion on this, or better I don't care as I will never use this functionality.

**Comment by tsujan** [comment]
> I never ever want a file manager to hide me any kind of files... 

I don't care about this functionality either -- never used it -- but I like consistency. From your comment, I get it that you'll have no objection if `.bak` and `.old` are treated like `~`.

**Comment by palinek** [comment]
> you'll have no objection if .bak and .old are treated like ~

Right. But even better would be to remove "hide/treat special/ backup files" functionality at all :)

**Comment by tsujan** [comment]
> But even better would be to remove "hide/treat special/ backup files" functionality at all :)

I have no objection to that but I also think that some users might curse me if I remove it ;)

**Comment by aramazano** [comment]
From consistency point of view, yes I also think file.bak and file.old should be treated the same way as file~

But from usage point of view, IMHO backup files should not be treated the same way as "dot" files (.file)

Dot files are hidden by definition, whereas backup files are hidden for convenience. Hiding or showing them all by the same token ("show hidden files" option) merges these two cases in one pot, which might be undesirable for some users.

So, ideally, there should be two separate options like "show hidden files" and "show backup files", but this adds on to the overall complexity (both by programming-wise and usage-wise) which may lead to more bloat than it is worth.

So I'm on the fence with this "two separate options" idea.

**Comment by tsujan** [comment]
@aramazano Treading backup files ([now](https://github.com/lxde/libfm-qt/pull/155), all of them) as hidden files is an old option added by PCMan and I don't think it can be a problem, exactly because it's an *option*. Anyhow, this issue and its corresponding PR aren't about it.
