### ISSUE TITLE
Please use Owner instead of the comment field in list view

### ISSUE THREAD

**Issue by agaida** [lxde/pcmanfm-qt#617]
##### Expected Behavior
* Display owner and group field (group optional)
![user](https://user-images.githubusercontent.com/1162845/34070940-4eb7fccc-e26e-11e7-918a-b211b2cc6470.jpg)
* field 5 make absolutly no sense here https://www.cyberciti.biz/faq/understanding-etcpasswd-file-format/

##### Steps to Reproduce (for bugs)
1. See embedded picture - just create a new user with all fields filled out and have fun 

##### System Information
* Distribution & Version: current

**Comment by tsujan** [comment]
Good point! The owner column doesn't show the real owner but his/her full name. I also agree with a group column; it doesn't need to be optional though -- that's the *detailed* list view, after all.

**Comment by tsujan** [comment]
Off topic (sorry, but it's in your screenshot): What should we do with the icons used for compact and detailed list modes? Breeze and some other icon sets have decent icons for them but, for example, gnome-icon-theme doesn't.

**Comment by agaida** [comment]
erm - be pragmatic - just ignore gnome-icon-themes i guess

**Comment by agaida** [comment]
Maybe i should be more verbose about - we make some mistakes sometimes regarding our users. For us it is no big deal just to compile the whole LXQt from git in the right order - may it be for arch, debian or some other distribution. We know the very most pitfalls and know where we have put the dead bodies of our enemies in the basement. Most of our users don't have this knowledge - so we should help them.

And that's the point where distributions jump in - we make the sources and they provide binary packages or resonable receipes to their users - and should go the extra mile to enrich our sources with reasonable dependencies and recommends. We can help with more documentation. 

Examples are Arch or maybe Gentoo - i guess the very most users will prefer AUR or ebuilds from git instead cmake; make; make install - so in these cases it should be possible to depend on a known working icon theme.

**Comment by tsujan** [comment]
@agaida I didn't reply because I agreed with you. I also remembered that those 2 icons were defined in Qt style plugins. Breeze, Oxygen and Kvantum define them in such a way that they're found in KDE icon sets. Fusion and gtk engines choose hard-coded Qt icons. I see this as an issue in the latter styles but it isn't our problem.

**Comment by tsujan** [comment]
@agaida To pacify my coding conscience, I opened https://github.com/lxde/pcmanfm-qt/issues/618.

**Comment by tsujan** [comment]
Please try https://github.com/lxde/libfm-qt/pull/146. Here:

![group](https://user-images.githubusercontent.com/981076/34077469-8c867b30-e31a-11e7-9970-3fc09aa0511a.png)

**Comment by tsujan** [comment]
BTW, Dolphin does the same thing; the full name shouldn't be added, in the first place.
