### ISSUE TITLE
Add Extension column to detailed list view

### ISSUE THREAD

**Issue by kargaroc** [lxde/pcmanfm-qt#624]
PCManFM GTK has a column in the detailed list view for windows-style filename extensions.
PCManFM QT does not.

This would be useful to me, since most of my files have filename extensions, and as such I can save a lot of screen space by using them rather than the Type column.

**Comment by tsujan** [comment]
I can't have PCManFM to see what you describe. You mean, for example, "png" instead of "PNG image"? If so, what could be its use? The ".png" extension is already in the file name.

**Comment by kargaroc** [comment]
>what could be its use?
So that you can click it and sort by extension.

**Comment by tsujan** [comment]
> So that you can click it and sort by extension.

You mean clicking on its header. That's already possible with the type column.

As for the space, the detailed list view has a horizontal scrollbar. No space is really wasted to be saved.

I really doubt that this could be considered as a useful feature.

BTW, please note that pcmanfm and pcmanfm-qt are different apps with different structures. There's no rule that says whatever is in the former should be in the latter.
