### ISSUE TITLE
Add symlink info to status bar

### ISSUE THREAD

**Issue by aramazano** [lxde/pcmanfm-qt#636]
In pcmanfm-qt symlinks are represented with a different icon, but that's all. No other information is shown in the main (detailed list) view, nor in the status bar. I have to look into properties of a symlink to see which file it is pointing to.

In detailed view under the "file type" column, *destination* file type is shown for a symlink (e.g. "plain text file"), whereas it would be better if it read "symbolic link" or "symlink to plain text file" or something like this.

In the status bar it repeats the file name and destination file type, whereas it would be better to show the structure of the symlink, something like "sample-link.txt -> ../../somedirectory/real-file.txt"

##### System Information

* Distribution & Version: Debian Stretch (9.3)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.7.1
* lxqt-build-tools Version: ?
* libqtxdg Version: ?
* libfm-qt Version: libfm-qt3:amd64 0.11.2-1
* Package version: PCManFM-Qt 0.11.3

**Comment by tsujan** [comment]
Symlinks are clearly distinguished from other files by their emblems and their file types are definitely those of their targets.

The only valid feature requested here is some symlink info on the statusbar -- although I'm not sure about cluttering the statusbar.

**Comment by aramazano** [comment]
There are certain situations where I systematically change some symlinks in a directory. When I enter such a directory, I feel clueless regarding which symlink is pointing to which file lately. Then I have to check each symlink's properties to get a picture of the latest setup.

I believe showing symlink structure in the status bar is more of a usability enhancement than clutter.

**Comment by aramazano** [comment]
A more generalized solution might be showing the output of file(1) command in the status bar, without any post-processing at all. Parameters to the command could be adjusted so that the longest output (of file command) can still fit in the space provided by status bar (in case a file has too long a name, then output should be trimmed, so some post-processing might still be needed after all).

For instance something like this could be used for a reasonably concise output:

file -e cdf -e compress -e elf -e tar $FILE

Additionally, full output of the "file" command could be added in the properties dialog. I think That would be cool. This would give better view/control to users, while not getting in the way, I think

So, info gathering part is delegated to the file command, and pcmanfm-qt does only the presentation part. Full info in the right-click dialog should not clutter user experience since it is neatly hidden away in normal use. Since only one file's properties processed at a time, it won't hog the CPU or memory.

In debian, there is dependency drawback (to the file package), though. OTOH it is already installed in any reasonable desktop system, so this dependency would be "already satisfied" in most (if not all) cases. I don't know if in another distro the file command is bundled in the base system.

**Comment by tsujan** [comment]
> A more generalized solution might be showing the output of file(1) command in the status bar

GLib covers it. Using commandlines in the code is a mistake, unless it's about entering commandlines, like in terminal emulators.

**Comment by aramazano** [comment]
> GLib covers it.
That's great.

> Using commandlines in the code is a mistake, unless it's about entering commandlines, like in terminal emulators.
I know. I was a bit too lazy to check the libs. :)

**Comment by tsujan** [comment]
I think this is enough for the statusabar:

![link](https://user-images.githubusercontent.com/981076/34652906-dad095ce-f3f9-11e7-978d-bd8c1d189202.png)

It's very similar to what Dolphin shows.

**Comment by aramazano** [comment]
Fair enough. This would satisfy my original needs. Thank you.

**Comment by tsujan** [comment]
You're welcome. And thanks for the idea. When I saw that Dolphin had it, it became important to me ;)

**Comment by tsujan** [comment]
And, as the last change, let's add something Dolphin doesn't have ;)

When *inside* a folder which is a link to another folder and when no file is selected (like `/lib64` in Arch systems):

![link1](https://user-images.githubusercontent.com/981076/34653302-5aaa98d0-f3ff-11e7-8f22-ff4b119ae599.png)

**Comment by aramazano** [comment]
> And, as the last change, let's add something Dolphin doesn't have ;)

This is cool too. :)

-----------------

> GLib covers it.

As an unrelated side note, I have checked glib's dependencies and it doesn't depend to (i.e. use) libmagic1, whereas file command heavily makes use of it. So I will have to assume that glib has its own means for magic resolution (how?) or it doesn't make use of magics in assessment of file properties. If the latter case is true, then glib might not quite match the versatility of the file command.

Further, I couldn't find a general purpose C/C++ library that depends on libmagic1 or the magic database it uses (checked via "apt-cache rdepends libmagic1 libmagic-mgc").

OTOH it is not feasible to use libmagic1 directly from within pcmanfm-qt for file properties assessment, as file command does more than just magic detection. A library that offers "file"s functionality is needed and I fail to spot one.

So this takes me back to square one, i.e. (having to) use find command from within pcmanfm-qt, or (because this is against best practices) not have this kind of functionality at all.

Properties assesment based only on external properties of a file is still a viable solution, even if it is not as sophisticated as the file command (which makes use both magics and other means).

So I fail to find a perfect library for the job.

(Again, I don't know whether glib has reinvented the wheel, but I don't think so, as it doesn't depend on the/any magics database (libmagic-mgc) and it would be unreasonable to expect such a database might be embedded in glib).

**Comment by tsujan** [comment]
> So I will have to assume that glib has its own means for magic resolution (how?)

Yes, it does. As for the "how" question, I haven't -- and couldn't -- read all GLib sources. I only read those GLib/Qt source files, in which I need to find something.

Anyhow, as for reliability of GLib, suffice it to say, all GTK file managers rely on GLib to do such jobs and I haven't seen a KDE file manager that does them better. Until now, `pcmanfm-qt` is the only Qt file manager that relies on GLib for its core jobs and, as I've said in other places several times, that's one of its advantages: Qt for GUI, GLib for file management.

**Comment by aramazano** [comment]
> Yes, it does.

As far I can see, the only way GLib can do this is through "monolithic duplication".

That is,

(1) GLib should be duplicating what libmagic1 does (i.e. reinvented the wheel) *and* (2) A magics database should be hardcoded in GLib as it doesn't depend on any (hence the term "monolithic").

I'm not going to question, for GLib, how optimal (or sensible) such a strategy is.

**Comment by tsujan** [comment]
> As far I can see, the only way GLib can do this is through "monolithic duplication".

I haven't encountered that term anywhere. I neither understand how you can compare `file`, which is a type identification utility, with `GLib`, which is a low-level system library.

**Comment by aramazano** [comment]
It was a makeshift term humorously coined by me :) as an attempt to highlight two mistakes which shouldn't occur within GLib sphere.

IOW, I was indirectly implying that GLib seems to miss the functionality of `file` utility after all. Yes, it can offer some functions for file identification, but none of them seems to be magic based.

As for `file` vs `GLib` comparison; I don't do that. I was just looking for a library that provides some functions comparable to `file` utility.

**Comment by tsujan** [comment]
> ... but none of them seems to be magic based.

?!

I vaguely remember that I had a similar talk with another user (deja vu?). I should refer people to this comment if they ask again about type detection by `GLib`:

The concept of "duplication" doesn't make sense here because `file` is a commandline utility -- there's no wheel to be reinvented. That's like saying `ffmpeg` is a reinvention of `mplayer`, although such an example doesn't convey at all how different a core library and a commandline utility are from each other.

One of the GLib functions tha are used to detect types is `g_content_type_guess()`, which is very thorough. It calls:

`xdg_mime_get_mime_type_for_data()` → `_xdg_mime_magic_lookup_data()` → `_xdg_mime_magic_match_compare_to_data() ` → `_xdg_mime_magic_matchlet_compare_level()`...

among other things. Please just pay attention to the function names!

**Comment by aramazano** [comment]
But with duplication I was talking about GLib duplicating the functionality of libmagic1 (not that of `file`).

As for `g_content_type_guess()` nested calls, these are related to mime magic. The term "magic" finds use in many contexts. I am really not quite sure if mime_magic and file_magic are the same. Given that they are one and the same, then there is a very interesting sitıation that GLib doesn't depend on libmagic1 (which means GLib is duplicating libmagic functionality) and also doesn't depend on any magics database (meaning that it is hardcoded in GLib). Most interesting indeed.

**Comment by tsujan** [comment]
@aramazano I have a feeling that you have a strange presupposition about `file` being the center of Linux -- if not the universe. Every library -- GLib, Qt, EFL,... -- which wants to guess a mime type without its permission is a duplication ;) I have no problem with that but I don't share such a belief. Let's not continue off-topic talks!

**Comment by tsujan** [comment]
BTW and for the sake of completeness:

> the functionality of libmagic1 (not that of file).

"libmagic1" is a Debian package made out of `file`.

**Comment by agaida** [comment]
@aramazano Only for the records, i will close all bugs in debian for upstream fixed things at sight without processing. There will be exceptions for security related bugs.   
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895327 - please let us avoid not needed work in the future.

**Comment by aramazano** [comment]
@agaida sorry for the bug report. I thought it would be easier for me to concentrate all my bug reports to Debian (use Debian as a hub) for various packages. Didn't think about the inconvenience it entails for you.

So, do I report *all* LXQt related bugs here in github? There is also a pending featherpad related bug report (severity: wishlist) I had submitted to Debian. I can close and move to github, if you wish.
