### ISSUE TITLE
Crash on pasting into search:///

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#643]
This is a very old bug: pasting anything into the search folder causes a crash.

The reason is that the search folder is somehow "artificially" made. The bug is in `libfm` and, sadly, we still depend on it. `libfm` should give an error message on pasting into the search folder but, instead, it tries to do the operation, giving these warnings:
````
... g_file_resolve_relative_path: assertion 'G_IS_FILE (file)' failed
... g_file_copy: assertion 'G_IS_FILE (destination)' failed
````
An easy `libfm-qt` workaround is possible by seeing the search folder -- but not its "subfolders" -- as non-writable. Actually, that's needed apart from the `libfm` bug because the Paste menu-item should be disabled inside the search folder. I may do so in a PR but the issue still remains because files can be dragged and dropped into the search folder. (A workaround can also be added for that but I'm not sure whether it's worth adding.)

**Comment by tsujan** [comment]
[The PR](https://github.com/lxde/libfm-qt/pull/166) prevents the crash in all cases.

Disabling the Paste menu-item in such cases doesn't seem good to me for now.

**Comment by tsujan** [comment]
The real fix is here, in libfm: https://github.com/lxde/libfm/pull/38

**Comment by agaida** [comment]
So it is merged - but it should be released too - @LStranger, we talked over one and a half month ago about a libfm release - what's happend?
