### ISSUE TITLE
Dolphin like split view

### ISSUE THREAD

**Issue by micrococo** [lxde/pcmanfm-qt#644]
Hi.

I use the split view functionality very often, much more than tabs. So I'd like to have it in PCManFM-Qt. PCManFM already has it but I'd like a behaviour like that of Dolphin: pressing F3 splits the view and once split pressing F3 again closes the active half (PCManFM turns the split view into two tabs).

Thanks in advance.

**Comment by tsujan** [comment]
Duplicate of https://github.com/lxde/pcmanfm-qt/issues/104

**Comment by micrococo** [comment]
Sorry, I saw that issue before I posted mine but I didn't consider it to be the same because it is more generic. I'd just like to have two panels, nothing as complex as that, but it's ok closing this issue.

**Comment by tsujan** [comment]
If https://github.com/lxqt/pcmanfm-qt/issues/104 is implemented, this will be too. So, closing.
