### ISSUE TITLE
Option to hide the user subtree in the tree view

### ISSUE THREAD

**Issue by micrococo** [lxde/pcmanfm-qt#645]
Hi.

I'd like to have an option to hide the user home subtree in the tree view in the side panel. I really don't know what this subtree is there for. A "Home" button in the menu bar and/or a bookmark can accomplish the task, so it seems redundant to me and wastes a bit of space.

Thanks in advance.

**Comment by tsujan** [comment]
Already implemented. Please use the latest git.

**Comment by micrococo** [comment]
Really? I think I'm already using latest git[1] and I can't see the option anywhere. I may not have expressed what I want correctly. A picture is worth a thousand words. I want to be able to hide the subtree framed in red. Then you could hide the root node (/) too like Dolphin does.

![pcmanfm-qt](https://user-images.githubusercontent.com/7717273/35642603-de2fdbda-06c3-11e8-86f4-db0140e027de.jpg)

[1] https://build.opensuse.org/package/show/X11:LXQt:git/pcmanfm-qt

**Comment by tsujan** [comment]
Sorry, my mistake! I thought you'd talked about the side-pane places but you meant the directory tree.

That tree has an obvious purpose and its removal couldn't be seen as a feature. Sorry that you see it "redundant" or like a "waste of space" --  the same words could be used about almost anything.

**Comment by micrococo** [comment]
What is the obvious purpose? :) To me it looks like a kind of quick access to the user home folder, but if you add a go-home button in the toolbar you get the same functionality and save the space of the two rows (home subtree and root node). Not much but it is welcome on small screens like my netbook one.

In addition I don't want it to be removed, just an option to hide it if possible and it's not difficult to be implemented. I understand that other people may find it useful.

**Comment by palinek** [comment]
Size of the side pane can be easily changed by dragging the separator... even make it completely invisible.
But I also think, that it can be useful for some people to hide/show the side pane by some button/menu action.

**Comment by tsujan** [comment]
> In addition I don't want it to be removed, just an option to hide it if possible and it's not difficult to be implemented.

We often listen to users and implement their good ideas. Feature requests are really welcome. However, that doesn't mean that every user's personal preferences should be implemented as an option. A split-view (your other report) is a good idea liked by many but removing this or that button/item isn't.

@palinek As far as I understood his words -- and he attached a screenshot too -- he didn't mean hiding the side-pane.

**Comment by micrococo** [comment]
> However, that doesn't mean that every user's personal preferences should be implemented as an option.

I agree. I'm just too used to Dolphin it seems. :)

> @palinek As far as I understood his words -- and he attached a screenshot too -- he didn't mean hiding the side-pane.

You right. Thanks for your time.
