### ISSUE TITLE
Enhancement for wallpaper setting

### ISSUE THREAD

**Issue by AcarBurak** [lxde/pcmanfm-qt#86]
1. In Desktop Preferences > Browse > Open one can only use List and Detail views both of which is meaningless in such a context. Thumbnail view is badly needed!
2. After choosing the wallpaper and pressing OK closes the window, but depending on the image the default/current behaviour of wallpaper setting (stretch, tiling etc.) may not produce a desirable outcome. So one needs to go back. An additional Apply button besides OK would be a fine convenience.

**Comment by tsujan** [comment]
This behavior of closing a dialog after pressing OK can be seen in the new search utility too and I agree that it's an obstacle to usability in some places (but not everywhere). I add it to my TODO list for PR'ing.

**Comment by AcarBurak** [comment]
Thank you for fixing the second part of the issue.

**Comment by tsujan** [comment]
I think this old report can be closed. Its first part boils down to the fact that Qt dialogs don't have an icon view and, unlike KDE, we don't our own open/save dialogs. Maybe another feature request should be opened for that.
