### ISSUE TITLE
Icon theme problem after trying Qt5

### ISSUE THREAD

**Issue by hawkeyed** [lxde/pcmanfm-qt#89]
Hello,
As you can see in the ss the panel's icon theme is Numix. But file manager shows the gnome icon theme. I hope you can fix it. You're my hero
![pcmanfm](https://cloud.githubusercontent.com/assets/7062714/3988311/8c70267a-28ae-11e4-9ef9-478da88a3746.png)

**Comment by tsujan** [comment]
Definitely not an issue.
