### ISSUE TITLE
Entry Compress in right-click menu

### ISSUE THREAD

**Issue by Esclapion** [lxde/pcmanfm-qt#90]
How suppress that, please ? It does nothing for the moment. I don't find where it's set.

**Comment by PCMan** [comment]
You need to set a supported "archiver" in the preferences dialog (advanced page).
Currently, ark, file-roller, and squeeze are supported.

**Comment by pmattern** [comment]
Seems rather like a question that got answered without reply.
Any remaining aspects are covered by #226, IMO.
